// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: common.proto

package dshackle

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChainRef int32

const (
	ChainRef_CHAIN_UNSPECIFIED                  ChainRef = 0
	ChainRef_CHAIN_BITCOIN__MAINNET             ChainRef = 1
	ChainRef_CHAIN_ETHEREUM__MAINNET            ChainRef = 100
	ChainRef_CHAIN_ETHEREUM_CLASSIC__MAINNET    ChainRef = 101
	ChainRef_CHAIN_FANTOM__MAINNET              ChainRef = 102  // Fantom, https://fantom.foundation/
	ChainRef_CHAIN_POLYGON_POS__MAINNET         ChainRef = 1002 // Matic PoS Ethereum sidechain based on Polygon
	ChainRef_CHAIN_RSK__MAINNET                 ChainRef = 1003 // RSK sidechain, https://www.rsk.co/
	ChainRef_CHAIN_ARBITRUM__MAINNET            ChainRef = 1004 // Arbitrum (next generation Layer2 technologies for Ethereum), https://arbitrum.io
	ChainRef_CHAIN_OPTIMISM__MAINNET            ChainRef = 1005 // Optimism (low-cost and lightning-fast Ethereum L2 blockchain), https://www.optimism.io
	ChainRef_CHAIN_BSC__MAINNET                 ChainRef = 1006 // Binance Smart Chain, https://docs.bnbchain.org/docs/learn/intro
	ChainRef_CHAIN_POLYGON_ZKEVM__MAINNET       ChainRef = 1007 // Polygon ZK-EVM
	ChainRef_CHAIN_ARBITRUM_NOVA__MAINNET       ChainRef = 1008 // Arbitrum Nova, https://arbitrum.io
	ChainRef_CHAIN_ZKSYNC__MAINNET              ChainRef = 1009 // zkSync, https://zksync.io/
	ChainRef_CHAIN_BASE__MAINNET                ChainRef = 1010 // Base, https://base.org/
	ChainRef_CHAIN_LINEA__MAINNET               ChainRef = 1011 // Linea, https://docs.linea.build
	ChainRef_CHAIN_GNOSIS__MAINNET              ChainRef = 1012 // Gnosis, https://www.gnosis.io/
	ChainRef_CHAIN_AVALANCHE__MAINNET           ChainRef = 1013 // Avalanche, https://www.avax.network/
	ChainRef_CHAIN_STARKNET__MAINNET            ChainRef = 1014
	ChainRef_CHAIN_AURORA__MAINNET              ChainRef = 1015
	ChainRef_CHAIN_SCROLL__MAINNET              ChainRef = 1016 // https://scroll.io/portal, mainnet for l2 doen't exists now
	ChainRef_CHAIN_MANTLE__MAINNET              ChainRef = 1017
	ChainRef_CHAIN_KLAYTN__MAINNET              ChainRef = 1018 // now it's kaia
	ChainRef_CHAIN_CELO__MAINNET                ChainRef = 1019
	ChainRef_CHAIN_MOONBEAM__MAINNET            ChainRef = 1020
	ChainRef_CHAIN_MOONBEAM__MOONRIVER          ChainRef = 1021
	ChainRef_CHAIN_CRONOS__MAINNET              ChainRef = 1022
	ChainRef_CHAIN_METIS__MAINNET               ChainRef = 1023
	ChainRef_CHAIN_OPBNB__MAINNET               ChainRef = 1024
	ChainRef_CHAIN_KAVA__MAINNET                ChainRef = 1025
	ChainRef_CHAIN_ASTAR__MAINNET               ChainRef = 1026
	ChainRef_CHAIN_VARA__MAINNET                ChainRef = 1027
	ChainRef_CHAIN_SOLANA__MAINNET              ChainRef = 1028
	ChainRef_CHAIN_HAQQ__MAINNET                ChainRef = 1029
	ChainRef_CHAIN_FILECOIN__MAINNET            ChainRef = 1030
	ChainRef_CHAIN_FUSE__MAINNET                ChainRef = 1031
	ChainRef_CHAIN_OKTC__MAINNET                ChainRef = 1032
	ChainRef_CHAIN_MANTA_PACIFIC__MAINNET       ChainRef = 1033
	ChainRef_CHAIN_HARMONY__MAINNET_SHARD_0     ChainRef = 1034
	ChainRef_CHAIN_HARMONY__MAINNET_SHARD_1     ChainRef = 1035
	ChainRef_CHAIN_IMMUTABLE_ZKEVM__MAINNET     ChainRef = 1036
	ChainRef_CHAIN_ZORA__MAINNET                ChainRef = 1037
	ChainRef_CHAIN_MODE__MAINNET                ChainRef = 1038
	ChainRef_CHAIN_EVMOS__MAINNET               ChainRef = 1039
	ChainRef_CHAIN_NEON_EVM__MAINNET            ChainRef = 1040
	ChainRef_CHAIN_BOBA_ETHEREUM__MAINNET       ChainRef = 1041
	ChainRef_CHAIN_HECO__MAINNET                ChainRef = 1042
	ChainRef_CHAIN_RONIN__MAINNET               ChainRef = 1043
	ChainRef_CHAIN_BOBA_BNB__MAINNET            ChainRef = 1044
	ChainRef_CHAIN_ZETA__MAINNET                ChainRef = 1045
	ChainRef_CHAIN_BITTORRENT__MAINNET          ChainRef = 1046
	ChainRef_CHAIN_THUNDERCORE__MAINNET         ChainRef = 1047
	ChainRef_CHAIN_CORE__MAINNET                ChainRef = 1048
	ChainRef_CHAIN_TELOS__MAINNET               ChainRef = 1049
	ChainRef_CHAIN_NEAR__MAINNET                ChainRef = 1050
	ChainRef_CHAIN_BLAST__MAINNET               ChainRef = 1051
	ChainRef_CHAIN_DYMENSION__MAINNET           ChainRef = 1052
	ChainRef_CHAIN_ETHEREUM_BEACON__MAINNET     ChainRef = 1053
	ChainRef_CHAIN_PLAYNANCE__MAINNET           ChainRef = 1054
	ChainRef_CHAIN_REAL__MAINNET                ChainRef = 1055
	ChainRef_CHAIN_LISK__MAINNET                ChainRef = 1056
	ChainRef_CHAIN_COSMOS_HUB_MAINNET           ChainRef = 1057
	ChainRef_CHAIN_TAIKO_MAINNET                ChainRef = 1058
	ChainRef_CHAIN_AXELAR_MAINNET               ChainRef = 1059
	ChainRef_CHAIN_OSMOSIS_MAINNET              ChainRef = 1060
	ChainRef_CHAIN_NEUTRON__MAINNET             ChainRef = 1061
	ChainRef_CHAIN_ROOTSTOCK__MAINNET           ChainRef = 1062
	ChainRef_CHAIN_ZIRCUIT__MAINNET             ChainRef = 1063
	ChainRef_CHAIN_AVAIL__MAINNET               ChainRef = 1064
	ChainRef_CHAIN_FRAXTAL__MAINNET             ChainRef = 1065
	ChainRef_CHAIN_TRON_EVM__MAINNET            ChainRef = 1066
	ChainRef_CHAIN_TRON_HTTP__MAINNET           ChainRef = 1067
	ChainRef_CHAIN_KROMA__MAINNET               ChainRef = 1068
	ChainRef_CHAIN_WEMIX__MAINNET               ChainRef = 1069
	ChainRef_CHAIN_ALEPHZERO__MAINNET           ChainRef = 1070
	ChainRef_CHAIN_POLKADOT__MAINNET            ChainRef = 1071
	ChainRef_CHAIN_KUSAMA__MAINNET              ChainRef = 1072
	ChainRef_CHAIN_METAL_L2__MAINNET            ChainRef = 1073
	ChainRef_CHAIN_BOB__MAINNET                 ChainRef = 1074
	ChainRef_CHAIN_GOAT__MAINNET                ChainRef = 1075
	ChainRef_CHAIN_EVERCLEAR__MAINNET           ChainRef = 1076
	ChainRef_CHAIN_SNAXCHAIN__MAINNET           ChainRef = 1077
	ChainRef_CHAIN_XLAYER__MAINNET              ChainRef = 1078
	ChainRef_CHAIN_SEI__MAINNET                 ChainRef = 1079
	ChainRef_CHAIN_TON__MAINNET                 ChainRef = 1080
	ChainRef_CHAIN_UNICHAIN__MAINNET            ChainRef = 1081
	ChainRef_CHAIN_APECHAIN__MAINNET            ChainRef = 1082
	ChainRef_CHAIN_ZERO__MAINNET                ChainRef = 1083
	ChainRef_CHAIN_WORLDCHAIN__MAINNET          ChainRef = 1084
	ChainRef_CHAIN_CRONOS_ZKEVM__MAINNET        ChainRef = 1085
	ChainRef_CHAIN_VICTION__MAINNET             ChainRef = 1086
	ChainRef_CHAIN_SONIC__MAINNET               ChainRef = 1087
	ChainRef_CHAIN_SUPERSEED__MAINNET           ChainRef = 1088
	ChainRef_CHAIN_INK__MAINNET                 ChainRef = 1089
	ChainRef_CHAIN_ABSTRACT__MAINNET            ChainRef = 1090
	ChainRef_CHAIN_HASHKEY__MAINNET             ChainRef = 1091
	ChainRef_CHAIN_GRAVITY_ALPHA__MAINNET       ChainRef = 1092
	ChainRef_CHAIN_MERLIN__MAINNET              ChainRef = 1093
	ChainRef_CHAIN_PLUME__MAINNET               ChainRef = 1094
	ChainRef_CHAIN_SONEIUM__MAINNET             ChainRef = 1095
	ChainRef_CHAIN_DOGECOIN__MAINNET            ChainRef = 1096
	ChainRef_CHAIN_LITECOIN__MAINNET            ChainRef = 1097
	ChainRef_CHAIN_BITCOIN_CASH__MAINNET        ChainRef = 1098
	ChainRef_CHAIN_BERACHAIN__MAINNET           ChainRef = 1099
	ChainRef_CHAIN_RIPPLE__MAINNET              ChainRef = 1100
	ChainRef_CHAIN_SWELL__MAINNET               ChainRef = 1101
	ChainRef_CHAIN_LENS__MAINNET                ChainRef = 1102
	ChainRef_CHAIN_HYPERLIQUID__MAINNET         ChainRef = 1103
	ChainRef_CHAIN_KADENA__MAINNET              ChainRef = 1104
	ChainRef_CHAIN_HEMI__MAINNET                ChainRef = 1105
	ChainRef_CHAIN_GNOSIS_BEACON_CHAIN__MAINNET ChainRef = 1106
	ChainRef_CHAIN_MONAD__MAINNET               ChainRef = 1107
	ChainRef_CHAIN_SHIBARIUM__MAINNET           ChainRef = 1108
	ChainRef_CHAIN_PLASMA__MAINNET              ChainRef = 1109
	ChainRef_CHAIN_KATANA__MAINNET              ChainRef = 1110
	ChainRef_CHAIN_DOMA__MAINNET                ChainRef = 1111
	ChainRef_CHAIN_SOPHON__MAINNET              ChainRef = 1112
	ChainRef_CHAIN_ARC__MAINNET                 ChainRef = 1113
	ChainRef_CHAIN_0G__MAINNET                  ChainRef = 1114
	ChainRef_CHAIN_SOMNIA__MAINNET              ChainRef = 1115
	ChainRef_CHAIN_BITTENSOR__MAINNET           ChainRef = 1116
	ChainRef_CHAIN_IOTEX__MAINNET               ChainRef = 1117
	ChainRef_CHAIN_XRPL__MAINNET                ChainRef = 1118
	ChainRef_CHAIN_MEZO__MAINNET                ChainRef = 1119
	ChainRef_CHAIN_XDC__MAINNET                 ChainRef = 1120
	ChainRef_CHAIN_CREDITCOIN__MAINNET          ChainRef = 1121
	ChainRef_CHAIN_FLARE__MAINNET               ChainRef = 1122
	ChainRef_CHAIN_OASYS__MAINNET               ChainRef = 1123
	ChainRef_CHAIN_SONGBIRD__MAINNET            ChainRef = 1124
	ChainRef_CHAIN_STORY__MAINNET               ChainRef = 1125
	ChainRef_CHAIN_VECHAIN__MAINNET             ChainRef = 1126
	ChainRef_CHAIN_ZILLIQA2__MAINNET            ChainRef = 1127
	ChainRef_CHAIN_BABYLON__MAINNET             ChainRef = 1128
	ChainRef_CHAIN_AGORIC__MAINNET              ChainRef = 1129
	ChainRef_CHAIN_COREUM__MAINNET              ChainRef = 1130
	ChainRef_CHAIN_FETCH_AI__MAINNET            ChainRef = 1131
	ChainRef_CHAIN_PROVENANCE__MAINNET          ChainRef = 1132
	ChainRef_CHAIN_INITIA__MAINNET              ChainRef = 1133
	ChainRef_CHAIN_INJECTIVE__MAINNET           ChainRef = 1134
	ChainRef_CHAIN_MANTRA__MAINNET              ChainRef = 1135
	ChainRef_CHAIN_BITCOIN_SV__MAINNET          ChainRef = 1136
	ChainRef_CHAIN_DASH__MAINNET                ChainRef = 1137
	ChainRef_CHAIN_DIGIBYTE__MAINNET            ChainRef = 1138
	ChainRef_CHAIN_VERGE__MAINNET               ChainRef = 1139
	ChainRef_CHAIN_ZCASH__MAINNET               ChainRef = 1140
	ChainRef_CHAIN_POLYX__MAINNET               ChainRef = 1141
	ChainRef_CHAIN_ZK_VERIFY__MAINNET           ChainRef = 1142
	ChainRef_CHAIN_WESTEND__MAINNET             ChainRef = 1143
	ChainRef_CHAIN_WESTEND_ASSETHUB__MAINNET    ChainRef = 1144
	ChainRef_CHAIN_PASEO__MAINNET               ChainRef = 1145
	ChainRef_CHAIN_PASEO_ASSETHUB__MAINNET      ChainRef = 1146
	ChainRef_CHAIN_POLKADOT_ASSETHUB__MAINNET   ChainRef = 1147
	ChainRef_CHAIN_MEGAETH__MAINNET             ChainRef = 1148
	ChainRef_CHAIN_TEMPO__MAINNET               ChainRef = 1149
	ChainRef_CHAIN_AZTEC__MAINNET               ChainRef = 1150
	ChainRef_CHAIN_MOCA__MAINNET                ChainRef = 1151
	ChainRef_CHAIN_MORPH__MAINNET               ChainRef = 1152
	ChainRef_CHAIN_TAC_MAINNET                  ChainRef = 1153
	ChainRef_CHAIN_TEA_MAINNET                  ChainRef = 1154
	ChainRef_CHAIN_ALGORAND__MAINNET            ChainRef = 1155
	ChainRef_CHAIN_ORDERLY__MAINNET             ChainRef = 1156
	ChainRef_CHAIN_ABCORE__MAINNET              ChainRef = 1157
	ChainRef_CHAIN_BSQUARED__MAINNET            ChainRef = 1158
	ChainRef_CHAIN_ADI__MAINNET                 ChainRef = 1159
	ChainRef_CHAIN_STABLE__MAINNET              ChainRef = 1160
	ChainRef_CHAIN_JOVAY__MAINNET               ChainRef = 1161
	ChainRef_CHAIN_PHAROS__MAINNET              ChainRef = 1162
	ChainRef_CHAIN_EDGE__MAINNET                ChainRef = 1163
	ChainRef_CHAIN_BOTANIX__MAINNET             ChainRef = 1164
	ChainRef_CHAIN_ROBINHOOD__MAINNET           ChainRef = 1165
	ChainRef_CHAIN_KITE__MAINNET                ChainRef = 1166
	ChainRef_CHAIN_HUMANITY__MAINNET            ChainRef = 1167
	ChainRef_CHAIN_APTOS__MAINNET               ChainRef = 1168
	ChainRef_CHAIN_BITLAYER__MAINNET            ChainRef = 1169
	ChainRef_CHAIN_MOVA__MAINNET                ChainRef = 1170
	ChainRef_CHAIN_ETHERLINK__MAINNET           ChainRef = 1171
	ChainRef_CHAIN_NEO_X__MAINNET               ChainRef = 1172
	ChainRef_CHAIN_MOVA__MAINNET_V2             ChainRef = 1173
	ChainRef_CHAIN_STELLAR__MAINNET             ChainRef = 1174
	ChainRef_CHAIN_CELESTIA__MAINNET            ChainRef = 1175
	ChainRef_CHAIN_SUI__MAINNET                 ChainRef = 1176
	// Testnets start with 10_000
	ChainRef_CHAIN_ETHEREUM__MORDEN                    ChainRef = 10001
	ChainRef_CHAIN_ETHEREUM__KOVAN                     ChainRef = 10002
	ChainRef_CHAIN_BITCOIN__TESTNET                    ChainRef = 10003
	ChainRef_CHAIN_ETHEREUM__ROPSTEN                   ChainRef = 10006
	ChainRef_CHAIN_ETHEREUM__RINKEBY                   ChainRef = 10007
	ChainRef_CHAIN_ETHEREUM__SEPOLIA                   ChainRef = 10008
	ChainRef_CHAIN_FANTOM__TESTNET                     ChainRef = 10016
	ChainRef_CHAIN_GNOSIS__CHIADO                      ChainRef = 10017
	ChainRef_CHAIN_AVALANCHE__FUJI                     ChainRef = 10018
	ChainRef_CHAIN_AURORA__TESTNET                     ChainRef = 10021
	ChainRef_CHAIN_KLAYTN__BAOBAB                      ChainRef = 10024 // now it's kaia-kairos
	ChainRef_CHAIN_SCROLL__SEPOLIA                     ChainRef = 10025
	ChainRef_CHAIN_BSC__TESTNET                        ChainRef = 10026
	ChainRef_CHAIN_ETHEREUM__HOLESKY                   ChainRef = 10027
	ChainRef_CHAIN_CELO__ALFAJORES                     ChainRef = 10028
	ChainRef_CHAIN_MOONBEAM__ALPHA                     ChainRef = 10029
	ChainRef_CHAIN_CRONOS__TESTNET                     ChainRef = 10030
	ChainRef_CHAIN_OPBNB__TESTNET                      ChainRef = 10032
	ChainRef_CHAIN_KAVA__TESTNET                       ChainRef = 10033
	ChainRef_CHAIN_IMMUTABLE_ZKEVM__TESTNET            ChainRef = 10034
	ChainRef_CHAIN_VARA__TESTNET                       ChainRef = 10036
	ChainRef_CHAIN_SOLANA__TESTNET                     ChainRef = 10037
	ChainRef_CHAIN_OPTIMISM__SEPOLIA                   ChainRef = 10038
	ChainRef_CHAIN_SOLANA__DEVNET                      ChainRef = 10039
	ChainRef_CHAIN_BASE__SEPOLIA                       ChainRef = 10040
	ChainRef_CHAIN_HAQQ__TESTNET                       ChainRef = 10041
	ChainRef_CHAIN_FILECOIN__CALIBRATION               ChainRef = 10042
	ChainRef_CHAIN_OKTC__TESTNET                       ChainRef = 10044
	ChainRef_CHAIN_ZKSYNC__SEPOLIA                     ChainRef = 10046
	ChainRef_CHAIN_BERACHAIN__ARTIO                    ChainRef = 10047
	ChainRef_CHAIN_POLYGON__AMOY                       ChainRef = 10048
	ChainRef_CHAIN_BLAST__SEPOLIA                      ChainRef = 10049
	ChainRef_CHAIN_LISK__TESTNET                       ChainRef = 10050
	ChainRef_CHAIN_ARBITRUM__SEPOLIA                   ChainRef = 10051
	ChainRef_CHAIN_ZORA__SEPOLIA                       ChainRef = 10053
	ChainRef_CHAIN_MODE__TESTNET                       ChainRef = 10054
	ChainRef_CHAIN_EVMOS__TESTNET                      ChainRef = 10055
	ChainRef_CHAIN_NEON_EVM__DEVNET                    ChainRef = 10056
	ChainRef_CHAIN_HECO__TESTNET                       ChainRef = 10057
	ChainRef_CHAIN_METIS__SEPOLIA                      ChainRef = 10058
	ChainRef_CHAIN_PLAYNANCE__TESTNET                  ChainRef = 10059
	ChainRef_CHAIN_BITTORRENT__TESTNET                 ChainRef = 10060
	ChainRef_CHAIN_THUNDERCORE__TESTNET                ChainRef = 10061
	ChainRef_CHAIN_CORE__TESTNET                       ChainRef = 10062
	ChainRef_CHAIN_TELOS__TESTNET                      ChainRef = 10063
	ChainRef_CHAIN_NEAR__TESTNET                       ChainRef = 10064
	ChainRef_CHAIN_NEAR__BETANET                       ChainRef = 10065
	ChainRef_CHAIN_MANTLE__SEPOLIA                     ChainRef = 10066
	ChainRef_CHAIN_OP_CELESTIA_RASPBERRY__TESTNET      ChainRef = 10067
	ChainRef_CHAIN_ARBITRUM_BLUEBERRY__TESTNET         ChainRef = 10068
	ChainRef_CHAIN_ETHEREUM_BEACON__SEPOLIA            ChainRef = 10070
	ChainRef_CHAIN_ETHEREUM_BEACON__HOLESKY            ChainRef = 10071
	ChainRef_CHAIN_POLYGON_BLACKBERRY__TESTNET         ChainRef = 10072
	ChainRef_CHAIN_POLYGON_ZKEVM_CARDONA_TESTNET       ChainRef = 10073
	ChainRef_CHAIN_LINEA__SEPOLIA                      ChainRef = 10074
	ChainRef_CHAIN_STARKNET__SEPOLIA                   ChainRef = 10075
	ChainRef_CHAIN_MANTA_PACIFIC__SEPOLIA              ChainRef = 10076
	ChainRef_CHAIN_EVERCLEAR__SEPOLIA                  ChainRef = 10077
	ChainRef_CHAIN_ALEPHZERO__SEPOLIA                  ChainRef = 10078
	ChainRef_CHAIN_COSMOS_HUB__TESTNET                 ChainRef = 10079
	ChainRef_CHAIN_TAIKO_HEKLA__TESTNET                ChainRef = 10080
	ChainRef_CHAIN_AXELAR__TESTNET                     ChainRef = 10081
	ChainRef_CHAIN_OSMOSIS__TESTNET                    ChainRef = 10082
	ChainRef_CHAIN_NEUTRON__TESTNET                    ChainRef = 10083
	ChainRef_CHAIN_ROOTSTOCK__TESTNET                  ChainRef = 10084
	ChainRef_CHAIN_OPEN_CAMPUS_CODEX__SEPOLIA          ChainRef = 10085
	ChainRef_CHAIN_GAMESWIFT__TESTNET                  ChainRef = 10086
	ChainRef_CHAIN_ZETA__TESTNET                       ChainRef = 10087
	ChainRef_CHAIN_ZIRCUIT__TESTNET                    ChainRef = 10088
	ChainRef_CHAIN_AVAIL__TURING_TESTNET               ChainRef = 10089
	ChainRef_CHAIN_FRAXTAL___TESTNET                   ChainRef = 10090
	ChainRef_CHAIN_TRON_EVM__SHASTA                    ChainRef = 10091
	ChainRef_CHAIN_TRON_HTTP__SHASTA                   ChainRef = 10092
	ChainRef_CHAIN_KROMA__SEPOLIA                      ChainRef = 10093
	ChainRef_CHAIN_WEMIX__TESTNET                      ChainRef = 10094
	ChainRef_CHAIN_METAL_L2__TESTNET                   ChainRef = 10095
	ChainRef_CHAIN_BOB__TESTNET                        ChainRef = 10096
	ChainRef_CHAIN_SNAXCHAIN__TESTNET                  ChainRef = 10098
	ChainRef_CHAIN_XLAYER__TESTNET                     ChainRef = 10099
	ChainRef_CHAIN_SEI__TESTNET                        ChainRef = 10100
	ChainRef_CHAIN_SEI__DEVNET                         ChainRef = 10101
	ChainRef_CHAIN_RONIN__SAIGON                       ChainRef = 10102
	ChainRef_CHAIN_SONIC__TESTNET                      ChainRef = 10103
	ChainRef_CHAIN_LENS__TESTNET                       ChainRef = 10104
	ChainRef_CHAIN_UNICHAIN__SEPOLIA                   ChainRef = 10105
	ChainRef_CHAIN_APECHAIN__SEPOLIA                   ChainRef = 10106
	ChainRef_CHAIN_SONEIUM__TESTNET                    ChainRef = 10107
	ChainRef_CHAIN_TON__TESTNET                        ChainRef = 10108
	ChainRef_CHAIN_GOAT__TESTNET3                      ChainRef = 10109
	ChainRef_CHAIN_WORLDCHAIN__SEPOLIA                 ChainRef = 10110
	ChainRef_CHAIN_CRONOS_ZKEVM__TESTNET               ChainRef = 10111
	ChainRef_CHAIN_VICTION__TESTNET                    ChainRef = 10112
	ChainRef_CHAIN_0G_NEWTON__TESTNET                  ChainRef = 10113
	ChainRef_CHAIN_SUPERSEED__SEPOLIA                  ChainRef = 10114
	ChainRef_CHAIN_INK__SEPOLIA                        ChainRef = 10115
	ChainRef_CHAIN_ABSTRACT__SEPOLIA                   ChainRef = 10116
	ChainRef_CHAIN_HASHKEY__TESTNET                    ChainRef = 10117
	ChainRef_CHAIN_GRAVITY_ALPHA__SEPOLIA              ChainRef = 10118
	ChainRef_CHAIN_HYPERLIQUID__TESTNET                ChainRef = 10119
	ChainRef_CHAIN_MERLIN__TESTNET                     ChainRef = 10120
	ChainRef_CHAIN_MEZO__TESTNET                       ChainRef = 10121
	ChainRef_CHAIN_PLUME__DEVNET                       ChainRef = 10122
	ChainRef_CHAIN_PLUME__TESTNET                      ChainRef = 10123
	ChainRef_CHAIN_MONAD__TESTNET                      ChainRef = 10124
	ChainRef_CHAIN_DOGECOIN__TESTNET                   ChainRef = 10125
	ChainRef_CHAIN_LITECOIN__TESTNET                   ChainRef = 10126
	ChainRef_CHAIN_BITCOIN_CASH__TESTNET               ChainRef = 10127
	ChainRef_CHAIN_RIPPLE__TESTNET                     ChainRef = 10128
	ChainRef_CHAIN_SWELL__TESTNET                      ChainRef = 10129
	ChainRef_CHAIN_ZIRCUIT__GARFIELD                   ChainRef = 10130
	ChainRef_CHAIN_ETHEREUM__HOODI                     ChainRef = 10131
	ChainRef_CHAIN_ETHEREUM_BEACON__HOODI              ChainRef = 10132
	ChainRef_CHAIN_BERACHAIN__BEPOLIA                  ChainRef = 10133
	ChainRef_CHAIN_KADENA__TESTNET                     ChainRef = 10134
	ChainRef_CHAIN_OZEAN__TESTNET                      ChainRef = 10135
	ChainRef_CHAIN_0G_GALILEO__TESTNET                 ChainRef = 10136
	ChainRef_CHAIN_MEGAETH__TESTNET                    ChainRef = 10137
	ChainRef_CHAIN_HEMI__TESTNET                       ChainRef = 10138
	ChainRef_CHAIN_CELO__SEPOLIA                       ChainRef = 10139
	ChainRef_CHAIN_SONIC__TESTNET_V2                   ChainRef = 10140
	ChainRef_CHAIN_GNOSIS_CHIADO_BEACON_CHAIN__TESTNET ChainRef = 10141
	ChainRef_CHAIN_PLASMA__TESTNET                     ChainRef = 10142
	ChainRef_CHAIN_KATANA__TESTNET                     ChainRef = 10143
	ChainRef_CHAIN_TAIKO__HOODI                        ChainRef = 10144
	ChainRef_CHAIN_DOMA__TESTNET                       ChainRef = 10145
	ChainRef_CHAIN_SOPHON__TESTNET                     ChainRef = 10146
	ChainRef_CHAIN_ARC__TESTNET                        ChainRef = 10147
	ChainRef_CHAIN_SOMNIA__TESTNET                     ChainRef = 10148
	ChainRef_CHAIN_BITTENSOR__TESTNET                  ChainRef = 10149
	ChainRef_CHAIN_DOGEOS__TESTNET                     ChainRef = 10150
	ChainRef_CHAIN_IOTEX__TESTNET                      ChainRef = 10151
	ChainRef_CHAIN_XRPL__TESTNET                       ChainRef = 10152
	ChainRef_CHAIN_XRPL__DEVNET                        ChainRef = 10153
	ChainRef_CHAIN_TEMPO__TESTNET                      ChainRef = 10154
	ChainRef_CHAIN_XDC__TESTNET                        ChainRef = 10155
	ChainRef_CHAIN_CREDITCOIN__TESTNET                 ChainRef = 10156
	ChainRef_CHAIN_CREDITCOIN__DEVNET                  ChainRef = 10157
	ChainRef_CHAIN_FLARE__TESTNET                      ChainRef = 10158
	ChainRef_CHAIN_OASYS__TESTNET                      ChainRef = 10159
	ChainRef_CHAIN_SONGBIRD__TESTNET                   ChainRef = 10160
	ChainRef_CHAIN_STORY__TESTNET                      ChainRef = 10161
	ChainRef_CHAIN_STORY_AENEID__TESTNET               ChainRef = 10162
	ChainRef_CHAIN_VECHAIN__TESTNET                    ChainRef = 10163
	ChainRef_CHAIN_ZILLIQA2__TESTNET                   ChainRef = 10164
	ChainRef_CHAIN_ZILLIQA2__DEVNET                    ChainRef = 10165
	ChainRef_CHAIN_BABYLON__TESTNET                    ChainRef = 10166
	ChainRef_CHAIN_COREUM__TESTNET                     ChainRef = 10167
	ChainRef_CHAIN_FETCH_AI__TESTNET                   ChainRef = 10168
	ChainRef_CHAIN_PROVENANCE__TESTNET                 ChainRef = 10169
	ChainRef_CHAIN_INITIA__TESTNET                     ChainRef = 10170
	ChainRef_CHAIN_INJECTIVE__TESTNET                  ChainRef = 10171
	ChainRef_CHAIN_MANTRA__TESTNET                     ChainRef = 10172
	ChainRef_CHAIN_BITCOIN_SV__TESTNET                 ChainRef = 10173
	ChainRef_CHAIN_DASH__TESTNET                       ChainRef = 10174
	ChainRef_CHAIN_DIGIBYTE__TESTNET                   ChainRef = 10175
	ChainRef_CHAIN_VERGE__TESTNET                      ChainRef = 10176
	ChainRef_CHAIN_ZCASH__TESTNET                      ChainRef = 10177
	ChainRef_CHAIN_POLYX__TESTNET                      ChainRef = 10178
	ChainRef_CHAIN_ZK_VERIFY__TESTNET                  ChainRef = 10183
	ChainRef_CHAIN_TEMPO_MODERATO__TESTNET             ChainRef = 10184
	ChainRef_CHAIN_MEGAETH__TESTNET_V2                 ChainRef = 10185
	ChainRef_CHAIN_AZTEC__TESTNET                      ChainRef = 10186
	ChainRef_CHAIN_AZTEC__DEVNET                       ChainRef = 10187
	ChainRef_CHAIN_MOCA__TESTNET                       ChainRef = 10188
	ChainRef_CHAIN_MORPH__TESTNET                      ChainRef = 10189
	ChainRef_CHAIN_ROBINHOOD__TESTNET                  ChainRef = 10190
	ChainRef_CHAIN_TACSPB__TESTNET                     ChainRef = 10191
	ChainRef_CHAIN_TEA__SEPOLIA                        ChainRef = 10192
	ChainRef_CHAIN_ALGORAND__TESTNET                   ChainRef = 10193
	ChainRef_CHAIN_ALGORAND__BETANET                   ChainRef = 10194
	ChainRef_CHAIN_ORDERLY__TESTNET                    ChainRef = 10195
	ChainRef_CHAIN_STABLE__TESTNET                     ChainRef = 10196
	ChainRef_CHAIN_JOVAY__SEPOLIA                      ChainRef = 10197
	ChainRef_CHAIN_PHAROS__TESTNET                     ChainRef = 10198
	ChainRef_CHAIN_PHAROS_ATLANTIC__TESTNET            ChainRef = 10199
	ChainRef_CHAIN_EDGE__TESTNET                       ChainRef = 10200
	ChainRef_CHAIN_BOTANIX__TESTNET                    ChainRef = 10201
	ChainRef_CHAIN_HUMANITY__TESTNET                   ChainRef = 10202
	ChainRef_CHAIN_APTOS__TESTNET                      ChainRef = 10203
	ChainRef_CHAIN_BITLAYER__TESTNET                   ChainRef = 10204
	ChainRef_CHAIN_MOVA__TESTNET                       ChainRef = 10205
	ChainRef_CHAIN_ETHERLINK__SHADOWNET                ChainRef = 10206
	ChainRef_CHAIN_NEO_X__TESTNET                      ChainRef = 10207
	ChainRef_CHAIN_STELLAR__TESTNET                    ChainRef = 10208
	ChainRef_CHAIN_CELESTIA__MOCHA                     ChainRef = 10209
	ChainRef_CHAIN_SUI__TESTNET                        ChainRef = 10210
	ChainRef_CHAIN_SUI__DEVNET                         ChainRef = 10211
	// Virtual chains (no real blockchain)
	ChainRef_CHAIN_LAMBDA__VIRTUAL ChainRef = 100000 // P2P Lambda REST API synthetic provider
)

// Enum value maps for ChainRef.
var (
	ChainRef_name = map[int32]string{
		0:      "CHAIN_UNSPECIFIED",
		1:      "CHAIN_BITCOIN__MAINNET",
		100:    "CHAIN_ETHEREUM__MAINNET",
		101:    "CHAIN_ETHEREUM_CLASSIC__MAINNET",
		102:    "CHAIN_FANTOM__MAINNET",
		1002:   "CHAIN_POLYGON_POS__MAINNET",
		1003:   "CHAIN_RSK__MAINNET",
		1004:   "CHAIN_ARBITRUM__MAINNET",
		1005:   "CHAIN_OPTIMISM__MAINNET",
		1006:   "CHAIN_BSC__MAINNET",
		1007:   "CHAIN_POLYGON_ZKEVM__MAINNET",
		1008:   "CHAIN_ARBITRUM_NOVA__MAINNET",
		1009:   "CHAIN_ZKSYNC__MAINNET",
		1010:   "CHAIN_BASE__MAINNET",
		1011:   "CHAIN_LINEA__MAINNET",
		1012:   "CHAIN_GNOSIS__MAINNET",
		1013:   "CHAIN_AVALANCHE__MAINNET",
		1014:   "CHAIN_STARKNET__MAINNET",
		1015:   "CHAIN_AURORA__MAINNET",
		1016:   "CHAIN_SCROLL__MAINNET",
		1017:   "CHAIN_MANTLE__MAINNET",
		1018:   "CHAIN_KLAYTN__MAINNET",
		1019:   "CHAIN_CELO__MAINNET",
		1020:   "CHAIN_MOONBEAM__MAINNET",
		1021:   "CHAIN_MOONBEAM__MOONRIVER",
		1022:   "CHAIN_CRONOS__MAINNET",
		1023:   "CHAIN_METIS__MAINNET",
		1024:   "CHAIN_OPBNB__MAINNET",
		1025:   "CHAIN_KAVA__MAINNET",
		1026:   "CHAIN_ASTAR__MAINNET",
		1027:   "CHAIN_VARA__MAINNET",
		1028:   "CHAIN_SOLANA__MAINNET",
		1029:   "CHAIN_HAQQ__MAINNET",
		1030:   "CHAIN_FILECOIN__MAINNET",
		1031:   "CHAIN_FUSE__MAINNET",
		1032:   "CHAIN_OKTC__MAINNET",
		1033:   "CHAIN_MANTA_PACIFIC__MAINNET",
		1034:   "CHAIN_HARMONY__MAINNET_SHARD_0",
		1035:   "CHAIN_HARMONY__MAINNET_SHARD_1",
		1036:   "CHAIN_IMMUTABLE_ZKEVM__MAINNET",
		1037:   "CHAIN_ZORA__MAINNET",
		1038:   "CHAIN_MODE__MAINNET",
		1039:   "CHAIN_EVMOS__MAINNET",
		1040:   "CHAIN_NEON_EVM__MAINNET",
		1041:   "CHAIN_BOBA_ETHEREUM__MAINNET",
		1042:   "CHAIN_HECO__MAINNET",
		1043:   "CHAIN_RONIN__MAINNET",
		1044:   "CHAIN_BOBA_BNB__MAINNET",
		1045:   "CHAIN_ZETA__MAINNET",
		1046:   "CHAIN_BITTORRENT__MAINNET",
		1047:   "CHAIN_THUNDERCORE__MAINNET",
		1048:   "CHAIN_CORE__MAINNET",
		1049:   "CHAIN_TELOS__MAINNET",
		1050:   "CHAIN_NEAR__MAINNET",
		1051:   "CHAIN_BLAST__MAINNET",
		1052:   "CHAIN_DYMENSION__MAINNET",
		1053:   "CHAIN_ETHEREUM_BEACON__MAINNET",
		1054:   "CHAIN_PLAYNANCE__MAINNET",
		1055:   "CHAIN_REAL__MAINNET",
		1056:   "CHAIN_LISK__MAINNET",
		1057:   "CHAIN_COSMOS_HUB_MAINNET",
		1058:   "CHAIN_TAIKO_MAINNET",
		1059:   "CHAIN_AXELAR_MAINNET",
		1060:   "CHAIN_OSMOSIS_MAINNET",
		1061:   "CHAIN_NEUTRON__MAINNET",
		1062:   "CHAIN_ROOTSTOCK__MAINNET",
		1063:   "CHAIN_ZIRCUIT__MAINNET",
		1064:   "CHAIN_AVAIL__MAINNET",
		1065:   "CHAIN_FRAXTAL__MAINNET",
		1066:   "CHAIN_TRON_EVM__MAINNET",
		1067:   "CHAIN_TRON_HTTP__MAINNET",
		1068:   "CHAIN_KROMA__MAINNET",
		1069:   "CHAIN_WEMIX__MAINNET",
		1070:   "CHAIN_ALEPHZERO__MAINNET",
		1071:   "CHAIN_POLKADOT__MAINNET",
		1072:   "CHAIN_KUSAMA__MAINNET",
		1073:   "CHAIN_METAL_L2__MAINNET",
		1074:   "CHAIN_BOB__MAINNET",
		1075:   "CHAIN_GOAT__MAINNET",
		1076:   "CHAIN_EVERCLEAR__MAINNET",
		1077:   "CHAIN_SNAXCHAIN__MAINNET",
		1078:   "CHAIN_XLAYER__MAINNET",
		1079:   "CHAIN_SEI__MAINNET",
		1080:   "CHAIN_TON__MAINNET",
		1081:   "CHAIN_UNICHAIN__MAINNET",
		1082:   "CHAIN_APECHAIN__MAINNET",
		1083:   "CHAIN_ZERO__MAINNET",
		1084:   "CHAIN_WORLDCHAIN__MAINNET",
		1085:   "CHAIN_CRONOS_ZKEVM__MAINNET",
		1086:   "CHAIN_VICTION__MAINNET",
		1087:   "CHAIN_SONIC__MAINNET",
		1088:   "CHAIN_SUPERSEED__MAINNET",
		1089:   "CHAIN_INK__MAINNET",
		1090:   "CHAIN_ABSTRACT__MAINNET",
		1091:   "CHAIN_HASHKEY__MAINNET",
		1092:   "CHAIN_GRAVITY_ALPHA__MAINNET",
		1093:   "CHAIN_MERLIN__MAINNET",
		1094:   "CHAIN_PLUME__MAINNET",
		1095:   "CHAIN_SONEIUM__MAINNET",
		1096:   "CHAIN_DOGECOIN__MAINNET",
		1097:   "CHAIN_LITECOIN__MAINNET",
		1098:   "CHAIN_BITCOIN_CASH__MAINNET",
		1099:   "CHAIN_BERACHAIN__MAINNET",
		1100:   "CHAIN_RIPPLE__MAINNET",
		1101:   "CHAIN_SWELL__MAINNET",
		1102:   "CHAIN_LENS__MAINNET",
		1103:   "CHAIN_HYPERLIQUID__MAINNET",
		1104:   "CHAIN_KADENA__MAINNET",
		1105:   "CHAIN_HEMI__MAINNET",
		1106:   "CHAIN_GNOSIS_BEACON_CHAIN__MAINNET",
		1107:   "CHAIN_MONAD__MAINNET",
		1108:   "CHAIN_SHIBARIUM__MAINNET",
		1109:   "CHAIN_PLASMA__MAINNET",
		1110:   "CHAIN_KATANA__MAINNET",
		1111:   "CHAIN_DOMA__MAINNET",
		1112:   "CHAIN_SOPHON__MAINNET",
		1113:   "CHAIN_ARC__MAINNET",
		1114:   "CHAIN_0G__MAINNET",
		1115:   "CHAIN_SOMNIA__MAINNET",
		1116:   "CHAIN_BITTENSOR__MAINNET",
		1117:   "CHAIN_IOTEX__MAINNET",
		1118:   "CHAIN_XRPL__MAINNET",
		1119:   "CHAIN_MEZO__MAINNET",
		1120:   "CHAIN_XDC__MAINNET",
		1121:   "CHAIN_CREDITCOIN__MAINNET",
		1122:   "CHAIN_FLARE__MAINNET",
		1123:   "CHAIN_OASYS__MAINNET",
		1124:   "CHAIN_SONGBIRD__MAINNET",
		1125:   "CHAIN_STORY__MAINNET",
		1126:   "CHAIN_VECHAIN__MAINNET",
		1127:   "CHAIN_ZILLIQA2__MAINNET",
		1128:   "CHAIN_BABYLON__MAINNET",
		1129:   "CHAIN_AGORIC__MAINNET",
		1130:   "CHAIN_COREUM__MAINNET",
		1131:   "CHAIN_FETCH_AI__MAINNET",
		1132:   "CHAIN_PROVENANCE__MAINNET",
		1133:   "CHAIN_INITIA__MAINNET",
		1134:   "CHAIN_INJECTIVE__MAINNET",
		1135:   "CHAIN_MANTRA__MAINNET",
		1136:   "CHAIN_BITCOIN_SV__MAINNET",
		1137:   "CHAIN_DASH__MAINNET",
		1138:   "CHAIN_DIGIBYTE__MAINNET",
		1139:   "CHAIN_VERGE__MAINNET",
		1140:   "CHAIN_ZCASH__MAINNET",
		1141:   "CHAIN_POLYX__MAINNET",
		1142:   "CHAIN_ZK_VERIFY__MAINNET",
		1143:   "CHAIN_WESTEND__MAINNET",
		1144:   "CHAIN_WESTEND_ASSETHUB__MAINNET",
		1145:   "CHAIN_PASEO__MAINNET",
		1146:   "CHAIN_PASEO_ASSETHUB__MAINNET",
		1147:   "CHAIN_POLKADOT_ASSETHUB__MAINNET",
		1148:   "CHAIN_MEGAETH__MAINNET",
		1149:   "CHAIN_TEMPO__MAINNET",
		1150:   "CHAIN_AZTEC__MAINNET",
		1151:   "CHAIN_MOCA__MAINNET",
		1152:   "CHAIN_MORPH__MAINNET",
		1153:   "CHAIN_TAC_MAINNET",
		1154:   "CHAIN_TEA_MAINNET",
		1155:   "CHAIN_ALGORAND__MAINNET",
		1156:   "CHAIN_ORDERLY__MAINNET",
		1157:   "CHAIN_ABCORE__MAINNET",
		1158:   "CHAIN_BSQUARED__MAINNET",
		1159:   "CHAIN_ADI__MAINNET",
		1160:   "CHAIN_STABLE__MAINNET",
		1161:   "CHAIN_JOVAY__MAINNET",
		1162:   "CHAIN_PHAROS__MAINNET",
		1163:   "CHAIN_EDGE__MAINNET",
		1164:   "CHAIN_BOTANIX__MAINNET",
		1165:   "CHAIN_ROBINHOOD__MAINNET",
		1166:   "CHAIN_KITE__MAINNET",
		1167:   "CHAIN_HUMANITY__MAINNET",
		1168:   "CHAIN_APTOS__MAINNET",
		1169:   "CHAIN_BITLAYER__MAINNET",
		1170:   "CHAIN_MOVA__MAINNET",
		1171:   "CHAIN_ETHERLINK__MAINNET",
		1172:   "CHAIN_NEO_X__MAINNET",
		1173:   "CHAIN_MOVA__MAINNET_V2",
		1174:   "CHAIN_STELLAR__MAINNET",
		1175:   "CHAIN_CELESTIA__MAINNET",
		1176:   "CHAIN_SUI__MAINNET",
		10001:  "CHAIN_ETHEREUM__MORDEN",
		10002:  "CHAIN_ETHEREUM__KOVAN",
		10003:  "CHAIN_BITCOIN__TESTNET",
		10006:  "CHAIN_ETHEREUM__ROPSTEN",
		10007:  "CHAIN_ETHEREUM__RINKEBY",
		10008:  "CHAIN_ETHEREUM__SEPOLIA",
		10016:  "CHAIN_FANTOM__TESTNET",
		10017:  "CHAIN_GNOSIS__CHIADO",
		10018:  "CHAIN_AVALANCHE__FUJI",
		10021:  "CHAIN_AURORA__TESTNET",
		10024:  "CHAIN_KLAYTN__BAOBAB",
		10025:  "CHAIN_SCROLL__SEPOLIA",
		10026:  "CHAIN_BSC__TESTNET",
		10027:  "CHAIN_ETHEREUM__HOLESKY",
		10028:  "CHAIN_CELO__ALFAJORES",
		10029:  "CHAIN_MOONBEAM__ALPHA",
		10030:  "CHAIN_CRONOS__TESTNET",
		10032:  "CHAIN_OPBNB__TESTNET",
		10033:  "CHAIN_KAVA__TESTNET",
		10034:  "CHAIN_IMMUTABLE_ZKEVM__TESTNET",
		10036:  "CHAIN_VARA__TESTNET",
		10037:  "CHAIN_SOLANA__TESTNET",
		10038:  "CHAIN_OPTIMISM__SEPOLIA",
		10039:  "CHAIN_SOLANA__DEVNET",
		10040:  "CHAIN_BASE__SEPOLIA",
		10041:  "CHAIN_HAQQ__TESTNET",
		10042:  "CHAIN_FILECOIN__CALIBRATION",
		10044:  "CHAIN_OKTC__TESTNET",
		10046:  "CHAIN_ZKSYNC__SEPOLIA",
		10047:  "CHAIN_BERACHAIN__ARTIO",
		10048:  "CHAIN_POLYGON__AMOY",
		10049:  "CHAIN_BLAST__SEPOLIA",
		10050:  "CHAIN_LISK__TESTNET",
		10051:  "CHAIN_ARBITRUM__SEPOLIA",
		10053:  "CHAIN_ZORA__SEPOLIA",
		10054:  "CHAIN_MODE__TESTNET",
		10055:  "CHAIN_EVMOS__TESTNET",
		10056:  "CHAIN_NEON_EVM__DEVNET",
		10057:  "CHAIN_HECO__TESTNET",
		10058:  "CHAIN_METIS__SEPOLIA",
		10059:  "CHAIN_PLAYNANCE__TESTNET",
		10060:  "CHAIN_BITTORRENT__TESTNET",
		10061:  "CHAIN_THUNDERCORE__TESTNET",
		10062:  "CHAIN_CORE__TESTNET",
		10063:  "CHAIN_TELOS__TESTNET",
		10064:  "CHAIN_NEAR__TESTNET",
		10065:  "CHAIN_NEAR__BETANET",
		10066:  "CHAIN_MANTLE__SEPOLIA",
		10067:  "CHAIN_OP_CELESTIA_RASPBERRY__TESTNET",
		10068:  "CHAIN_ARBITRUM_BLUEBERRY__TESTNET",
		10070:  "CHAIN_ETHEREUM_BEACON__SEPOLIA",
		10071:  "CHAIN_ETHEREUM_BEACON__HOLESKY",
		10072:  "CHAIN_POLYGON_BLACKBERRY__TESTNET",
		10073:  "CHAIN_POLYGON_ZKEVM_CARDONA_TESTNET",
		10074:  "CHAIN_LINEA__SEPOLIA",
		10075:  "CHAIN_STARKNET__SEPOLIA",
		10076:  "CHAIN_MANTA_PACIFIC__SEPOLIA",
		10077:  "CHAIN_EVERCLEAR__SEPOLIA",
		10078:  "CHAIN_ALEPHZERO__SEPOLIA",
		10079:  "CHAIN_COSMOS_HUB__TESTNET",
		10080:  "CHAIN_TAIKO_HEKLA__TESTNET",
		10081:  "CHAIN_AXELAR__TESTNET",
		10082:  "CHAIN_OSMOSIS__TESTNET",
		10083:  "CHAIN_NEUTRON__TESTNET",
		10084:  "CHAIN_ROOTSTOCK__TESTNET",
		10085:  "CHAIN_OPEN_CAMPUS_CODEX__SEPOLIA",
		10086:  "CHAIN_GAMESWIFT__TESTNET",
		10087:  "CHAIN_ZETA__TESTNET",
		10088:  "CHAIN_ZIRCUIT__TESTNET",
		10089:  "CHAIN_AVAIL__TURING_TESTNET",
		10090:  "CHAIN_FRAXTAL___TESTNET",
		10091:  "CHAIN_TRON_EVM__SHASTA",
		10092:  "CHAIN_TRON_HTTP__SHASTA",
		10093:  "CHAIN_KROMA__SEPOLIA",
		10094:  "CHAIN_WEMIX__TESTNET",
		10095:  "CHAIN_METAL_L2__TESTNET",
		10096:  "CHAIN_BOB__TESTNET",
		10098:  "CHAIN_SNAXCHAIN__TESTNET",
		10099:  "CHAIN_XLAYER__TESTNET",
		10100:  "CHAIN_SEI__TESTNET",
		10101:  "CHAIN_SEI__DEVNET",
		10102:  "CHAIN_RONIN__SAIGON",
		10103:  "CHAIN_SONIC__TESTNET",
		10104:  "CHAIN_LENS__TESTNET",
		10105:  "CHAIN_UNICHAIN__SEPOLIA",
		10106:  "CHAIN_APECHAIN__SEPOLIA",
		10107:  "CHAIN_SONEIUM__TESTNET",
		10108:  "CHAIN_TON__TESTNET",
		10109:  "CHAIN_GOAT__TESTNET3",
		10110:  "CHAIN_WORLDCHAIN__SEPOLIA",
		10111:  "CHAIN_CRONOS_ZKEVM__TESTNET",
		10112:  "CHAIN_VICTION__TESTNET",
		10113:  "CHAIN_0G_NEWTON__TESTNET",
		10114:  "CHAIN_SUPERSEED__SEPOLIA",
		10115:  "CHAIN_INK__SEPOLIA",
		10116:  "CHAIN_ABSTRACT__SEPOLIA",
		10117:  "CHAIN_HASHKEY__TESTNET",
		10118:  "CHAIN_GRAVITY_ALPHA__SEPOLIA",
		10119:  "CHAIN_HYPERLIQUID__TESTNET",
		10120:  "CHAIN_MERLIN__TESTNET",
		10121:  "CHAIN_MEZO__TESTNET",
		10122:  "CHAIN_PLUME__DEVNET",
		10123:  "CHAIN_PLUME__TESTNET",
		10124:  "CHAIN_MONAD__TESTNET",
		10125:  "CHAIN_DOGECOIN__TESTNET",
		10126:  "CHAIN_LITECOIN__TESTNET",
		10127:  "CHAIN_BITCOIN_CASH__TESTNET",
		10128:  "CHAIN_RIPPLE__TESTNET",
		10129:  "CHAIN_SWELL__TESTNET",
		10130:  "CHAIN_ZIRCUIT__GARFIELD",
		10131:  "CHAIN_ETHEREUM__HOODI",
		10132:  "CHAIN_ETHEREUM_BEACON__HOODI",
		10133:  "CHAIN_BERACHAIN__BEPOLIA",
		10134:  "CHAIN_KADENA__TESTNET",
		10135:  "CHAIN_OZEAN__TESTNET",
		10136:  "CHAIN_0G_GALILEO__TESTNET",
		10137:  "CHAIN_MEGAETH__TESTNET",
		10138:  "CHAIN_HEMI__TESTNET",
		10139:  "CHAIN_CELO__SEPOLIA",
		10140:  "CHAIN_SONIC__TESTNET_V2",
		10141:  "CHAIN_GNOSIS_CHIADO_BEACON_CHAIN__TESTNET",
		10142:  "CHAIN_PLASMA__TESTNET",
		10143:  "CHAIN_KATANA__TESTNET",
		10144:  "CHAIN_TAIKO__HOODI",
		10145:  "CHAIN_DOMA__TESTNET",
		10146:  "CHAIN_SOPHON__TESTNET",
		10147:  "CHAIN_ARC__TESTNET",
		10148:  "CHAIN_SOMNIA__TESTNET",
		10149:  "CHAIN_BITTENSOR__TESTNET",
		10150:  "CHAIN_DOGEOS__TESTNET",
		10151:  "CHAIN_IOTEX__TESTNET",
		10152:  "CHAIN_XRPL__TESTNET",
		10153:  "CHAIN_XRPL__DEVNET",
		10154:  "CHAIN_TEMPO__TESTNET",
		10155:  "CHAIN_XDC__TESTNET",
		10156:  "CHAIN_CREDITCOIN__TESTNET",
		10157:  "CHAIN_CREDITCOIN__DEVNET",
		10158:  "CHAIN_FLARE__TESTNET",
		10159:  "CHAIN_OASYS__TESTNET",
		10160:  "CHAIN_SONGBIRD__TESTNET",
		10161:  "CHAIN_STORY__TESTNET",
		10162:  "CHAIN_STORY_AENEID__TESTNET",
		10163:  "CHAIN_VECHAIN__TESTNET",
		10164:  "CHAIN_ZILLIQA2__TESTNET",
		10165:  "CHAIN_ZILLIQA2__DEVNET",
		10166:  "CHAIN_BABYLON__TESTNET",
		10167:  "CHAIN_COREUM__TESTNET",
		10168:  "CHAIN_FETCH_AI__TESTNET",
		10169:  "CHAIN_PROVENANCE__TESTNET",
		10170:  "CHAIN_INITIA__TESTNET",
		10171:  "CHAIN_INJECTIVE__TESTNET",
		10172:  "CHAIN_MANTRA__TESTNET",
		10173:  "CHAIN_BITCOIN_SV__TESTNET",
		10174:  "CHAIN_DASH__TESTNET",
		10175:  "CHAIN_DIGIBYTE__TESTNET",
		10176:  "CHAIN_VERGE__TESTNET",
		10177:  "CHAIN_ZCASH__TESTNET",
		10178:  "CHAIN_POLYX__TESTNET",
		10183:  "CHAIN_ZK_VERIFY__TESTNET",
		10184:  "CHAIN_TEMPO_MODERATO__TESTNET",
		10185:  "CHAIN_MEGAETH__TESTNET_V2",
		10186:  "CHAIN_AZTEC__TESTNET",
		10187:  "CHAIN_AZTEC__DEVNET",
		10188:  "CHAIN_MOCA__TESTNET",
		10189:  "CHAIN_MORPH__TESTNET",
		10190:  "CHAIN_ROBINHOOD__TESTNET",
		10191:  "CHAIN_TACSPB__TESTNET",
		10192:  "CHAIN_TEA__SEPOLIA",
		10193:  "CHAIN_ALGORAND__TESTNET",
		10194:  "CHAIN_ALGORAND__BETANET",
		10195:  "CHAIN_ORDERLY__TESTNET",
		10196:  "CHAIN_STABLE__TESTNET",
		10197:  "CHAIN_JOVAY__SEPOLIA",
		10198:  "CHAIN_PHAROS__TESTNET",
		10199:  "CHAIN_PHAROS_ATLANTIC__TESTNET",
		10200:  "CHAIN_EDGE__TESTNET",
		10201:  "CHAIN_BOTANIX__TESTNET",
		10202:  "CHAIN_HUMANITY__TESTNET",
		10203:  "CHAIN_APTOS__TESTNET",
		10204:  "CHAIN_BITLAYER__TESTNET",
		10205:  "CHAIN_MOVA__TESTNET",
		10206:  "CHAIN_ETHERLINK__SHADOWNET",
		10207:  "CHAIN_NEO_X__TESTNET",
		10208:  "CHAIN_STELLAR__TESTNET",
		10209:  "CHAIN_CELESTIA__MOCHA",
		10210:  "CHAIN_SUI__TESTNET",
		10211:  "CHAIN_SUI__DEVNET",
		100000: "CHAIN_LAMBDA__VIRTUAL",
	}
	ChainRef_value = map[string]int32{
		"CHAIN_UNSPECIFIED":                         0,
		"CHAIN_BITCOIN__MAINNET":                    1,
		"CHAIN_ETHEREUM__MAINNET":                   100,
		"CHAIN_ETHEREUM_CLASSIC__MAINNET":           101,
		"CHAIN_FANTOM__MAINNET":                     102,
		"CHAIN_POLYGON_POS__MAINNET":                1002,
		"CHAIN_RSK__MAINNET":                        1003,
		"CHAIN_ARBITRUM__MAINNET":                   1004,
		"CHAIN_OPTIMISM__MAINNET":                   1005,
		"CHAIN_BSC__MAINNET":                        1006,
		"CHAIN_POLYGON_ZKEVM__MAINNET":              1007,
		"CHAIN_ARBITRUM_NOVA__MAINNET":              1008,
		"CHAIN_ZKSYNC__MAINNET":                     1009,
		"CHAIN_BASE__MAINNET":                       1010,
		"CHAIN_LINEA__MAINNET":                      1011,
		"CHAIN_GNOSIS__MAINNET":                     1012,
		"CHAIN_AVALANCHE__MAINNET":                  1013,
		"CHAIN_STARKNET__MAINNET":                   1014,
		"CHAIN_AURORA__MAINNET":                     1015,
		"CHAIN_SCROLL__MAINNET":                     1016,
		"CHAIN_MANTLE__MAINNET":                     1017,
		"CHAIN_KLAYTN__MAINNET":                     1018,
		"CHAIN_CELO__MAINNET":                       1019,
		"CHAIN_MOONBEAM__MAINNET":                   1020,
		"CHAIN_MOONBEAM__MOONRIVER":                 1021,
		"CHAIN_CRONOS__MAINNET":                     1022,
		"CHAIN_METIS__MAINNET":                      1023,
		"CHAIN_OPBNB__MAINNET":                      1024,
		"CHAIN_KAVA__MAINNET":                       1025,
		"CHAIN_ASTAR__MAINNET":                      1026,
		"CHAIN_VARA__MAINNET":                       1027,
		"CHAIN_SOLANA__MAINNET":                     1028,
		"CHAIN_HAQQ__MAINNET":                       1029,
		"CHAIN_FILECOIN__MAINNET":                   1030,
		"CHAIN_FUSE__MAINNET":                       1031,
		"CHAIN_OKTC__MAINNET":                       1032,
		"CHAIN_MANTA_PACIFIC__MAINNET":              1033,
		"CHAIN_HARMONY__MAINNET_SHARD_0":            1034,
		"CHAIN_HARMONY__MAINNET_SHARD_1":            1035,
		"CHAIN_IMMUTABLE_ZKEVM__MAINNET":            1036,
		"CHAIN_ZORA__MAINNET":                       1037,
		"CHAIN_MODE__MAINNET":                       1038,
		"CHAIN_EVMOS__MAINNET":                      1039,
		"CHAIN_NEON_EVM__MAINNET":                   1040,
		"CHAIN_BOBA_ETHEREUM__MAINNET":              1041,
		"CHAIN_HECO__MAINNET":                       1042,
		"CHAIN_RONIN__MAINNET":                      1043,
		"CHAIN_BOBA_BNB__MAINNET":                   1044,
		"CHAIN_ZETA__MAINNET":                       1045,
		"CHAIN_BITTORRENT__MAINNET":                 1046,
		"CHAIN_THUNDERCORE__MAINNET":                1047,
		"CHAIN_CORE__MAINNET":                       1048,
		"CHAIN_TELOS__MAINNET":                      1049,
		"CHAIN_NEAR__MAINNET":                       1050,
		"CHAIN_BLAST__MAINNET":                      1051,
		"CHAIN_DYMENSION__MAINNET":                  1052,
		"CHAIN_ETHEREUM_BEACON__MAINNET":            1053,
		"CHAIN_PLAYNANCE__MAINNET":                  1054,
		"CHAIN_REAL__MAINNET":                       1055,
		"CHAIN_LISK__MAINNET":                       1056,
		"CHAIN_COSMOS_HUB_MAINNET":                  1057,
		"CHAIN_TAIKO_MAINNET":                       1058,
		"CHAIN_AXELAR_MAINNET":                      1059,
		"CHAIN_OSMOSIS_MAINNET":                     1060,
		"CHAIN_NEUTRON__MAINNET":                    1061,
		"CHAIN_ROOTSTOCK__MAINNET":                  1062,
		"CHAIN_ZIRCUIT__MAINNET":                    1063,
		"CHAIN_AVAIL__MAINNET":                      1064,
		"CHAIN_FRAXTAL__MAINNET":                    1065,
		"CHAIN_TRON_EVM__MAINNET":                   1066,
		"CHAIN_TRON_HTTP__MAINNET":                  1067,
		"CHAIN_KROMA__MAINNET":                      1068,
		"CHAIN_WEMIX__MAINNET":                      1069,
		"CHAIN_ALEPHZERO__MAINNET":                  1070,
		"CHAIN_POLKADOT__MAINNET":                   1071,
		"CHAIN_KUSAMA__MAINNET":                     1072,
		"CHAIN_METAL_L2__MAINNET":                   1073,
		"CHAIN_BOB__MAINNET":                        1074,
		"CHAIN_GOAT__MAINNET":                       1075,
		"CHAIN_EVERCLEAR__MAINNET":                  1076,
		"CHAIN_SNAXCHAIN__MAINNET":                  1077,
		"CHAIN_XLAYER__MAINNET":                     1078,
		"CHAIN_SEI__MAINNET":                        1079,
		"CHAIN_TON__MAINNET":                        1080,
		"CHAIN_UNICHAIN__MAINNET":                   1081,
		"CHAIN_APECHAIN__MAINNET":                   1082,
		"CHAIN_ZERO__MAINNET":                       1083,
		"CHAIN_WORLDCHAIN__MAINNET":                 1084,
		"CHAIN_CRONOS_ZKEVM__MAINNET":               1085,
		"CHAIN_VICTION__MAINNET":                    1086,
		"CHAIN_SONIC__MAINNET":                      1087,
		"CHAIN_SUPERSEED__MAINNET":                  1088,
		"CHAIN_INK__MAINNET":                        1089,
		"CHAIN_ABSTRACT__MAINNET":                   1090,
		"CHAIN_HASHKEY__MAINNET":                    1091,
		"CHAIN_GRAVITY_ALPHA__MAINNET":              1092,
		"CHAIN_MERLIN__MAINNET":                     1093,
		"CHAIN_PLUME__MAINNET":                      1094,
		"CHAIN_SONEIUM__MAINNET":                    1095,
		"CHAIN_DOGECOIN__MAINNET":                   1096,
		"CHAIN_LITECOIN__MAINNET":                   1097,
		"CHAIN_BITCOIN_CASH__MAINNET":               1098,
		"CHAIN_BERACHAIN__MAINNET":                  1099,
		"CHAIN_RIPPLE__MAINNET":                     1100,
		"CHAIN_SWELL__MAINNET":                      1101,
		"CHAIN_LENS__MAINNET":                       1102,
		"CHAIN_HYPERLIQUID__MAINNET":                1103,
		"CHAIN_KADENA__MAINNET":                     1104,
		"CHAIN_HEMI__MAINNET":                       1105,
		"CHAIN_GNOSIS_BEACON_CHAIN__MAINNET":        1106,
		"CHAIN_MONAD__MAINNET":                      1107,
		"CHAIN_SHIBARIUM__MAINNET":                  1108,
		"CHAIN_PLASMA__MAINNET":                     1109,
		"CHAIN_KATANA__MAINNET":                     1110,
		"CHAIN_DOMA__MAINNET":                       1111,
		"CHAIN_SOPHON__MAINNET":                     1112,
		"CHAIN_ARC__MAINNET":                        1113,
		"CHAIN_0G__MAINNET":                         1114,
		"CHAIN_SOMNIA__MAINNET":                     1115,
		"CHAIN_BITTENSOR__MAINNET":                  1116,
		"CHAIN_IOTEX__MAINNET":                      1117,
		"CHAIN_XRPL__MAINNET":                       1118,
		"CHAIN_MEZO__MAINNET":                       1119,
		"CHAIN_XDC__MAINNET":                        1120,
		"CHAIN_CREDITCOIN__MAINNET":                 1121,
		"CHAIN_FLARE__MAINNET":                      1122,
		"CHAIN_OASYS__MAINNET":                      1123,
		"CHAIN_SONGBIRD__MAINNET":                   1124,
		"CHAIN_STORY__MAINNET":                      1125,
		"CHAIN_VECHAIN__MAINNET":                    1126,
		"CHAIN_ZILLIQA2__MAINNET":                   1127,
		"CHAIN_BABYLON__MAINNET":                    1128,
		"CHAIN_AGORIC__MAINNET":                     1129,
		"CHAIN_COREUM__MAINNET":                     1130,
		"CHAIN_FETCH_AI__MAINNET":                   1131,
		"CHAIN_PROVENANCE__MAINNET":                 1132,
		"CHAIN_INITIA__MAINNET":                     1133,
		"CHAIN_INJECTIVE__MAINNET":                  1134,
		"CHAIN_MANTRA__MAINNET":                     1135,
		"CHAIN_BITCOIN_SV__MAINNET":                 1136,
		"CHAIN_DASH__MAINNET":                       1137,
		"CHAIN_DIGIBYTE__MAINNET":                   1138,
		"CHAIN_VERGE__MAINNET":                      1139,
		"CHAIN_ZCASH__MAINNET":                      1140,
		"CHAIN_POLYX__MAINNET":                      1141,
		"CHAIN_ZK_VERIFY__MAINNET":                  1142,
		"CHAIN_WESTEND__MAINNET":                    1143,
		"CHAIN_WESTEND_ASSETHUB__MAINNET":           1144,
		"CHAIN_PASEO__MAINNET":                      1145,
		"CHAIN_PASEO_ASSETHUB__MAINNET":             1146,
		"CHAIN_POLKADOT_ASSETHUB__MAINNET":          1147,
		"CHAIN_MEGAETH__MAINNET":                    1148,
		"CHAIN_TEMPO__MAINNET":                      1149,
		"CHAIN_AZTEC__MAINNET":                      1150,
		"CHAIN_MOCA__MAINNET":                       1151,
		"CHAIN_MORPH__MAINNET":                      1152,
		"CHAIN_TAC_MAINNET":                         1153,
		"CHAIN_TEA_MAINNET":                         1154,
		"CHAIN_ALGORAND__MAINNET":                   1155,
		"CHAIN_ORDERLY__MAINNET":                    1156,
		"CHAIN_ABCORE__MAINNET":                     1157,
		"CHAIN_BSQUARED__MAINNET":                   1158,
		"CHAIN_ADI__MAINNET":                        1159,
		"CHAIN_STABLE__MAINNET":                     1160,
		"CHAIN_JOVAY__MAINNET":                      1161,
		"CHAIN_PHAROS__MAINNET":                     1162,
		"CHAIN_EDGE__MAINNET":                       1163,
		"CHAIN_BOTANIX__MAINNET":                    1164,
		"CHAIN_ROBINHOOD__MAINNET":                  1165,
		"CHAIN_KITE__MAINNET":                       1166,
		"CHAIN_HUMANITY__MAINNET":                   1167,
		"CHAIN_APTOS__MAINNET":                      1168,
		"CHAIN_BITLAYER__MAINNET":                   1169,
		"CHAIN_MOVA__MAINNET":                       1170,
		"CHAIN_ETHERLINK__MAINNET":                  1171,
		"CHAIN_NEO_X__MAINNET":                      1172,
		"CHAIN_MOVA__MAINNET_V2":                    1173,
		"CHAIN_STELLAR__MAINNET":                    1174,
		"CHAIN_CELESTIA__MAINNET":                   1175,
		"CHAIN_SUI__MAINNET":                        1176,
		"CHAIN_ETHEREUM__MORDEN":                    10001,
		"CHAIN_ETHEREUM__KOVAN":                     10002,
		"CHAIN_BITCOIN__TESTNET":                    10003,
		"CHAIN_ETHEREUM__ROPSTEN":                   10006,
		"CHAIN_ETHEREUM__RINKEBY":                   10007,
		"CHAIN_ETHEREUM__SEPOLIA":                   10008,
		"CHAIN_FANTOM__TESTNET":                     10016,
		"CHAIN_GNOSIS__CHIADO":                      10017,
		"CHAIN_AVALANCHE__FUJI":                     10018,
		"CHAIN_AURORA__TESTNET":                     10021,
		"CHAIN_KLAYTN__BAOBAB":                      10024,
		"CHAIN_SCROLL__SEPOLIA":                     10025,
		"CHAIN_BSC__TESTNET":                        10026,
		"CHAIN_ETHEREUM__HOLESKY":                   10027,
		"CHAIN_CELO__ALFAJORES":                     10028,
		"CHAIN_MOONBEAM__ALPHA":                     10029,
		"CHAIN_CRONOS__TESTNET":                     10030,
		"CHAIN_OPBNB__TESTNET":                      10032,
		"CHAIN_KAVA__TESTNET":                       10033,
		"CHAIN_IMMUTABLE_ZKEVM__TESTNET":            10034,
		"CHAIN_VARA__TESTNET":                       10036,
		"CHAIN_SOLANA__TESTNET":                     10037,
		"CHAIN_OPTIMISM__SEPOLIA":                   10038,
		"CHAIN_SOLANA__DEVNET":                      10039,
		"CHAIN_BASE__SEPOLIA":                       10040,
		"CHAIN_HAQQ__TESTNET":                       10041,
		"CHAIN_FILECOIN__CALIBRATION":               10042,
		"CHAIN_OKTC__TESTNET":                       10044,
		"CHAIN_ZKSYNC__SEPOLIA":                     10046,
		"CHAIN_BERACHAIN__ARTIO":                    10047,
		"CHAIN_POLYGON__AMOY":                       10048,
		"CHAIN_BLAST__SEPOLIA":                      10049,
		"CHAIN_LISK__TESTNET":                       10050,
		"CHAIN_ARBITRUM__SEPOLIA":                   10051,
		"CHAIN_ZORA__SEPOLIA":                       10053,
		"CHAIN_MODE__TESTNET":                       10054,
		"CHAIN_EVMOS__TESTNET":                      10055,
		"CHAIN_NEON_EVM__DEVNET":                    10056,
		"CHAIN_HECO__TESTNET":                       10057,
		"CHAIN_METIS__SEPOLIA":                      10058,
		"CHAIN_PLAYNANCE__TESTNET":                  10059,
		"CHAIN_BITTORRENT__TESTNET":                 10060,
		"CHAIN_THUNDERCORE__TESTNET":                10061,
		"CHAIN_CORE__TESTNET":                       10062,
		"CHAIN_TELOS__TESTNET":                      10063,
		"CHAIN_NEAR__TESTNET":                       10064,
		"CHAIN_NEAR__BETANET":                       10065,
		"CHAIN_MANTLE__SEPOLIA":                     10066,
		"CHAIN_OP_CELESTIA_RASPBERRY__TESTNET":      10067,
		"CHAIN_ARBITRUM_BLUEBERRY__TESTNET":         10068,
		"CHAIN_ETHEREUM_BEACON__SEPOLIA":            10070,
		"CHAIN_ETHEREUM_BEACON__HOLESKY":            10071,
		"CHAIN_POLYGON_BLACKBERRY__TESTNET":         10072,
		"CHAIN_POLYGON_ZKEVM_CARDONA_TESTNET":       10073,
		"CHAIN_LINEA__SEPOLIA":                      10074,
		"CHAIN_STARKNET__SEPOLIA":                   10075,
		"CHAIN_MANTA_PACIFIC__SEPOLIA":              10076,
		"CHAIN_EVERCLEAR__SEPOLIA":                  10077,
		"CHAIN_ALEPHZERO__SEPOLIA":                  10078,
		"CHAIN_COSMOS_HUB__TESTNET":                 10079,
		"CHAIN_TAIKO_HEKLA__TESTNET":                10080,
		"CHAIN_AXELAR__TESTNET":                     10081,
		"CHAIN_OSMOSIS__TESTNET":                    10082,
		"CHAIN_NEUTRON__TESTNET":                    10083,
		"CHAIN_ROOTSTOCK__TESTNET":                  10084,
		"CHAIN_OPEN_CAMPUS_CODEX__SEPOLIA":          10085,
		"CHAIN_GAMESWIFT__TESTNET":                  10086,
		"CHAIN_ZETA__TESTNET":                       10087,
		"CHAIN_ZIRCUIT__TESTNET":                    10088,
		"CHAIN_AVAIL__TURING_TESTNET":               10089,
		"CHAIN_FRAXTAL___TESTNET":                   10090,
		"CHAIN_TRON_EVM__SHASTA":                    10091,
		"CHAIN_TRON_HTTP__SHASTA":                   10092,
		"CHAIN_KROMA__SEPOLIA":                      10093,
		"CHAIN_WEMIX__TESTNET":                      10094,
		"CHAIN_METAL_L2__TESTNET":                   10095,
		"CHAIN_BOB__TESTNET":                        10096,
		"CHAIN_SNAXCHAIN__TESTNET":                  10098,
		"CHAIN_XLAYER__TESTNET":                     10099,
		"CHAIN_SEI__TESTNET":                        10100,
		"CHAIN_SEI__DEVNET":                         10101,
		"CHAIN_RONIN__SAIGON":                       10102,
		"CHAIN_SONIC__TESTNET":                      10103,
		"CHAIN_LENS__TESTNET":                       10104,
		"CHAIN_UNICHAIN__SEPOLIA":                   10105,
		"CHAIN_APECHAIN__SEPOLIA":                   10106,
		"CHAIN_SONEIUM__TESTNET":                    10107,
		"CHAIN_TON__TESTNET":                        10108,
		"CHAIN_GOAT__TESTNET3":                      10109,
		"CHAIN_WORLDCHAIN__SEPOLIA":                 10110,
		"CHAIN_CRONOS_ZKEVM__TESTNET":               10111,
		"CHAIN_VICTION__TESTNET":                    10112,
		"CHAIN_0G_NEWTON__TESTNET":                  10113,
		"CHAIN_SUPERSEED__SEPOLIA":                  10114,
		"CHAIN_INK__SEPOLIA":                        10115,
		"CHAIN_ABSTRACT__SEPOLIA":                   10116,
		"CHAIN_HASHKEY__TESTNET":                    10117,
		"CHAIN_GRAVITY_ALPHA__SEPOLIA":              10118,
		"CHAIN_HYPERLIQUID__TESTNET":                10119,
		"CHAIN_MERLIN__TESTNET":                     10120,
		"CHAIN_MEZO__TESTNET":                       10121,
		"CHAIN_PLUME__DEVNET":                       10122,
		"CHAIN_PLUME__TESTNET":                      10123,
		"CHAIN_MONAD__TESTNET":                      10124,
		"CHAIN_DOGECOIN__TESTNET":                   10125,
		"CHAIN_LITECOIN__TESTNET":                   10126,
		"CHAIN_BITCOIN_CASH__TESTNET":               10127,
		"CHAIN_RIPPLE__TESTNET":                     10128,
		"CHAIN_SWELL__TESTNET":                      10129,
		"CHAIN_ZIRCUIT__GARFIELD":                   10130,
		"CHAIN_ETHEREUM__HOODI":                     10131,
		"CHAIN_ETHEREUM_BEACON__HOODI":              10132,
		"CHAIN_BERACHAIN__BEPOLIA":                  10133,
		"CHAIN_KADENA__TESTNET":                     10134,
		"CHAIN_OZEAN__TESTNET":                      10135,
		"CHAIN_0G_GALILEO__TESTNET":                 10136,
		"CHAIN_MEGAETH__TESTNET":                    10137,
		"CHAIN_HEMI__TESTNET":                       10138,
		"CHAIN_CELO__SEPOLIA":                       10139,
		"CHAIN_SONIC__TESTNET_V2":                   10140,
		"CHAIN_GNOSIS_CHIADO_BEACON_CHAIN__TESTNET": 10141,
		"CHAIN_PLASMA__TESTNET":                     10142,
		"CHAIN_KATANA__TESTNET":                     10143,
		"CHAIN_TAIKO__HOODI":                        10144,
		"CHAIN_DOMA__TESTNET":                       10145,
		"CHAIN_SOPHON__TESTNET":                     10146,
		"CHAIN_ARC__TESTNET":                        10147,
		"CHAIN_SOMNIA__TESTNET":                     10148,
		"CHAIN_BITTENSOR__TESTNET":                  10149,
		"CHAIN_DOGEOS__TESTNET":                     10150,
		"CHAIN_IOTEX__TESTNET":                      10151,
		"CHAIN_XRPL__TESTNET":                       10152,
		"CHAIN_XRPL__DEVNET":                        10153,
		"CHAIN_TEMPO__TESTNET":                      10154,
		"CHAIN_XDC__TESTNET":                        10155,
		"CHAIN_CREDITCOIN__TESTNET":                 10156,
		"CHAIN_CREDITCOIN__DEVNET":                  10157,
		"CHAIN_FLARE__TESTNET":                      10158,
		"CHAIN_OASYS__TESTNET":                      10159,
		"CHAIN_SONGBIRD__TESTNET":                   10160,
		"CHAIN_STORY__TESTNET":                      10161,
		"CHAIN_STORY_AENEID__TESTNET":               10162,
		"CHAIN_VECHAIN__TESTNET":                    10163,
		"CHAIN_ZILLIQA2__TESTNET":                   10164,
		"CHAIN_ZILLIQA2__DEVNET":                    10165,
		"CHAIN_BABYLON__TESTNET":                    10166,
		"CHAIN_COREUM__TESTNET":                     10167,
		"CHAIN_FETCH_AI__TESTNET":                   10168,
		"CHAIN_PROVENANCE__TESTNET":                 10169,
		"CHAIN_INITIA__TESTNET":                     10170,
		"CHAIN_INJECTIVE__TESTNET":                  10171,
		"CHAIN_MANTRA__TESTNET":                     10172,
		"CHAIN_BITCOIN_SV__TESTNET":                 10173,
		"CHAIN_DASH__TESTNET":                       10174,
		"CHAIN_DIGIBYTE__TESTNET":                   10175,
		"CHAIN_VERGE__TESTNET":                      10176,
		"CHAIN_ZCASH__TESTNET":                      10177,
		"CHAIN_POLYX__TESTNET":                      10178,
		"CHAIN_ZK_VERIFY__TESTNET":                  10183,
		"CHAIN_TEMPO_MODERATO__TESTNET":             10184,
		"CHAIN_MEGAETH__TESTNET_V2":                 10185,
		"CHAIN_AZTEC__TESTNET":                      10186,
		"CHAIN_AZTEC__DEVNET":                       10187,
		"CHAIN_MOCA__TESTNET":                       10188,
		"CHAIN_MORPH__TESTNET":                      10189,
		"CHAIN_ROBINHOOD__TESTNET":                  10190,
		"CHAIN_TACSPB__TESTNET":                     10191,
		"CHAIN_TEA__SEPOLIA":                        10192,
		"CHAIN_ALGORAND__TESTNET":                   10193,
		"CHAIN_ALGORAND__BETANET":                   10194,
		"CHAIN_ORDERLY__TESTNET":                    10195,
		"CHAIN_STABLE__TESTNET":                     10196,
		"CHAIN_JOVAY__SEPOLIA":                      10197,
		"CHAIN_PHAROS__TESTNET":                     10198,
		"CHAIN_PHAROS_ATLANTIC__TESTNET":            10199,
		"CHAIN_EDGE__TESTNET":                       10200,
		"CHAIN_BOTANIX__TESTNET":                    10201,
		"CHAIN_HUMANITY__TESTNET":                   10202,
		"CHAIN_APTOS__TESTNET":                      10203,
		"CHAIN_BITLAYER__TESTNET":                   10204,
		"CHAIN_MOVA__TESTNET":                       10205,
		"CHAIN_ETHERLINK__SHADOWNET":                10206,
		"CHAIN_NEO_X__TESTNET":                      10207,
		"CHAIN_STELLAR__TESTNET":                    10208,
		"CHAIN_CELESTIA__MOCHA":                     10209,
		"CHAIN_SUI__TESTNET":                        10210,
		"CHAIN_SUI__DEVNET":                         10211,
		"CHAIN_LAMBDA__VIRTUAL":                     100000,
	}
)

func (x ChainRef) Enum() *ChainRef {
	p := new(ChainRef)
	*p = x
	return p
}

func (x ChainRef) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChainRef) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (ChainRef) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x ChainRef) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChainRef.Descriptor instead.
func (ChainRef) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type AvailabilityEnum int32

const (
	AvailabilityEnum_AVAIL_UNKNOWN     AvailabilityEnum = 0
	AvailabilityEnum_AVAIL_OK          AvailabilityEnum = 1
	AvailabilityEnum_AVAIL_LAGGING     AvailabilityEnum = 2
	AvailabilityEnum_AVAIL_IMMATURE    AvailabilityEnum = 3
	AvailabilityEnum_AVAIL_SYNCING     AvailabilityEnum = 4
	AvailabilityEnum_AVAIL_UNAVAILABLE AvailabilityEnum = 5
	AvailabilityEnum_AVAIL_FORKED      AvailabilityEnum = 6
)

// Enum value maps for AvailabilityEnum.
var (
	AvailabilityEnum_name = map[int32]string{
		0: "AVAIL_UNKNOWN",
		1: "AVAIL_OK",
		2: "AVAIL_LAGGING",
		3: "AVAIL_IMMATURE",
		4: "AVAIL_SYNCING",
		5: "AVAIL_UNAVAILABLE",
		6: "AVAIL_FORKED",
	}
	AvailabilityEnum_value = map[string]int32{
		"AVAIL_UNKNOWN":     0,
		"AVAIL_OK":          1,
		"AVAIL_LAGGING":     2,
		"AVAIL_IMMATURE":    3,
		"AVAIL_SYNCING":     4,
		"AVAIL_UNAVAILABLE": 5,
		"AVAIL_FORKED":      6,
	}
)

func (x AvailabilityEnum) Enum() *AvailabilityEnum {
	p := new(AvailabilityEnum)
	*p = x
	return p
}

func (x AvailabilityEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AvailabilityEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (AvailabilityEnum) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x AvailabilityEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AvailabilityEnum.Descriptor instead.
func (AvailabilityEnum) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

type FinalizationType int32

const (
	FinalizationType_FINALIZATION_UNSPECIFIED     FinalizationType = 0
	FinalizationType_FINALIZATION_SAFE_BLOCK      FinalizationType = 1
	FinalizationType_FINALIZATION_FINALIZED_BLOCK FinalizationType = 2
)

// Enum value maps for FinalizationType.
var (
	FinalizationType_name = map[int32]string{
		0: "FINALIZATION_UNSPECIFIED",
		1: "FINALIZATION_SAFE_BLOCK",
		2: "FINALIZATION_FINALIZED_BLOCK",
	}
	FinalizationType_value = map[string]int32{
		"FINALIZATION_UNSPECIFIED":     0,
		"FINALIZATION_SAFE_BLOCK":      1,
		"FINALIZATION_FINALIZED_BLOCK": 2,
	}
)

func (x FinalizationType) Enum() *FinalizationType {
	p := new(FinalizationType)
	*p = x
	return p
}

func (x FinalizationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FinalizationType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (FinalizationType) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x FinalizationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FinalizationType.Descriptor instead.
func (FinalizationType) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

type Chain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ChainRef               `protobuf:"varint,1,opt,name=type,proto3,enum=emerald.ChainRef" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chain) Reset() {
	*x = Chain{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chain) ProtoMessage() {}

func (x *Chain) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chain.ProtoReflect.Descriptor instead.
func (*Chain) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *Chain) GetType() ChainRef {
	if x != nil {
		return x.Type
	}
	return ChainRef_CHAIN_UNSPECIFIED
}

type SingleAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SingleAddress) Reset() {
	*x = SingleAddress{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SingleAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SingleAddress) ProtoMessage() {}

func (x *SingleAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SingleAddress.ProtoReflect.Descriptor instead.
func (*SingleAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *SingleAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type XpubAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// base58 encoded string for xpub, https://en.bitcoin.it/wiki/BIP_0032#Serialization_format
	Xpub          string `protobuf:"bytes,1,opt,name=xpub,proto3" json:"xpub,omitempty"`
	Start         uint64 `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	Limit         uint64 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	UnusedLimit   uint64 `protobuf:"varint,5,opt,name=unused_limit,json=unusedLimit,proto3" json:"unused_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *XpubAddress) Reset() {
	*x = XpubAddress{}
	mi := &file_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *XpubAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*XpubAddress) ProtoMessage() {}

func (x *XpubAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use XpubAddress.ProtoReflect.Descriptor instead.
func (*XpubAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

func (x *XpubAddress) GetXpub() string {
	if x != nil {
		return x.Xpub
	}
	return ""
}

func (x *XpubAddress) GetStart() uint64 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *XpubAddress) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *XpubAddress) GetUnusedLimit() uint64 {
	if x != nil {
		return x.UnusedLimit
	}
	return 0
}

type MultiAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addresses     []*SingleAddress       `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultiAddress) Reset() {
	*x = MultiAddress{}
	mi := &file_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultiAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiAddress) ProtoMessage() {}

func (x *MultiAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiAddress.ProtoReflect.Descriptor instead.
func (*MultiAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{3}
}

func (x *MultiAddress) GetAddresses() []*SingleAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ReferenceAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Refid         uint64                 `protobuf:"varint,1,opt,name=refid,proto3" json:"refid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceAddress) Reset() {
	*x = ReferenceAddress{}
	mi := &file_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceAddress) ProtoMessage() {}

func (x *ReferenceAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceAddress.ProtoReflect.Descriptor instead.
func (*ReferenceAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{4}
}

func (x *ReferenceAddress) GetRefid() uint64 {
	if x != nil {
		return x.Refid
	}
	return 0
}

type AnyAddress struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to AddrType:
	//
	//	*AnyAddress_AddressSingle
	//	*AnyAddress_AddressMulti
	//	*AnyAddress_AddressXpub
	//	*AnyAddress_AddressRef
	AddrType      isAnyAddress_AddrType `protobuf_oneof:"addr_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyAddress) Reset() {
	*x = AnyAddress{}
	mi := &file_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyAddress) ProtoMessage() {}

func (x *AnyAddress) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyAddress.ProtoReflect.Descriptor instead.
func (*AnyAddress) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{5}
}

func (x *AnyAddress) GetAddrType() isAnyAddress_AddrType {
	if x != nil {
		return x.AddrType
	}
	return nil
}

func (x *AnyAddress) GetAddressSingle() *SingleAddress {
	if x != nil {
		if x, ok := x.AddrType.(*AnyAddress_AddressSingle); ok {
			return x.AddressSingle
		}
	}
	return nil
}

func (x *AnyAddress) GetAddressMulti() *MultiAddress {
	if x != nil {
		if x, ok := x.AddrType.(*AnyAddress_AddressMulti); ok {
			return x.AddressMulti
		}
	}
	return nil
}

func (x *AnyAddress) GetAddressXpub() *XpubAddress {
	if x != nil {
		if x, ok := x.AddrType.(*AnyAddress_AddressXpub); ok {
			return x.AddressXpub
		}
	}
	return nil
}

func (x *AnyAddress) GetAddressRef() *ReferenceAddress {
	if x != nil {
		if x, ok := x.AddrType.(*AnyAddress_AddressRef); ok {
			return x.AddressRef
		}
	}
	return nil
}

type isAnyAddress_AddrType interface {
	isAnyAddress_AddrType()
}

type AnyAddress_AddressSingle struct {
	AddressSingle *SingleAddress `protobuf:"bytes,1,opt,name=address_single,json=addressSingle,proto3,oneof"`
}

type AnyAddress_AddressMulti struct {
	AddressMulti *MultiAddress `protobuf:"bytes,2,opt,name=address_multi,json=addressMulti,proto3,oneof"`
}

type AnyAddress_AddressXpub struct {
	AddressXpub *XpubAddress `protobuf:"bytes,3,opt,name=address_xpub,json=addressXpub,proto3,oneof"`
}

type AnyAddress_AddressRef struct {
	AddressRef *ReferenceAddress `protobuf:"bytes,4,opt,name=address_ref,json=addressRef,proto3,oneof"`
}

func (*AnyAddress_AddressSingle) isAnyAddress_AddrType() {}

func (*AnyAddress_AddressMulti) isAnyAddress_AddrType() {}

func (*AnyAddress_AddressXpub) isAnyAddress_AddrType() {}

func (*AnyAddress_AddressRef) isAnyAddress_AddrType() {}

type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         ChainRef               `protobuf:"varint,1,opt,name=chain,proto3,enum=emerald.ChainRef" json:"chain,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{6}
}

func (x *Asset) GetChain() ChainRef {
	if x != nil {
		return x.Chain
	}
	return ChainRef_CHAIN_UNSPECIFIED
}

func (x *Asset) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type BlockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	BlockId       string                 `protobuf:"bytes,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockInfo) Reset() {
	*x = BlockInfo{}
	mi := &file_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockInfo) ProtoMessage() {}

func (x *BlockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockInfo.ProtoReflect.Descriptor instead.
func (*BlockInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{7}
}

func (x *BlockInfo) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockInfo) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *BlockInfo) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type FinalizationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Height        uint64                 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Type          FinalizationType       `protobuf:"varint,2,opt,name=type,proto3,enum=emerald.FinalizationType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizationData) Reset() {
	*x = FinalizationData{}
	mi := &file_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizationData) ProtoMessage() {}

func (x *FinalizationData) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizationData.ProtoReflect.Descriptor instead.
func (*FinalizationData) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizationData) GetHeight() uint64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *FinalizationData) GetType() FinalizationType {
	if x != nil {
		return x.Type
	}
	return FinalizationType_FINALIZATION_UNSPECIFIED
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\aemerald\".\n" +
	"\x05Chain\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.emerald.ChainRefR\x04type\")\n" +
	"\rSingleAddress\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\"p\n" +
	"\vXpubAddress\x12\x12\n" +
	"\x04xpub\x18\x01 \x01(\tR\x04xpub\x12\x14\n" +
	"\x05start\x18\x03 \x01(\x04R\x05start\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x04R\x05limit\x12!\n" +
	"\funused_limit\x18\x05 \x01(\x04R\vunusedLimit\"D\n" +
	"\fMultiAddress\x124\n" +
	"\taddresses\x18\x01 \x03(\v2\x16.emerald.SingleAddressR\taddresses\"(\n" +
	"\x10ReferenceAddress\x12\x14\n" +
	"\x05refid\x18\x01 \x01(\x04R\x05refid\"\x91\x02\n" +
	"\n" +
	"AnyAddress\x12?\n" +
	"\x0eaddress_single\x18\x01 \x01(\v2\x16.emerald.SingleAddressH\x00R\raddressSingle\x12<\n" +
	"\raddress_multi\x18\x02 \x01(\v2\x15.emerald.MultiAddressH\x00R\faddressMulti\x129\n" +
	"\faddress_xpub\x18\x03 \x01(\v2\x14.emerald.XpubAddressH\x00R\vaddressXpub\x12<\n" +
	"\vaddress_ref\x18\x04 \x01(\v2\x19.emerald.ReferenceAddressH\x00R\n" +
	"addressRefB\v\n" +
	"\taddr_type\"D\n" +
	"\x05Asset\x12'\n" +
	"\x05chain\x18\x01 \x01(\x0e2\x11.emerald.ChainRefR\x05chain\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\"\\\n" +
	"\tBlockInfo\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\tR\ablockId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\"Y\n" +
	"\x10FinalizationData\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x04R\x06height\x12-\n" +
	"\x04type\x18\x02 \x01(\x0e2\x19.emerald.FinalizationTypeR\x04type*\xeaT\n" +
	"\bChainRef\x12\x15\n" +
	"\x11CHAIN_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CHAIN_BITCOIN__MAINNET\x10\x01\x12\x1b\n" +
	"\x17CHAIN_ETHEREUM__MAINNET\x10d\x12#\n" +
	"\x1fCHAIN_ETHEREUM_CLASSIC__MAINNET\x10e\x12\x19\n" +
	"\x15CHAIN_FANTOM__MAINNET\x10f\x12\x1f\n" +
	"\x1aCHAIN_POLYGON_POS__MAINNET\x10\xea\a\x12\x17\n" +
	"\x12CHAIN_RSK__MAINNET\x10\xeb\a\x12\x1c\n" +
	"\x17CHAIN_ARBITRUM__MAINNET\x10\xec\a\x12\x1c\n" +
	"\x17CHAIN_OPTIMISM__MAINNET\x10\xed\a\x12\x17\n" +
	"\x12CHAIN_BSC__MAINNET\x10\xee\a\x12!\n" +
	"\x1cCHAIN_POLYGON_ZKEVM__MAINNET\x10\xef\a\x12!\n" +
	"\x1cCHAIN_ARBITRUM_NOVA__MAINNET\x10\xf0\a\x12\x1a\n" +
	"\x15CHAIN_ZKSYNC__MAINNET\x10\xf1\a\x12\x18\n" +
	"\x13CHAIN_BASE__MAINNET\x10\xf2\a\x12\x19\n" +
	"\x14CHAIN_LINEA__MAINNET\x10\xf3\a\x12\x1a\n" +
	"\x15CHAIN_GNOSIS__MAINNET\x10\xf4\a\x12\x1d\n" +
	"\x18CHAIN_AVALANCHE__MAINNET\x10\xf5\a\x12\x1c\n" +
	"\x17CHAIN_STARKNET__MAINNET\x10\xf6\a\x12\x1a\n" +
	"\x15CHAIN_AURORA__MAINNET\x10\xf7\a\x12\x1a\n" +
	"\x15CHAIN_SCROLL__MAINNET\x10\xf8\a\x12\x1a\n" +
	"\x15CHAIN_MANTLE__MAINNET\x10\xf9\a\x12\x1a\n" +
	"\x15CHAIN_KLAYTN__MAINNET\x10\xfa\a\x12\x18\n" +
	"\x13CHAIN_CELO__MAINNET\x10\xfb\a\x12\x1c\n" +
	"\x17CHAIN_MOONBEAM__MAINNET\x10\xfc\a\x12\x1e\n" +
	"\x19CHAIN_MOONBEAM__MOONRIVER\x10\xfd\a\x12\x1a\n" +
	"\x15CHAIN_CRONOS__MAINNET\x10\xfe\a\x12\x19\n" +
	"\x14CHAIN_METIS__MAINNET\x10\xff\a\x12\x19\n" +
	"\x14CHAIN_OPBNB__MAINNET\x10\x80\b\x12\x18\n" +
	"\x13CHAIN_KAVA__MAINNET\x10\x81\b\x12\x19\n" +
	"\x14CHAIN_ASTAR__MAINNET\x10\x82\b\x12\x18\n" +
	"\x13CHAIN_VARA__MAINNET\x10\x83\b\x12\x1a\n" +
	"\x15CHAIN_SOLANA__MAINNET\x10\x84\b\x12\x18\n" +
	"\x13CHAIN_HAQQ__MAINNET\x10\x85\b\x12\x1c\n" +
	"\x17CHAIN_FILECOIN__MAINNET\x10\x86\b\x12\x18\n" +
	"\x13CHAIN_FUSE__MAINNET\x10\x87\b\x12\x18\n" +
	"\x13CHAIN_OKTC__MAINNET\x10\x88\b\x12!\n" +
	"\x1cCHAIN_MANTA_PACIFIC__MAINNET\x10\x89\b\x12#\n" +
	"\x1eCHAIN_HARMONY__MAINNET_SHARD_0\x10\x8a\b\x12#\n" +
	"\x1eCHAIN_HARMONY__MAINNET_SHARD_1\x10\x8b\b\x12#\n" +
	"\x1eCHAIN_IMMUTABLE_ZKEVM__MAINNET\x10\x8c\b\x12\x18\n" +
	"\x13CHAIN_ZORA__MAINNET\x10\x8d\b\x12\x18\n" +
	"\x13CHAIN_MODE__MAINNET\x10\x8e\b\x12\x19\n" +
	"\x14CHAIN_EVMOS__MAINNET\x10\x8f\b\x12\x1c\n" +
	"\x17CHAIN_NEON_EVM__MAINNET\x10\x90\b\x12!\n" +
	"\x1cCHAIN_BOBA_ETHEREUM__MAINNET\x10\x91\b\x12\x18\n" +
	"\x13CHAIN_HECO__MAINNET\x10\x92\b\x12\x19\n" +
	"\x14CHAIN_RONIN__MAINNET\x10\x93\b\x12\x1c\n" +
	"\x17CHAIN_BOBA_BNB__MAINNET\x10\x94\b\x12\x18\n" +
	"\x13CHAIN_ZETA__MAINNET\x10\x95\b\x12\x1e\n" +
	"\x19CHAIN_BITTORRENT__MAINNET\x10\x96\b\x12\x1f\n" +
	"\x1aCHAIN_THUNDERCORE__MAINNET\x10\x97\b\x12\x18\n" +
	"\x13CHAIN_CORE__MAINNET\x10\x98\b\x12\x19\n" +
	"\x14CHAIN_TELOS__MAINNET\x10\x99\b\x12\x18\n" +
	"\x13CHAIN_NEAR__MAINNET\x10\x9a\b\x12\x19\n" +
	"\x14CHAIN_BLAST__MAINNET\x10\x9b\b\x12\x1d\n" +
	"\x18CHAIN_DYMENSION__MAINNET\x10\x9c\b\x12#\n" +
	"\x1eCHAIN_ETHEREUM_BEACON__MAINNET\x10\x9d\b\x12\x1d\n" +
	"\x18CHAIN_PLAYNANCE__MAINNET\x10\x9e\b\x12\x18\n" +
	"\x13CHAIN_REAL__MAINNET\x10\x9f\b\x12\x18\n" +
	"\x13CHAIN_LISK__MAINNET\x10\xa0\b\x12\x1d\n" +
	"\x18CHAIN_COSMOS_HUB_MAINNET\x10\xa1\b\x12\x18\n" +
	"\x13CHAIN_TAIKO_MAINNET\x10\xa2\b\x12\x19\n" +
	"\x14CHAIN_AXELAR_MAINNET\x10\xa3\b\x12\x1a\n" +
	"\x15CHAIN_OSMOSIS_MAINNET\x10\xa4\b\x12\x1b\n" +
	"\x16CHAIN_NEUTRON__MAINNET\x10\xa5\b\x12\x1d\n" +
	"\x18CHAIN_ROOTSTOCK__MAINNET\x10\xa6\b\x12\x1b\n" +
	"\x16CHAIN_ZIRCUIT__MAINNET\x10\xa7\b\x12\x19\n" +
	"\x14CHAIN_AVAIL__MAINNET\x10\xa8\b\x12\x1b\n" +
	"\x16CHAIN_FRAXTAL__MAINNET\x10\xa9\b\x12\x1c\n" +
	"\x17CHAIN_TRON_EVM__MAINNET\x10\xaa\b\x12\x1d\n" +
	"\x18CHAIN_TRON_HTTP__MAINNET\x10\xab\b\x12\x19\n" +
	"\x14CHAIN_KROMA__MAINNET\x10\xac\b\x12\x19\n" +
	"\x14CHAIN_WEMIX__MAINNET\x10\xad\b\x12\x1d\n" +
	"\x18CHAIN_ALEPHZERO__MAINNET\x10\xae\b\x12\x1c\n" +
	"\x17CHAIN_POLKADOT__MAINNET\x10\xaf\b\x12\x1a\n" +
	"\x15CHAIN_KUSAMA__MAINNET\x10\xb0\b\x12\x1c\n" +
	"\x17CHAIN_METAL_L2__MAINNET\x10\xb1\b\x12\x17\n" +
	"\x12CHAIN_BOB__MAINNET\x10\xb2\b\x12\x18\n" +
	"\x13CHAIN_GOAT__MAINNET\x10\xb3\b\x12\x1d\n" +
	"\x18CHAIN_EVERCLEAR__MAINNET\x10\xb4\b\x12\x1d\n" +
	"\x18CHAIN_SNAXCHAIN__MAINNET\x10\xb5\b\x12\x1a\n" +
	"\x15CHAIN_XLAYER__MAINNET\x10\xb6\b\x12\x17\n" +
	"\x12CHAIN_SEI__MAINNET\x10\xb7\b\x12\x17\n" +
	"\x12CHAIN_TON__MAINNET\x10\xb8\b\x12\x1c\n" +
	"\x17CHAIN_UNICHAIN__MAINNET\x10\xb9\b\x12\x1c\n" +
	"\x17CHAIN_APECHAIN__MAINNET\x10\xba\b\x12\x18\n" +
	"\x13CHAIN_ZERO__MAINNET\x10\xbb\b\x12\x1e\n" +
	"\x19CHAIN_WORLDCHAIN__MAINNET\x10\xbc\b\x12 \n" +
	"\x1bCHAIN_CRONOS_ZKEVM__MAINNET\x10\xbd\b\x12\x1b\n" +
	"\x16CHAIN_VICTION__MAINNET\x10\xbe\b\x12\x19\n" +
	"\x14CHAIN_SONIC__MAINNET\x10\xbf\b\x12\x1d\n" +
	"\x18CHAIN_SUPERSEED__MAINNET\x10\xc0\b\x12\x17\n" +
	"\x12CHAIN_INK__MAINNET\x10\xc1\b\x12\x1c\n" +
	"\x17CHAIN_ABSTRACT__MAINNET\x10\xc2\b\x12\x1b\n" +
	"\x16CHAIN_HASHKEY__MAINNET\x10\xc3\b\x12!\n" +
	"\x1cCHAIN_GRAVITY_ALPHA__MAINNET\x10\xc4\b\x12\x1a\n" +
	"\x15CHAIN_MERLIN__MAINNET\x10\xc5\b\x12\x19\n" +
	"\x14CHAIN_PLUME__MAINNET\x10\xc6\b\x12\x1b\n" +
	"\x16CHAIN_SONEIUM__MAINNET\x10\xc7\b\x12\x1c\n" +
	"\x17CHAIN_DOGECOIN__MAINNET\x10\xc8\b\x12\x1c\n" +
	"\x17CHAIN_LITECOIN__MAINNET\x10\xc9\b\x12 \n" +
	"\x1bCHAIN_BITCOIN_CASH__MAINNET\x10\xca\b\x12\x1d\n" +
	"\x18CHAIN_BERACHAIN__MAINNET\x10\xcb\b\x12\x1a\n" +
	"\x15CHAIN_RIPPLE__MAINNET\x10\xcc\b\x12\x19\n" +
	"\x14CHAIN_SWELL__MAINNET\x10\xcd\b\x12\x18\n" +
	"\x13CHAIN_LENS__MAINNET\x10\xce\b\x12\x1f\n" +
	"\x1aCHAIN_HYPERLIQUID__MAINNET\x10\xcf\b\x12\x1a\n" +
	"\x15CHAIN_KADENA__MAINNET\x10\xd0\b\x12\x18\n" +
	"\x13CHAIN_HEMI__MAINNET\x10\xd1\b\x12'\n" +
	"\"CHAIN_GNOSIS_BEACON_CHAIN__MAINNET\x10\xd2\b\x12\x19\n" +
	"\x14CHAIN_MONAD__MAINNET\x10\xd3\b\x12\x1d\n" +
	"\x18CHAIN_SHIBARIUM__MAINNET\x10\xd4\b\x12\x1a\n" +
	"\x15CHAIN_PLASMA__MAINNET\x10\xd5\b\x12\x1a\n" +
	"\x15CHAIN_KATANA__MAINNET\x10\xd6\b\x12\x18\n" +
	"\x13CHAIN_DOMA__MAINNET\x10\xd7\b\x12\x1a\n" +
	"\x15CHAIN_SOPHON__MAINNET\x10\xd8\b\x12\x17\n" +
	"\x12CHAIN_ARC__MAINNET\x10\xd9\b\x12\x16\n" +
	"\x11CHAIN_0G__MAINNET\x10\xda\b\x12\x1a\n" +
	"\x15CHAIN_SOMNIA__MAINNET\x10\xdb\b\x12\x1d\n" +
	"\x18CHAIN_BITTENSOR__MAINNET\x10\xdc\b\x12\x19\n" +
	"\x14CHAIN_IOTEX__MAINNET\x10\xdd\b\x12\x18\n" +
	"\x13CHAIN_XRPL__MAINNET\x10\xde\b\x12\x18\n" +
	"\x13CHAIN_MEZO__MAINNET\x10\xdf\b\x12\x17\n" +
	"\x12CHAIN_XDC__MAINNET\x10\xe0\b\x12\x1e\n" +
	"\x19CHAIN_CREDITCOIN__MAINNET\x10\xe1\b\x12\x19\n" +
	"\x14CHAIN_FLARE__MAINNET\x10\xe2\b\x12\x19\n" +
	"\x14CHAIN_OASYS__MAINNET\x10\xe3\b\x12\x1c\n" +
	"\x17CHAIN_SONGBIRD__MAINNET\x10\xe4\b\x12\x19\n" +
	"\x14CHAIN_STORY__MAINNET\x10\xe5\b\x12\x1b\n" +
	"\x16CHAIN_VECHAIN__MAINNET\x10\xe6\b\x12\x1c\n" +
	"\x17CHAIN_ZILLIQA2__MAINNET\x10\xe7\b\x12\x1b\n" +
	"\x16CHAIN_BABYLON__MAINNET\x10\xe8\b\x12\x1a\n" +
	"\x15CHAIN_AGORIC__MAINNET\x10\xe9\b\x12\x1a\n" +
	"\x15CHAIN_COREUM__MAINNET\x10\xea\b\x12\x1c\n" +
	"\x17CHAIN_FETCH_AI__MAINNET\x10\xeb\b\x12\x1e\n" +
	"\x19CHAIN_PROVENANCE__MAINNET\x10\xec\b\x12\x1a\n" +
	"\x15CHAIN_INITIA__MAINNET\x10\xed\b\x12\x1d\n" +
	"\x18CHAIN_INJECTIVE__MAINNET\x10\xee\b\x12\x1a\n" +
	"\x15CHAIN_MANTRA__MAINNET\x10\xef\b\x12\x1e\n" +
	"\x19CHAIN_BITCOIN_SV__MAINNET\x10\xf0\b\x12\x18\n" +
	"\x13CHAIN_DASH__MAINNET\x10\xf1\b\x12\x1c\n" +
	"\x17CHAIN_DIGIBYTE__MAINNET\x10\xf2\b\x12\x19\n" +
	"\x14CHAIN_VERGE__MAINNET\x10\xf3\b\x12\x19\n" +
	"\x14CHAIN_ZCASH__MAINNET\x10\xf4\b\x12\x19\n" +
	"\x14CHAIN_POLYX__MAINNET\x10\xf5\b\x12\x1d\n" +
	"\x18CHAIN_ZK_VERIFY__MAINNET\x10\xf6\b\x12\x1b\n" +
	"\x16CHAIN_WESTEND__MAINNET\x10\xf7\b\x12$\n" +
	"\x1fCHAIN_WESTEND_ASSETHUB__MAINNET\x10\xf8\b\x12\x19\n" +
	"\x14CHAIN_PASEO__MAINNET\x10\xf9\b\x12\"\n" +
	"\x1dCHAIN_PASEO_ASSETHUB__MAINNET\x10\xfa\b\x12%\n" +
	" CHAIN_POLKADOT_ASSETHUB__MAINNET\x10\xfb\b\x12\x1b\n" +
	"\x16CHAIN_MEGAETH__MAINNET\x10\xfc\b\x12\x19\n" +
	"\x14CHAIN_TEMPO__MAINNET\x10\xfd\b\x12\x19\n" +
	"\x14CHAIN_AZTEC__MAINNET\x10\xfe\b\x12\x18\n" +
	"\x13CHAIN_MOCA__MAINNET\x10\xff\b\x12\x19\n" +
	"\x14CHAIN_MORPH__MAINNET\x10\x80\t\x12\x16\n" +
	"\x11CHAIN_TAC_MAINNET\x10\x81\t\x12\x16\n" +
	"\x11CHAIN_TEA_MAINNET\x10\x82\t\x12\x1c\n" +
	"\x17CHAIN_ALGORAND__MAINNET\x10\x83\t\x12\x1b\n" +
	"\x16CHAIN_ORDERLY__MAINNET\x10\x84\t\x12\x1a\n" +
	"\x15CHAIN_ABCORE__MAINNET\x10\x85\t\x12\x1c\n" +
	"\x17CHAIN_BSQUARED__MAINNET\x10\x86\t\x12\x17\n" +
	"\x12CHAIN_ADI__MAINNET\x10\x87\t\x12\x1a\n" +
	"\x15CHAIN_STABLE__MAINNET\x10\x88\t\x12\x19\n" +
	"\x14CHAIN_JOVAY__MAINNET\x10\x89\t\x12\x1a\n" +
	"\x15CHAIN_PHAROS__MAINNET\x10\x8a\t\x12\x18\n" +
	"\x13CHAIN_EDGE__MAINNET\x10\x8b\t\x12\x1b\n" +
	"\x16CHAIN_BOTANIX__MAINNET\x10\x8c\t\x12\x1d\n" +
	"\x18CHAIN_ROBINHOOD__MAINNET\x10\x8d\t\x12\x18\n" +
	"\x13CHAIN_KITE__MAINNET\x10\x8e\t\x12\x1c\n" +
	"\x17CHAIN_HUMANITY__MAINNET\x10\x8f\t\x12\x19\n" +
	"\x14CHAIN_APTOS__MAINNET\x10\x90\t\x12\x1c\n" +
	"\x17CHAIN_BITLAYER__MAINNET\x10\x91\t\x12\x18\n" +
	"\x13CHAIN_MOVA__MAINNET\x10\x92\t\x12\x1d\n" +
	"\x18CHAIN_ETHERLINK__MAINNET\x10\x93\t\x12\x19\n" +
	"\x14CHAIN_NEO_X__MAINNET\x10\x94\t\x12\x1b\n" +
	"\x16CHAIN_MOVA__MAINNET_V2\x10\x95\t\x12\x1b\n" +
	"\x16CHAIN_STELLAR__MAINNET\x10\x96\t\x12\x1c\n" +
	"\x17CHAIN_CELESTIA__MAINNET\x10\x97\t\x12\x17\n" +
	"\x12CHAIN_SUI__MAINNET\x10\x98\t\x12\x1b\n" +
	"\x16CHAIN_ETHEREUM__MORDEN\x10\x91N\x12\x1a\n" +
	"\x15CHAIN_ETHEREUM__KOVAN\x10\x92N\x12\x1b\n" +
	"\x16CHAIN_BITCOIN__TESTNET\x10\x93N\x12\x1c\n" +
	"\x17CHAIN_ETHEREUM__ROPSTEN\x10\x96N\x12\x1c\n" +
	"\x17CHAIN_ETHEREUM__RINKEBY\x10\x97N\x12\x1c\n" +
	"\x17CHAIN_ETHEREUM__SEPOLIA\x10\x98N\x12\x1a\n" +
	"\x15CHAIN_FANTOM__TESTNET\x10\xa0N\x12\x19\n" +
	"\x14CHAIN_GNOSIS__CHIADO\x10\xa1N\x12\x1a\n" +
	"\x15CHAIN_AVALANCHE__FUJI\x10\xa2N\x12\x1a\n" +
	"\x15CHAIN_AURORA__TESTNET\x10\xa5N\x12\x19\n" +
	"\x14CHAIN_KLAYTN__BAOBAB\x10\xa8N\x12\x1a\n" +
	"\x15CHAIN_SCROLL__SEPOLIA\x10\xa9N\x12\x17\n" +
	"\x12CHAIN_BSC__TESTNET\x10\xaaN\x12\x1c\n" +
	"\x17CHAIN_ETHEREUM__HOLESKY\x10\xabN\x12\x1a\n" +
	"\x15CHAIN_CELO__ALFAJORES\x10\xacN\x12\x1a\n" +
	"\x15CHAIN_MOONBEAM__ALPHA\x10\xadN\x12\x1a\n" +
	"\x15CHAIN_CRONOS__TESTNET\x10\xaeN\x12\x19\n" +
	"\x14CHAIN_OPBNB__TESTNET\x10\xb0N\x12\x18\n" +
	"\x13CHAIN_KAVA__TESTNET\x10\xb1N\x12#\n" +
	"\x1eCHAIN_IMMUTABLE_ZKEVM__TESTNET\x10\xb2N\x12\x18\n" +
	"\x13CHAIN_VARA__TESTNET\x10\xb4N\x12\x1a\n" +
	"\x15CHAIN_SOLANA__TESTNET\x10\xb5N\x12\x1c\n" +
	"\x17CHAIN_OPTIMISM__SEPOLIA\x10\xb6N\x12\x19\n" +
	"\x14CHAIN_SOLANA__DEVNET\x10\xb7N\x12\x18\n" +
	"\x13CHAIN_BASE__SEPOLIA\x10\xb8N\x12\x18\n" +
	"\x13CHAIN_HAQQ__TESTNET\x10\xb9N\x12 \n" +
	"\x1bCHAIN_FILECOIN__CALIBRATION\x10\xbaN\x12\x18\n" +
	"\x13CHAIN_OKTC__TESTNET\x10\xbcN\x12\x1a\n" +
	"\x15CHAIN_ZKSYNC__SEPOLIA\x10\xbeN\x12\x1b\n" +
	"\x16CHAIN_BERACHAIN__ARTIO\x10\xbfN\x12\x18\n" +
	"\x13CHAIN_POLYGON__AMOY\x10\xc0N\x12\x19\n" +
	"\x14CHAIN_BLAST__SEPOLIA\x10\xc1N\x12\x18\n" +
	"\x13CHAIN_LISK__TESTNET\x10\xc2N\x12\x1c\n" +
	"\x17CHAIN_ARBITRUM__SEPOLIA\x10\xc3N\x12\x18\n" +
	"\x13CHAIN_ZORA__SEPOLIA\x10\xc5N\x12\x18\n" +
	"\x13CHAIN_MODE__TESTNET\x10\xc6N\x12\x19\n" +
	"\x14CHAIN_EVMOS__TESTNET\x10\xc7N\x12\x1b\n" +
	"\x16CHAIN_NEON_EVM__DEVNET\x10\xc8N\x12\x18\n" +
	"\x13CHAIN_HECO__TESTNET\x10\xc9N\x12\x19\n" +
	"\x14CHAIN_METIS__SEPOLIA\x10\xcaN\x12\x1d\n" +
	"\x18CHAIN_PLAYNANCE__TESTNET\x10\xcbN\x12\x1e\n" +
	"\x19CHAIN_BITTORRENT__TESTNET\x10\xccN\x12\x1f\n" +
	"\x1aCHAIN_THUNDERCORE__TESTNET\x10\xcdN\x12\x18\n" +
	"\x13CHAIN_CORE__TESTNET\x10\xceN\x12\x19\n" +
	"\x14CHAIN_TELOS__TESTNET\x10\xcfN\x12\x18\n" +
	"\x13CHAIN_NEAR__TESTNET\x10\xd0N\x12\x18\n" +
	"\x13CHAIN_NEAR__BETANET\x10\xd1N\x12\x1a\n" +
	"\x15CHAIN_MANTLE__SEPOLIA\x10\xd2N\x12)\n" +
	"$CHAIN_OP_CELESTIA_RASPBERRY__TESTNET\x10\xd3N\x12&\n" +
	"!CHAIN_ARBITRUM_BLUEBERRY__TESTNET\x10\xd4N\x12#\n" +
	"\x1eCHAIN_ETHEREUM_BEACON__SEPOLIA\x10\xd6N\x12#\n" +
	"\x1eCHAIN_ETHEREUM_BEACON__HOLESKY\x10\xd7N\x12&\n" +
	"!CHAIN_POLYGON_BLACKBERRY__TESTNET\x10\xd8N\x12(\n" +
	"#CHAIN_POLYGON_ZKEVM_CARDONA_TESTNET\x10\xd9N\x12\x19\n" +
	"\x14CHAIN_LINEA__SEPOLIA\x10\xdaN\x12\x1c\n" +
	"\x17CHAIN_STARKNET__SEPOLIA\x10\xdbN\x12!\n" +
	"\x1cCHAIN_MANTA_PACIFIC__SEPOLIA\x10\xdcN\x12\x1d\n" +
	"\x18CHAIN_EVERCLEAR__SEPOLIA\x10\xddN\x12\x1d\n" +
	"\x18CHAIN_ALEPHZERO__SEPOLIA\x10\xdeN\x12\x1e\n" +
	"\x19CHAIN_COSMOS_HUB__TESTNET\x10\xdfN\x12\x1f\n" +
	"\x1aCHAIN_TAIKO_HEKLA__TESTNET\x10\xe0N\x12\x1a\n" +
	"\x15CHAIN_AXELAR__TESTNET\x10\xe1N\x12\x1b\n" +
	"\x16CHAIN_OSMOSIS__TESTNET\x10\xe2N\x12\x1b\n" +
	"\x16CHAIN_NEUTRON__TESTNET\x10\xe3N\x12\x1d\n" +
	"\x18CHAIN_ROOTSTOCK__TESTNET\x10\xe4N\x12%\n" +
	" CHAIN_OPEN_CAMPUS_CODEX__SEPOLIA\x10\xe5N\x12\x1d\n" +
	"\x18CHAIN_GAMESWIFT__TESTNET\x10\xe6N\x12\x18\n" +
	"\x13CHAIN_ZETA__TESTNET\x10\xe7N\x12\x1b\n" +
	"\x16CHAIN_ZIRCUIT__TESTNET\x10\xe8N\x12 \n" +
	"\x1bCHAIN_AVAIL__TURING_TESTNET\x10\xe9N\x12\x1c\n" +
	"\x17CHAIN_FRAXTAL___TESTNET\x10\xeaN\x12\x1b\n" +
	"\x16CHAIN_TRON_EVM__SHASTA\x10\xebN\x12\x1c\n" +
	"\x17CHAIN_TRON_HTTP__SHASTA\x10\xecN\x12\x19\n" +
	"\x14CHAIN_KROMA__SEPOLIA\x10\xedN\x12\x19\n" +
	"\x14CHAIN_WEMIX__TESTNET\x10\xeeN\x12\x1c\n" +
	"\x17CHAIN_METAL_L2__TESTNET\x10\xefN\x12\x17\n" +
	"\x12CHAIN_BOB__TESTNET\x10\xf0N\x12\x1d\n" +
	"\x18CHAIN_SNAXCHAIN__TESTNET\x10\xf2N\x12\x1a\n" +
	"\x15CHAIN_XLAYER__TESTNET\x10\xf3N\x12\x17\n" +
	"\x12CHAIN_SEI__TESTNET\x10\xf4N\x12\x16\n" +
	"\x11CHAIN_SEI__DEVNET\x10\xf5N\x12\x18\n" +
	"\x13CHAIN_RONIN__SAIGON\x10\xf6N\x12\x19\n" +
	"\x14CHAIN_SONIC__TESTNET\x10\xf7N\x12\x18\n" +
	"\x13CHAIN_LENS__TESTNET\x10\xf8N\x12\x1c\n" +
	"\x17CHAIN_UNICHAIN__SEPOLIA\x10\xf9N\x12\x1c\n" +
	"\x17CHAIN_APECHAIN__SEPOLIA\x10\xfaN\x12\x1b\n" +
	"\x16CHAIN_SONEIUM__TESTNET\x10\xfbN\x12\x17\n" +
	"\x12CHAIN_TON__TESTNET\x10\xfcN\x12\x19\n" +
	"\x14CHAIN_GOAT__TESTNET3\x10\xfdN\x12\x1e\n" +
	"\x19CHAIN_WORLDCHAIN__SEPOLIA\x10\xfeN\x12 \n" +
	"\x1bCHAIN_CRONOS_ZKEVM__TESTNET\x10\xffN\x12\x1b\n" +
	"\x16CHAIN_VICTION__TESTNET\x10\x80O\x12\x1d\n" +
	"\x18CHAIN_0G_NEWTON__TESTNET\x10\x81O\x12\x1d\n" +
	"\x18CHAIN_SUPERSEED__SEPOLIA\x10\x82O\x12\x17\n" +
	"\x12CHAIN_INK__SEPOLIA\x10\x83O\x12\x1c\n" +
	"\x17CHAIN_ABSTRACT__SEPOLIA\x10\x84O\x12\x1b\n" +
	"\x16CHAIN_HASHKEY__TESTNET\x10\x85O\x12!\n" +
	"\x1cCHAIN_GRAVITY_ALPHA__SEPOLIA\x10\x86O\x12\x1f\n" +
	"\x1aCHAIN_HYPERLIQUID__TESTNET\x10\x87O\x12\x1a\n" +
	"\x15CHAIN_MERLIN__TESTNET\x10\x88O\x12\x18\n" +
	"\x13CHAIN_MEZO__TESTNET\x10\x89O\x12\x18\n" +
	"\x13CHAIN_PLUME__DEVNET\x10\x8aO\x12\x19\n" +
	"\x14CHAIN_PLUME__TESTNET\x10\x8bO\x12\x19\n" +
	"\x14CHAIN_MONAD__TESTNET\x10\x8cO\x12\x1c\n" +
	"\x17CHAIN_DOGECOIN__TESTNET\x10\x8dO\x12\x1c\n" +
	"\x17CHAIN_LITECOIN__TESTNET\x10\x8eO\x12 \n" +
	"\x1bCHAIN_BITCOIN_CASH__TESTNET\x10\x8fO\x12\x1a\n" +
	"\x15CHAIN_RIPPLE__TESTNET\x10\x90O\x12\x19\n" +
	"\x14CHAIN_SWELL__TESTNET\x10\x91O\x12\x1c\n" +
	"\x17CHAIN_ZIRCUIT__GARFIELD\x10\x92O\x12\x1a\n" +
	"\x15CHAIN_ETHEREUM__HOODI\x10\x93O\x12!\n" +
	"\x1cCHAIN_ETHEREUM_BEACON__HOODI\x10\x94O\x12\x1d\n" +
	"\x18CHAIN_BERACHAIN__BEPOLIA\x10\x95O\x12\x1a\n" +
	"\x15CHAIN_KADENA__TESTNET\x10\x96O\x12\x19\n" +
	"\x14CHAIN_OZEAN__TESTNET\x10\x97O\x12\x1e\n" +
	"\x19CHAIN_0G_GALILEO__TESTNET\x10\x98O\x12\x1b\n" +
	"\x16CHAIN_MEGAETH__TESTNET\x10\x99O\x12\x18\n" +
	"\x13CHAIN_HEMI__TESTNET\x10\x9aO\x12\x18\n" +
	"\x13CHAIN_CELO__SEPOLIA\x10\x9bO\x12\x1c\n" +
	"\x17CHAIN_SONIC__TESTNET_V2\x10\x9cO\x12.\n" +
	")CHAIN_GNOSIS_CHIADO_BEACON_CHAIN__TESTNET\x10\x9dO\x12\x1a\n" +
	"\x15CHAIN_PLASMA__TESTNET\x10\x9eO\x12\x1a\n" +
	"\x15CHAIN_KATANA__TESTNET\x10\x9fO\x12\x17\n" +
	"\x12CHAIN_TAIKO__HOODI\x10\xa0O\x12\x18\n" +
	"\x13CHAIN_DOMA__TESTNET\x10\xa1O\x12\x1a\n" +
	"\x15CHAIN_SOPHON__TESTNET\x10\xa2O\x12\x17\n" +
	"\x12CHAIN_ARC__TESTNET\x10\xa3O\x12\x1a\n" +
	"\x15CHAIN_SOMNIA__TESTNET\x10\xa4O\x12\x1d\n" +
	"\x18CHAIN_BITTENSOR__TESTNET\x10\xa5O\x12\x1a\n" +
	"\x15CHAIN_DOGEOS__TESTNET\x10\xa6O\x12\x19\n" +
	"\x14CHAIN_IOTEX__TESTNET\x10\xa7O\x12\x18\n" +
	"\x13CHAIN_XRPL__TESTNET\x10\xa8O\x12\x17\n" +
	"\x12CHAIN_XRPL__DEVNET\x10\xa9O\x12\x19\n" +
	"\x14CHAIN_TEMPO__TESTNET\x10\xaaO\x12\x17\n" +
	"\x12CHAIN_XDC__TESTNET\x10\xabO\x12\x1e\n" +
	"\x19CHAIN_CREDITCOIN__TESTNET\x10\xacO\x12\x1d\n" +
	"\x18CHAIN_CREDITCOIN__DEVNET\x10\xadO\x12\x19\n" +
	"\x14CHAIN_FLARE__TESTNET\x10\xaeO\x12\x19\n" +
	"\x14CHAIN_OASYS__TESTNET\x10\xafO\x12\x1c\n" +
	"\x17CHAIN_SONGBIRD__TESTNET\x10\xb0O\x12\x19\n" +
	"\x14CHAIN_STORY__TESTNET\x10\xb1O\x12 \n" +
	"\x1bCHAIN_STORY_AENEID__TESTNET\x10\xb2O\x12\x1b\n" +
	"\x16CHAIN_VECHAIN__TESTNET\x10\xb3O\x12\x1c\n" +
	"\x17CHAIN_ZILLIQA2__TESTNET\x10\xb4O\x12\x1b\n" +
	"\x16CHAIN_ZILLIQA2__DEVNET\x10\xb5O\x12\x1b\n" +
	"\x16CHAIN_BABYLON__TESTNET\x10\xb6O\x12\x1a\n" +
	"\x15CHAIN_COREUM__TESTNET\x10\xb7O\x12\x1c\n" +
	"\x17CHAIN_FETCH_AI__TESTNET\x10\xb8O\x12\x1e\n" +
	"\x19CHAIN_PROVENANCE__TESTNET\x10\xb9O\x12\x1a\n" +
	"\x15CHAIN_INITIA__TESTNET\x10\xbaO\x12\x1d\n" +
	"\x18CHAIN_INJECTIVE__TESTNET\x10\xbbO\x12\x1a\n" +
	"\x15CHAIN_MANTRA__TESTNET\x10\xbcO\x12\x1e\n" +
	"\x19CHAIN_BITCOIN_SV__TESTNET\x10\xbdO\x12\x18\n" +
	"\x13CHAIN_DASH__TESTNET\x10\xbeO\x12\x1c\n" +
	"\x17CHAIN_DIGIBYTE__TESTNET\x10\xbfO\x12\x19\n" +
	"\x14CHAIN_VERGE__TESTNET\x10\xc0O\x12\x19\n" +
	"\x14CHAIN_ZCASH__TESTNET\x10\xc1O\x12\x19\n" +
	"\x14CHAIN_POLYX__TESTNET\x10\xc2O\x12\x1d\n" +
	"\x18CHAIN_ZK_VERIFY__TESTNET\x10\xc7O\x12\"\n" +
	"\x1dCHAIN_TEMPO_MODERATO__TESTNET\x10\xc8O\x12\x1e\n" +
	"\x19CHAIN_MEGAETH__TESTNET_V2\x10\xc9O\x12\x19\n" +
	"\x14CHAIN_AZTEC__TESTNET\x10\xcaO\x12\x18\n" +
	"\x13CHAIN_AZTEC__DEVNET\x10\xcbO\x12\x18\n" +
	"\x13CHAIN_MOCA__TESTNET\x10\xccO\x12\x19\n" +
	"\x14CHAIN_MORPH__TESTNET\x10\xcdO\x12\x1d\n" +
	"\x18CHAIN_ROBINHOOD__TESTNET\x10\xceO\x12\x1a\n" +
	"\x15CHAIN_TACSPB__TESTNET\x10\xcfO\x12\x17\n" +
	"\x12CHAIN_TEA__SEPOLIA\x10\xd0O\x12\x1c\n" +
	"\x17CHAIN_ALGORAND__TESTNET\x10\xd1O\x12\x1c\n" +
	"\x17CHAIN_ALGORAND__BETANET\x10\xd2O\x12\x1b\n" +
	"\x16CHAIN_ORDERLY__TESTNET\x10\xd3O\x12\x1a\n" +
	"\x15CHAIN_STABLE__TESTNET\x10\xd4O\x12\x19\n" +
	"\x14CHAIN_JOVAY__SEPOLIA\x10\xd5O\x12\x1a\n" +
	"\x15CHAIN_PHAROS__TESTNET\x10\xd6O\x12#\n" +
	"\x1eCHAIN_PHAROS_ATLANTIC__TESTNET\x10\xd7O\x12\x18\n" +
	"\x13CHAIN_EDGE__TESTNET\x10\xd8O\x12\x1b\n" +
	"\x16CHAIN_BOTANIX__TESTNET\x10\xd9O\x12\x1c\n" +
	"\x17CHAIN_HUMANITY__TESTNET\x10\xdaO\x12\x19\n" +
	"\x14CHAIN_APTOS__TESTNET\x10\xdbO\x12\x1c\n" +
	"\x17CHAIN_BITLAYER__TESTNET\x10\xdcO\x12\x18\n" +
	"\x13CHAIN_MOVA__TESTNET\x10\xddO\x12\x1f\n" +
	"\x1aCHAIN_ETHERLINK__SHADOWNET\x10\xdeO\x12\x19\n" +
	"\x14CHAIN_NEO_X__TESTNET\x10\xdfO\x12\x1b\n" +
	"\x16CHAIN_STELLAR__TESTNET\x10\xe0O\x12\x1a\n" +
	"\x15CHAIN_CELESTIA__MOCHA\x10\xe1O\x12\x17\n" +
	"\x12CHAIN_SUI__TESTNET\x10\xe2O\x12\x16\n" +
	"\x11CHAIN_SUI__DEVNET\x10\xe3O\x12\x1b\n" +
	"\x15CHAIN_LAMBDA__VIRTUAL\x10\xa0\x8d\x06\"\x04\b\x02\x10\x02\"\x06\b\xe9\a\x10\xe9\a\"\x06\b\x94N\x10\x94N\"\x06\b\x95N\x10\x95N\"\x06\b\x99N\x10\x99N\"\x06\b\x9aN\x10\x9aN\"\x06\b\x9bN\x10\x9bN\"\x06\b\x9cN\x10\x9cN\"\x06\b\x9dN\x10\x9dN\"\x06\b\x9eN\x10\x9eN\"\x06\b\x9fN\x10\x9fN\"\x06\b\xa3N\x10\xa3N\"\x06\b\xa4N\x10\xa4N\"\x06\b\xa6N\x10\xa6N\"\x06\b\xa7N\x10\xa7N\"\x06\b\xafN\x10\xafN\"\x06\b\xb3N\x10\xb3N\"\x06\b\xbbN\x10\xbbN\"\x06\b\xbdN\x10\xbdN\"\x06\b\xc4N\x10\xc4N\"\x06\b\xd5N\x10\xd5N\"\x06\b\xf1N\x10\xf1N*\x96\x01\n" +
	"\x10AvailabilityEnum\x12\x11\n" +
	"\rAVAIL_UNKNOWN\x10\x00\x12\f\n" +
	"\bAVAIL_OK\x10\x01\x12\x11\n" +
	"\rAVAIL_LAGGING\x10\x02\x12\x12\n" +
	"\x0eAVAIL_IMMATURE\x10\x03\x12\x11\n" +
	"\rAVAIL_SYNCING\x10\x04\x12\x15\n" +
	"\x11AVAIL_UNAVAILABLE\x10\x05\x12\x10\n" +
	"\fAVAIL_FORKED\x10\x06*o\n" +
	"\x10FinalizationType\x12\x1c\n" +
	"\x18FINALIZATION_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17FINALIZATION_SAFE_BLOCK\x10\x01\x12 \n" +
	"\x1cFINALIZATION_FINALIZED_BLOCK\x10\x02B\x19\n" +
	"\x17io.emeraldpay.api.protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_proto_goTypes = []any{
	(ChainRef)(0),            // 0: emerald.ChainRef
	(AvailabilityEnum)(0),    // 1: emerald.AvailabilityEnum
	(FinalizationType)(0),    // 2: emerald.FinalizationType
	(*Chain)(nil),            // 3: emerald.Chain
	(*SingleAddress)(nil),    // 4: emerald.SingleAddress
	(*XpubAddress)(nil),      // 5: emerald.XpubAddress
	(*MultiAddress)(nil),     // 6: emerald.MultiAddress
	(*ReferenceAddress)(nil), // 7: emerald.ReferenceAddress
	(*AnyAddress)(nil),       // 8: emerald.AnyAddress
	(*Asset)(nil),            // 9: emerald.Asset
	(*BlockInfo)(nil),        // 10: emerald.BlockInfo
	(*FinalizationData)(nil), // 11: emerald.FinalizationData
}
var file_common_proto_depIdxs = []int32{
	0, // 0: emerald.Chain.type:type_name -> emerald.ChainRef
	4, // 1: emerald.MultiAddress.addresses:type_name -> emerald.SingleAddress
	4, // 2: emerald.AnyAddress.address_single:type_name -> emerald.SingleAddress
	6, // 3: emerald.AnyAddress.address_multi:type_name -> emerald.MultiAddress
	5, // 4: emerald.AnyAddress.address_xpub:type_name -> emerald.XpubAddress
	7, // 5: emerald.AnyAddress.address_ref:type_name -> emerald.ReferenceAddress
	0, // 6: emerald.Asset.chain:type_name -> emerald.ChainRef
	2, // 7: emerald.FinalizationData.type:type_name -> emerald.FinalizationType
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[5].OneofWrappers = []any{
		(*AnyAddress_AddressSingle)(nil),
		(*AnyAddress_AddressMulti)(nil),
		(*AnyAddress_AddressXpub)(nil),
		(*AnyAddress_AddressRef)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
