export const CHAIN_DESCRIPTION = {
  polygon: `Polygon is a layer two or sidechain scaling solution that runs alongside
      the {ETHEREUM_LINK} blockchain, allowing for speedy transactions and low
      fees. MATIC is the network's native cryptocurrency, which is used for
      fees, staking, and more. dRPC's Polygon RPC endpoints provide robust,
      reliable access to the Polygon network, enabling developers and users to
      integrate smoothly and interact seamlessly with Polygon's blockchain.`,
  arbitrum: `A significant layer 2 scaling solution for {ETHEREUM_LINK} (categorized as
      level 2). Utilizing its native token, ETH, for cost-efficient and rapid
      transactions. Enhancing decentralized applications with advanced
      scalability and usability. dRPC offers dedicated Arbitrum RPC endpoints,
      providing reliable and efficient access to the Arbitrum blockchain,
      facilitating seamless integration and data interaction for developers and
      users.`,
  "arbitrum-nova": `Arbitrum Nova is an AnyTrust chain that aims for ultra low transaction fees. Nova differs from Arbitrum One by not posting transaction data on chain, but to Data Availability Committee. If you find something wrong on this page you can submit an issue or edit the information. dRPC's integration with Arbitrum Nova RPC offers developers and businesses a gateway to leverage these innovations for scalable and cost-effective blockchain solutions.`,
  avalanche: `A cutting-edge Layer 1 blockchain platform, fostering rapid, secure decentralized applications. AVAX is its native currency, driving network activities and powering a dynamic ecosystem of financial applications and services. dRPC's Avalanche RPC endpoints empower developers with reliable and efficient access to this robust network.`,
  bsc: `A major Layer 1 blockchain empowering decentralized applications with high-speed, low-cost transactions. BNB serves as its native currency, fueling the Binance Smart Chain ecosystem's growth and innovation. dRPC's BNB Smart chain RPC endpoints offer streamlined access to this dynamic ecosystem, enhancing connectivity and functionality.`,
  gnosis: `Gnosis operates as a prominent decentralized prediction market platform, facilitating information discovery and forecasting. It functions as a layer 2 solution, leveraging GNO tokens to incentivize participation and decision-making in a transparent and open ecosystem. dRPC complements this innovation by providing specialized Gnosis RPC endpoints, designed for seamless and secure access to Gnosis's unique features and capabilities.`,
  optimism: `Optimism, a leading Layer 2 scaling solution for Ethereum, revolutionizes
      blockchain interactions with its Optimistic Rollups technology. By
      providing faster and more cost-effective transactions, Optimism
      significantly improves the user experience on the {ETHEREUM_LINK} network.
      dRPC complements this innovation by offering Optimism RPC endpoints,
      enabling robust, secure, and efficient connections to the Optimism
      network, thereby streamlining blockchain development and interaction.`,
  zksync: `A notable layer 2 scaling solution for {ETHEREUM_LINK}, operating at level
      2. Its native currency, ETH, powers swift and low-cost transactions,
      boosting decentralized applications by enhancing scalability and usability
      through innovative zkRollup technology. dRPC's zkSync RPC endpoints
      empower developers and businesses to harness the full potential of
      zkSync's layer 2 solutions, offering seamless integration and enhanced
      performance for decentralized applications.`,
  kusama: `An innovative, multi-chain platform built as a level 1 network, fostering blockchain experimentation and development. KSM, its native currency, empowers a dynamic ecosystem of parachains, enabling rapid and customizable blockchain solutions.`,
  polkadot: `A cutting-edge, interoperable platform functioning as a level 1 network. Its native currency, DOT, fuels a versatile ecosystem of parachains, enabling seamless blockchain communication and collaboration for innovative decentralized applications and services.`,
  pyth: `An advanced decentralized network, operating at level 1. It provides real-time financial data, enhancing global markets. Its native currency, PYTH, incentivizes participants and fuels accurate, high-speed data feeds, revolutionizing financial information accessibility and reliability.`,
  quicksilver: `A cutting-edge layer 2 network built on Ethereum. It enhances scalability and usability while using ETH as its native currency for fast, cost-efficient transactions. Quicksilver empowers decentralized applications, making blockchain interactions seamless and accessible.`,

  threshold: `A privacy-focused blockchain platform offering advanced threshold cryptography. Enabling secure, private transactions and data sharing. Harnessing its native token, THRESH, for efficient and confidential blockchain interactions, fostering enhanced privacy and data protection.`,
  umnee: `No description available at that moment.`,
  vega: `A decentralized trading protocol and platform empowering derivatives markets. Operating as a layer 1 network, it utilizes VEGA tokens to facilitate open and borderless trading, providing transparency and liquidity for a wide range of financial instruments and assets.`,
  "polygon-zkevm": `An innovative layer 2 scaling solution combining ZK-Rollups and Ethereum Virtual Machine compatibility. Enhancing scalability and efficiency on the Polygon network, it enables fast, low-cost transactions for decentralized applications while maintaining Ethereum's familiar development environment and tools. dRPC's Polygon zkEVM RPC endpoints further empower this technology, offering developers seamless, high-performance access to Polygon's advanced scaling capabilities.`,
  base: `Base is an open-source optimistic rollup built on the {ETHEREUM_LINK}
      blockchain. Rollups are L2 blockchains built to help layer one (L1)
      blockchains like {BITCOIN_LINK} and Ethereum scale. They bundle hundreds of
      transactions and submit them to L1 as a single transaction, which reduces
      gas fees for the end user. dRPC's Base RPC offerings ensure foundational
      access and seamless integration with multiple blockchain platforms,
      underpinning the functionality and efficiency of advanced blockchain
      applications.`,
  fantom: `A highly efficient and secure blockchain platform. Operating as a layer 1 network, it offers near-instant transactions and low fees. Its native token, FTM, powers decentralized applications and DeFi projects, fostering innovation and accessibility within the blockchain ecosystem. dRPC's Fantom RPC endpoints further empower this platform, offering seamless and reliable access for developers and users alike.`,
  linea: `Linea is a network that scales the experience of Ethereum. Its out-of-the-box compatibility with the Ethereum Virtual Machine enables the deployment of already-existing applications, as well as the creation of new ones that would be too costly on Mainnet. dRPC's Linea RPC endpoints facilitate this scalability and innovation by providing developers with reliable and efficient access to the Linea network.`,
  ethereum: (
    <>
      <h2>
        Ethereum (ETH) is a decentralized, open-source blockchain featuring
        smart contract functionality.
      </h2>
      <h3>
        It is the second-largest cryptocurrency by market capitalization, after
        Bitcoin.
      </h3>{" "}
      Ethereum is the most actively used blockchain. dRPC enhances this
      ecosystem by offering reliable and efficient Ethereum RPC endpoints,
      enabling seamless access and data integration from the Ethereum
      blockchain.
    </>
  ),
  celo: `Celo is a blockchain network that helps in allowing mobile users worldwide to use cryptocurrencies to make financial transactions. dRPC further facilitates this by providing fast and secure Celo RPC endpoints, enabling seamless blockchain integration for developers and businesses.`,
  klaytn: `Kaia is a highly optimized, BFT-based public blockchain that aims to meet the enterprise-grade reliability. dRPC's Kaia RPC services complement this by offering streamlined and secure access to the Kaia network, enhancing user and developer experiences.`,
  mantle: `Mantle Network is an EVM-compatible technology stack for scaling Ethereum. dRPC supports this innovation with high-performance Mantle RPC endpoints tailored for seamless scalability and integration.`,
  scroll: `Scroll seamlessly extends Ethereum’s capabilities through zero knowledge tech and EVM equivalence. The L2 blockchain built by Ethereum devs for Ethereum devs. dRPC enhances this ecosystem with reliable and efficient Scroll RPC endpoints, enabling seamless access and data integration from the Scroll blockchain.`,
  aurora: `Aurora is an Ethereum Virtual Machine (EVM) implemented as a smart contract on NEAR Protocol, providing a high-throughput, scalable platform with low transaction costs. dRPC enhances this with robust Aurora RPC endpoints for seamless blockchain integration.`,
  moonbeam: `Moonbeam is a fully Ethereum-compatible smart contract platform on Polkadot. Moonriver is a companion network to Moonbeam and provides a permanently incentivized canary network. dRPC's Moonbeam RPC endpoints empower developers with robust and efficient tools for building on this versatile platform, enhancing both Ethereum and Polkadot ecosystem connectivity.`,
  opbnb: `opBNB is a high-performance layer-2 solution within the BNB ecosystem, built using the OP Stack. Leveraging its block size of 100M, opBNB's gas fees remain stable and low cost, making it a great solution for widespread adoption across multiple digital environments. From gaming and decentralized exchanges to daily use and digital collectibles, opBNB caters to a diverse set of needs while delivering optimal performance. dRPC's opBNB RPC endpoints further empower developers by providing fast, secure, and scalable access to the opBNB network, facilitating seamless integration and interaction with the blockchain.`,
  metis: `Metis is an Ethereum Layer 2 Rollup platform that offers simple and fast smart contract deployment within the network. Metis provides several solutions to solve the big challenges we face in the main net Ethereum, including transaction speed, cost, and scalability. dRPC enhances the Metis ecosystem with fast, secure, and scalable Metis RPC endpoints, facilitating seamless integration and optimal performance for developers.`,
  cronos: `Cronos is an {ETHEREUM_LINK}-compatible Layer 1 blockchain network built
      on the Cosmos SDK, and it is supported by Crypto.com, Crypto.org, and app
      developers and partners in the ecosystem. dRPC's Cronos RPC endpoints are
      designed to leverage this robust network, providing users and developers
      with efficient, scalable, and easy-to-integrate solutions.`,
  starknet: `Starknet is a Zero-Knowledge Rollup (ZK-Rollup) that is decentralized, permissionless, and censorship-resistant. It supports general computation over Ethereum. Developers create applications on Starknet allowing users to send transactions the same way they do with Ethereum today. All Starknet transactions are periodically batched, and their validity is proven on a stark proof, which is then verified on the Ethereum Blockchain. dRPC's Starknet RPC endpoints bring unmatched efficiency and security to these interactions, facilitating a seamless blockchain experience.`,
  "immutable-zkevm": `Explore Immutable's zkEVM, a cutting-edge protocol for scaling Ethereum using zk-rollups. dRPC enhances this ecosystem by providing efficient, secure, and scalable Immutable zkEVM RPC endpoints for seamless integration with your Web3 projects.`,
  kava: `Kava is a decentralized blockchain that combines the speed and interoperability of Cosmos with the developer power of Ethereum, enhanced by dRPC's dedicated RPC endpoints for seamless development and integration.`,
  astar: `Astar zkEVM is a cutting-edge blockchain network that leverages zk-SNARKs to achieve scalability and privacy. dRPC enhances this ecosystem by offering efficient, reliable, and decentralized Astar zkEVM RPC endpoints, empowering developers to build scalable and privacy-preserving Web3 applications.`,
  bitcoin: `Bitcoin is a consensus network that enables a new payment system and a completely digital money. It is the first decentralized peer-to-peer payment network that is powered by its users with no central authority or middlemen. From a user perspective, Bitcoin is pretty much like cash for the Internet. Bitcoin can also be seen as the most prominent triple entry bookkeeping system in existence. dRPC's Bitcoin RPC services facilitate easy and efficient interaction with this revolutionary network, offering a gateway to its robust and transparent financial system.`,
  solana: `Solana is a blockchain platform designed to host decentralized, scalable applications. Founded in 2017, it is an open-source project currently run by Solana Foundation based in Geneva, while the blockchain was built by San Francisco-based Solana Labs. dRPC elevates this by offering robust Solana RPC endpoints, ensuring fast, secure, and reliable access to the Solana network for seamless data interaction and integration.`,
  vara: `Vara Network is the inaugural Layer-1 platform developed using the Gear Protocol. It seamlessly integrates Gear Protocol's suite of features, including the actor model, persistent memory, WASM, and more. Built on the Substrate framework, Vara ensures forkless runtime upgrades. dRPC enhances this ecosystem by offering reliable and efficient Vara Network RPC endpoints, enabling seamless access and data integration from the Vara Network blockchain.`,
  berachain: `Berachain is a decentralized blockchain platform designed to empower Web3 projects with efficient and scalable solutions. dRPC enriches this ecosystem by providing reliable and efficient Berachain RPC endpoints, facilitating seamless access and data integration for developers and users alike.`,
  lisk: `Lisk is a Layer 2 blockchain dedicated to bringing Web3 adoption in emerging markets back to Ethereum. By leveraging cost-efficient, scalable, and innovative Layer 2 technology, Lisk enables real-world applications in emerging markets to operate efficiently on Ethereum for the first time. Lisk's founder-focused approach provides a comprehensive ecosystem of startup programs, tooling, seed liquidity, and knowledge bases to support local founders from inception to success. As a long-standing Web3 infrastructure project, Lisk has been contributing towards democratizing blockchain accessibility for developers globally since 2016. As an original member of the Optimism Superchain, Lisk also plays a pivotal role in building the industry’s first truly interoperable supernetwork alongside Optimism, Base, Mode, and Worldchain. dRPC enhances this ecosystem by offering efficient, reliable, and scalable Lisk RPC endpoints, ensuring seamless data interaction and integration with the Lisk blockchain.`,
  blast: `Blast is an L2 with native yield for ETH and stablecoins. Yield makes it possible to create new revenue streams and provide novel rewards for end-users. dRPC offers efficient, secure, and scalable Blast RPC endpoints for Blast Mainnet and Blast Sepolia networks, ensuring seamless integration and interaction with the Blast blockchain.`,
  harmony: `Harmony One is a fast and open blockchain for decentralized applications. Its mainnet runs Ethereum applications with 2-second transaction finality with tiny fees. Harmony is your gateway to a seamless and cost-effective decentralized future. Through dRPC, developers gain access to efficient Harmony RPC endpoints, enhancing the blockchain's reach and facilitating even smoother, cost-effective application integrations.`,
  filecoin: `Filecoin is a decentralized storage network designed to store humanity's most important information. It leverages blockchain technology to provide secure and efficient storage solutions for data storage and retrieval. dRPC enhances this ecosystem by offering reliable and efficient Filecoin RPC endpoints, enabling seamless access and data integration from the Filecoin network.`,
  fuse: `Fuse is revolutionizing Web3 projects with its focus on low-cost, fast, and secure transactions. dRPC enhances this ecosystem by providing efficient, reliable, and decentralized Fuse RPC endpoints, empowering developers with seamless integration and data access.`,
  taiko: `Taiko is an innovative blockchain platform designed for building Web3 projects. Experience the power of Taiko with dRPC's efficient and reliable RPC endpoints, facilitating seamless integration and data interaction.`,
  haqq: `Discover HAQQ, a decentralized protocol for Web3 applications. Secure your digital assets with HAQQ's innovative blockchain solutions. dRPC enhances this ecosystem with efficient and reliable HAQQ RPC endpoints, enabling seamless data interaction and integration.`,
  manta: ` Manta Network is a privacy-focused Layer-2 scaling solution for Ethereum, providing confidential transactions and privacy-preserving decentralized applications. dRPC enhances this ecosystem by offering reliable and efficient Manta Network RPC endpoints, enabling seamless access and data integration from the Manta Network blockchain.`,
  okt: `OKT Chain, the blockchain powering the OKExChain ecosystem, offers high-performance and scalability for decentralized applications. dRPC enhances this ecosystem by providing efficient and reliable OKT Chain RPC endpoints for seamless integration and data interaction.`,
  evmos: `Evmos is a Cosmos SDK-based platform offering full Ethereum Virtual Machine (EVM) compatibility, enabling developers to deploy smart contracts and dApps with Web3 support in the Cosmos ecosystem. It bridges Ethereum and Cosmos, facilitating asset and liquidity transfers while emphasizing scalability, interoperability, and user experience.`,
  heco: `Huobi HECO Chain (Heco) is a decentralized, high-efficiency, and energy-saving public chain. It is compatible with smart contracts and supports high-performance transactions. The endogenous token of Heco is HT, and it adopts the HPoS consensus mechanism. Heco will continue to improve the efficiency of Ethereum by Layer2, which will supplement and empower the Ethereum ecosystem. dRPC enhances this ecosystem further by offering reliable and efficient Heco RPC endpoints, facilitating seamless access and data integration from the Heco blockchain.`,
  mode: `Mode is the Modular DeFi L2 building the Superchain alongside Optimism. The goal of Mode is to empower developers and users to grow an ecosystem of world-class applications and be directly rewarded for their contribution. Mode builds new onchain economic systems to enable developers to scale their applications, provide higher yields for users. If you have ever deployed to any EVM chains you can deploy to Mode quickly and easily. Build experimental DeFi on Mode, get hands-on support to scale your application and earn predictable revenue through sequencer fee sharing and developer airdrops. dRPC enhances this ecosystem by offering reliable and efficient Mode RPC endpoints, enabling seamless access and data integration from the Mode blockchain.`,
  moonriver: `In June 2021, Moonriver first launched as a parachain on the Kusama network. Moonriver is a sister network of Moonbeam, and provides an environment to test new code under real economic conditions. Developers now have access to start experimenting and building on an incentivized canary network connected to Kusama. dRPC enhances the Moonriver ecosystem by offering reliable and efficient Moonriver RPC endpoints, enabling seamless access and data integration from the Moonriver blockchain.`,
  "neon-evm": `Neon EVM bridges Ethereum dApps onto Solana, offering seamless scalability and vibrant ecosystem access. With dRPC's fast, secure, and scalable Neon EVM RPC endpoints, developers harness efficient blockchain connectivity for enhanced web3 projects.`,
  ronin: `Ronin, an EVM blockchain hyper optimized for gaming by Sky Mavis, the mastermind behind Axie Infinity. It stands alone in scaling a single game to support millions of daily users and facilitating over $4 billion in NFT transactions. With its focus on rapid transactions and minimal fees, Ronin ensures seamless in-game experiences, solidifying its dominance in the realm of Web3 gaming. With dRPC's efficient and reliable Ronin RPC endpoints, developers can seamlessly integrate Ronin into their Web3 projects, ensuring fast and secure transactions.`,
  telos: `Telos is a Delegated Proof of Stake (DPOS) Layer-1 blockchain that offers unparalleled developer compatibility. With its comprehensive toolkit and dedicated onboarding support, it enables the seamless development and deployment of smart contracts on fast, scalable, and cost-efficient EVM. Underpinned by strong governance and fueled by a vibrant, passionate community, Telos stands as a beacon for the Web3 future's potential.`,
  thundercore: `Discover Thundercore, the cutting-edge platform for building blockchain applications. Fully Ethereum Virtual Machine (EVM) compatible, Thundercore ensures seamless development for Ethereum developers. dRPC offers Thundercore RPC endpoints, enabling efficient and reliable blockchain integration for Thundercore developers.`,
  "zeta-chain": `ZetaChain stands as a pioneering, public blockchain, enabling omnichain smart contracts and messaging across all blockchains. It tackles the challenges of "cross-chain" and "multi-chain" operations, aiming to unlock the crypto and global financial ecosystems for everyone. ZetaChain fosters a versatile, multi-chain crypto environment, allowing seamless movement and utilization of various blockchain benefits such as DeFi, payments, and more. dRPC complements this ecosystem by providing efficient ZetaChain RPC endpoints, facilitating easy access and integration with the ZetaChain blockchain, streamlining Web3 infrastructure management.`,
  zora: `The Zora Network is Layer 2 blockchain built to help bring media onchain. Most L2s are DeFi centric whereas the Zora Network is an “NTF first” ecosystem. Zora is secured by Ethereum and Powered by the OP Stack. dRPC enhances the Zora ecosystem by offering reliable and efficient Zora RPC endpoints, enabling seamless access and data integration from the Zora Network.`,
  bittorrent: `Bittorrent-Chain (BTTC) serves as a layer 2 scaling solution, aiming to address scalability and usability challenges while maintaining decentralization. Fully compatible with Ethereum, BTTC offers seamless migration for existing Ethereum applications. Experience ultra-high throughput and minimal fees with dRPC's Bittorrent RPC endpoints, ensuring efficient and reliable blockchain integration for your projects.`,
  "boba-ethereum": `Boba is a multichain network that currently supports two chains: Ethereum (ETH) and Binance Smart Chain (BNB). Boba Ethereum RPC enables seamless interaction with Boba Network's Eth Chain, a Layer-2 solution built on Ethereum. dRPC provides efficient and reliable RPC endpoints, empowering developers to integrate Boba ETH into their Web3 projects for enhanced scalability, security, and decentralization.`,
  "boba-bnb": `Boba is a multichain network that currently supports two chains: Ethereum (ETH) and Binance Smart Chain (BNB). Boba Ethereum RPC enables seamless interaction with Boba Network's Eth Chain, a Layer-2 solution built on Ethereum. dRPC provides efficient and reliable RPC endpoints, empowering developers to integrate Boba ETH into their Web3 projects for enhanced scalability, security, and decentralization.`,
  core: `Core (CORE) is a Turing-complete and EVM-compatible layer-one blockchain leveraging the Bitcoin hash rate and DPoS consensus. Powered by its novel consensus mechanism, “Satoshi Plus,” Core aims to be secure, scalable, and decentralized. Explore dRPC's Core Network RPC endpoints for seamless integration and data interaction with the Core blockchain.`,
  near: `NEAR, the user-friendly and carbon-neutral blockchain, offers fast, secure, and infinitely scalable solutions. Explore dRPC's NEAR RPC endpoints for seamless integration with NEAR's performance-driven ecosystem.`,
  playnance: `Playnance, an innovative Web3 iGaming studio, operates at the intersection of GameTech, FinTech, and DeFi, crafting engaging and secure experiences for players and partners. dRPC enhances Playnance's ecosystem by offering efficient, reliable, and decentralized RPC endpoints, ensuring seamless integration and interaction for Web3 projects.`,
  dymension: `Dymension, a network of lightning-fast modular blockchains known as RollApps, sets the stage for scalable decentralized applications. dRPC extends this ecosystem with reliable Dymension RPC endpoints, ensuring seamless connectivity and access to decentralized data for Web3 applications.`,
  "gelato-op-celestia": `Gelato OP Celestia enables high-throughput Ethereum Layer 2 chains through integration with OP Stack. Powered by Celestia’s data availability sampling (DAS), it ensures reliability even during temporary downtime, offering seamless transaction processing for decentralized applications. Utilizing Celestia, Gelato OP Celestia RPC endpoints offered by dRPC ensure reliable data access for Web3 applications, supporting seamless integration and scalability.`,
  "gelato-orbit-anytrust": `Gelato's innovative Celestia integration with Arbitrum Orbit offers developers an alternative data availability layer, empowering the launch of high-throughput, optimistic-powered Ethereum Layer 2 chains. Leveraging this integration, dRPC provides Gelato Orbit Anytrust RPC endpoints, ensuring fast, secure, and scalable access to Gelato's blockchain network.`,
  "bitcoin-api": `Bitcoin is a consensus network that enables a new payment system and a completely digital money. It is the first decentralized peer-to-peer payment network that is powered by its users with no central authority or middlemen. From a user perspective, Bitcoin is pretty much like cash for the Internet. Bitcoin can also be seen as the most prominent triple entry bookkeeping system in existence. dRPC's Bitcoin APIs facilitate easy and efficient interaction with this revolutionary network, offering a gateway to its robust and transparent financial system.`,
  "solana-api": `Solana is a blockchain platform designed to host decentralized, scalable applications. Founded in 2017, it is an open-source project currently run by Solana Foundation based in Geneva, while the blockchain was built by San Francisco-based Solana Labs. dRPC elevates this by offering robust Solana APIs, ensuring fast, secure, and reliable access to the Solana network for seamless data interaction and integration.`,
  "polygon-api": `Polygon is a layer 2 or sidechain scaling solution that runs alongside the Ethereum blockchain, allowing for speedy transactions and low fees. MATIC is the network's native cryptocurrency, which is used for fees, staking, and more. dRPC's Polygon APIs provide robust, reliable access to the Polygon network, enabling developers and users to integrate smoothly and interact seamlessly with Polygon's blockchain.`,
  alephzero: `Aleph Zero is a blockchain network that enables teams to deploy scalable, secure, low-cost, and ZK privacy-enhanced products across multiple verticals: from DeFi and gaming to enterprise.`,
  "arb-blueberry": `Blueberry is the first public L3 testnet using Arbitrum Orbit on the Arbitrum Anytrust platform, designed to lower transaction costs and increase throughput.`,
  axelar: `Axelar offers secure cross-chain communication for Web3, enabling the creation of Interchain dApps that operate across multiple blockchains. Built on the reliable proof-of-stake system used by Ethereum, Polygon, and Cosmos, Axelar ensures security.`,
  "cosmos-hub": `The Cosmos Hub is the pioneer among thousands of interconnected blockchains forming the Cosmos Network. While ATOM is the main token, the Hub will eventually support numerous other tokens.`,
  neutron: `Neutron is a blockchain network that introduces Smart Contracts to Cosmos-family blockchains through CosmWasm. It operates with networks using the IBC protocol and relies on the Cosmos Hub for security and block validation via Interchain Security.`,
  "opcelestia-raspberry": `Raspberry is the first public testnet featuring Celestia DA. Utilizing the OP stack, it offers developers near-zero computational overhead, rapid throughput, and low transaction costs.`,
  osmosis: `Osmosis is a decentralized exchange (DEX) appchain within the Cosmos ecosystem, functioning as both a Layer-1 blockchain and an application. Built by forking the Cosmos SDK, it is secured by Tendermint's Byzantine Fault-Tolerant (BFT) Proof-of-Stake (PoS) consensus mechanism. Validators must stake the OSMO token, the network's native token. sactions and proposing blocks.`,
  "polygon-blackberry": `Blackberry is a ZK-powered Layer 2 testnet utilizing Polygon CDK. It employs ZK proofs to ensure transaction validity and keeps transaction data off-chain through Data Availability Committees (DACs), enabling cost-efficient transactions and high throughput.`,
  real: `re.al is an Ethereum Layer-2 scaling platform designed to tokenize real-world assets (RWA). It uses advanced cryptographic protocols for efficient transactions and features a modular design for adaptability. The platform ensures high transaction speeds, reduced gas costs, and EVM compatibility, focusing on security, interoperability, and a developer-friendly environment to integrate RWAs seamlessly into the blockchain ecosystem.`,
  rootstock: `Rootstock is Bitcoin's Smart Contract platform, powered by a forked version of the Ethereum Virtual Machine (EVM) known as the Rootstock Virtual Machine (RVM). This ensures compatibility with Ethereum Smart Contracts and associated tools. The native currency, Smart Bitcoin (RBTC), is used for transaction gas fees and is pegged 1:1 with Bitcoin, maintaining a supply of 21 million RBTC. A Powpeg mechanism facilitates the transfer of bitcoins between the Bitcoin and Rootstock blockchains.`,
  "open-campus-codex": `EDU Chain is engineered to onboard real-world educational economies to the blockchain and create an ecosystem of decentralized applications (Dapps) to establish an innovative "Learn Own Earn" model for education. EDU Chain, the first decentralized blockchain for education built by Open Campus, helps to democratize education and empower all participants — learners, educators, edtech innovators — to contribute to and benefit from the future of education. Anyone can support the EDU Chain network by operating a node, which allows them to receive network rewards and participate in governance.`,
  gameswift: `GameSwift Chain is a modular, gaming-optimized Layer 2 solution for Ethereum with $GSWIFT as gas token. Built on the open-source OP Stack and governed by GS DAO, it is the first Gaming and AI Chain in the Superchain ecosystem. With EVM compatibility, GameSwift Chain enables developers to create Layer 3 solutions.`,
  zircuit: `Zircuit is an innovative EVM-compatible zero-knowledge rollup designed to unleash the boundless possibilities of web3. Built on advanced L2 research, this network features a unique hybrid architecture that merges reliable infrastructure with zero-knowledge proofs, providing developers with optimal conditions. Users benefit from high-performance, secure transactions, lower fees, and absolute confidence, thanks to the robust sequencer-level capabilities.`,
  tron: `TRON is an open-source public blockchain platform that supports smart contracts. It’s fully compatible with Ethereum, allowing easy migration of Ethereum smart contracts to TRON with minimal changes. TRON uses a unique consensus mechanism to achieve a high transaction processing speed (TPS) far exceeding Ethereum's, offering developers a superior experience with faster transactions and efficient performance.`,
  fraxtal: `Fraxtal is a modular rollup blockchain (L2) with a "fractal scaling". It’s an EVM-equivalent rollup using the OP stack for a fast, secure, and cost-effective deployment like Optimism & Base. Fraxtal offers modular components for other chains and networks, and features blockspace incentives (Flox) rewarding users and developers for gas usage with FXTL points, convertible into tokens.`,
  goat: `GOAT Network is a Bitcoin Layer 2 (L2) solution utilizing an Optimistic Challenge Protocol (GOAT-OCP) to enhance security and scalability. It integrates with ZKM Entangled Rollup for cross-chain liquidity, supporting high transaction throughput and smart contract execution while maintaining Bitcoin's native security.`,
  metall2: `Metal L2, also known as The Banking Layer, connects the Optimism Superchain directly to The Digital Banking Network (TDBN) by Metallicus. TDBN is an on-chain network of traditional financial institutions that provides seamless fiat onramps through Metal Pay Connect. Metal L2 facilitates easy movement between traditional finance and decentralized finance (DeFi) within the Superchain ecosystem while supporting token transactions on the Ethereum network.`,
  bob: `OB Network is a scalable Bitcoin Layer 2 (L2) solution designed to improve transaction efficiency and enable smart contract functionality. Utilizing the innovative BOB Protocol, it offers low-latency transactions and enhanced user experience. The network supports cross-chain interoperability and liquidity, ensuring seamless integration with various blockchain ecosystems while leveraging Bitcoin's robust security model.`,
  wemix: `WEMIX Network is a blockchain platform focused on gaming and digital content, designed to provide a seamless experience for developers and users. It features a multi-chain architecture that enhances scalability and interoperability, enabling the creation of decentralized applications (dApps) with low transaction fees and high throughput. WEMIX integrates a robust ecosystem of gaming assets and NFTs, allowing users to easily trade and utilize digital goods across various platforms while ensuring security through its consensus mechanism.`,
  xlayer:
    "OKX Layer is a high-performance Layer 2 solution built on the Ethereum blockchain, designed to enhance scalability and reduce transaction costs for decentralized applications (dApps). It leverages zk-Rollups technology, ensuring fast transaction processing and improved security while maintaining compatibility with existing Ethereum smart contracts. The platform supports a wide range of use cases, including DeFi, NFTs, and gaming, facilitating seamless integration and interoperability within the broader blockchain ecosystem. With its focus on user experience, OKX Layer aims to empower developers and users alike by providing a robust infrastructure for innovative applications.",
  snaxchain:
    "SnaxChain is a decentralized governance layer built on the Synthetix protocol, designed to facilitate community-driven decision-making and enhance network participation. It introduces a unique epoch-based governance model, allowing stakeholders to propose and vote on key protocol changes and enhancements. SnaxChain aims to streamline the governance process by utilizing on-chain voting mechanisms and incentivizing active participation from users. This framework fosters a collaborative environment where the community can shape the direction of the Synthetix ecosystem while ensuring transparency and accountability in governance practices.",
  sei: "Sei is a Layer 1 blockchain optimized for decentralized exchanges (DEXs) with a focus on high-speed, low-latency trading, offering fast finality and built-in order matching, making it ideal for trading applications in the DeFi ecosystem.",
  "eth-beacon-chain":
    "The Ethereum Beacon Chain is the foundational Layer 1 blockchain for Ethereum's Proof-of-Stake (PoS) network, designed to manage the consensus mechanism, coordinate validators, and support the eventual transition from Proof-of-Work (PoW), enabling scalability, security, and energy efficiency for the Ethereum ecosystem.",
  ton: "TON (The Open Network) is a Layer 1 blockchain originally developed by Telegram, now continued by the community. It features a scalable, sharded architecture, supporting high transaction throughput and fast finality, making it suitable for various applications like decentralized finance, gaming, and NFTs. TON integrates with Telegram to facilitate seamless Web3 experiences for users, emphasizing speed, security, and decentralized applications within the messaging ecosystem.",
  lens: "Lens is a Web3 social graph built on Polygon, designed to empower users with ownership and control over their social data and interactions. It enables decentralized, user-owned social networks where individuals can create, follow, and engage with content across platforms, all while retaining custody of their profiles, followers, and content. Lens fosters interoperability, allowing to build new social experiences and monetization options without intermediaries, promoting a creator-first ecosystem within the blockchain space.",
  sonic:
    "Sonic is a high-performance EVM-compatible layer-1 blockchain delivering over 10,000 transactions per second with sub-second finality, staking, and governance, and providing a secure Ethereum gateway to ensure seamless liquidity and asset security for developers and users alike.",
  apechain:
    "ApeChain is a creator-centric blockchain built on Arbitrum Orbit, powered by ApeCoin ($APE) to support applications in gaming, finance, and intellectual property.",
  unichain:
    "Unichain is a DeFi-native Ethereum Layer 2 (L2) network developed by Uniswap Labs, designed to serve as the central hub for liquidity across multiple blockchains. It offers faster transactions and significantly reduced fees, enhancing the efficiency of decentralized finance (DeFi) applications.",
  soneium:
    "Soneium is a public blockchain ecosystem developed by Sony Block Solutions Labs, designed to integrate Web3 technologies into daily life by creating an internet where creativity and technology converge.",
  worldchain:
    "Worldchain Network is a global decentralized blockchain ecosystem developed by World Labs. It is designed to facilitate seamless cross-border transactions and interoperability between different blockchain platforms. Worldchain Network leverages cutting-edge consensus mechanisms and smart contract technologies to ensure high scalability, security, and efficiency. By integrating Web3 solutions into various sectors such as finance, supply chain, and digital identity, Worldchain Network aims to create a unified internet infrastructure where diverse digital interactions and data exchanges can occur transparently and trustlessly. The platform empowers developers and businesses to build innovative decentralized applications (dApps) that operate smoothly across multiple blockchain environments, fostering a truly interconnected digital economy.",
  "cronos-zkevm":
    "Cronos zkEVM is a layer-2 scaling solution from the Cronos ecosystem that leverages zero-knowledge rollup technology to improve blockchain scalability, security, and efficiency. Fully compatible with the Ethereum Virtual Machine (EVM), it allows seamless deployment of existing Ethereum smart contracts and decentralized applications (dApps) without modifications. By utilizing zero-knowledge proofs, Cronos zkEVM delivers high throughput and low transaction costs while maintaining robust security standards.",
  viction:
    "Viction is a people-centric layer-1 blockchain that offers zero-gas transactions and enhanced security, making Web3 accessible and safe for everyone. Utilizing a Proof-of-Stake (PoS) consensus mechanism supported by a network of 150 masternodes, Viction achieves scalability and stability. It employs advanced techniques such as double validation, smart contract staking, and proper randomization to enhance security and ensure chain finality. Fully compatible with the Ethereum Virtual Machine (EVM), Viction supports seamless deployment of existing Ethereum smart contracts and decentralized applications (dApps) without modifications.",
  ink: "Ink is a Layer 2 (L2) blockchain built on Optimism's Superchain, designed to serve as a robust foundation for deploying innovative decentralized finance (DeFi) protocols. Leveraging Kraken's extensive security and crypto expertise, Ink offers users a seamless and secure DeFi experience. Key features include sub-second block times for rapid transactions, minimal gas fees to reduce costs, and enhanced security measures at the sequencer level to protect against malicious activities.",
  superseed:
    "SuperSeed focuses on technical teams developing business and industrial automation startups. Leveraging their entrepreneurial experience, they provide capital and hands-on support to help startups achieve their first million in sales. SuperSeed's portfolio includes over 25 high-growth B2B software companies, reflecting their commitment to transforming business operations through technology.",
  "0g": "0G is the first decentralized AI Operating System (dAIOS), designed to power the future of AI by providing a scalable, secure, and versatile infrastructure for AI and Web3 applications. Its modular architecture includes components such as 0G Storage, 0G Data Availability (DA), 0G Compute, and 0G Chain, all optimized for handling massive data loads and complex AI workflows. Fully EVM-compatible, 0G enables seamless deployment of Ethereum-based smart contracts and decentralized applications (dApps).",
  monad:
    "Monad is a high-performance layer-1 blockchain designed to optimize speed, efficiency, and scalability for Web3 applications. Its innovative pipelined execution, parallel processing, and speculative execution deliver unmatched performance while maintaining full EVM compatibility. With near-instant finality and low fees, Monad enables seamless deployment of Ethereum-based smart contracts and dApps, providing a robust foundation for next-generation decentralized finance (DeFi) and blockchain innovation.",
  abstract:
    "Abstract is a modular blockchain designed to simplify Web3 development by providing an intuitive execution layer that abstracts complexity away from developers. It features built-in account abstraction, enabling seamless smart contract interactions and programmable wallets while maintaining full EVM compatibility. With a flexible and scalable architecture, Abstract empowers developers to build next-generation decentralized applications (dApps) with enhanced user experience, interoperability, and security.",
  merlin:
    "Merlin Chain is a Bitcoin Layer 2 solution designed to enhance the Bitcoin ecosystem by enabling high-speed, low-cost transactions while maintaining strong security and decentralization. Leveraging Zero-Knowledge Rollups (ZK-Rollups) and an EVM-compatible architecture, Merlin Chain seamlessly integrates Bitcoin with DeFi, NFTs, and smart contract functionalities. Its innovative infrastructure allows users to bridge BTC into a scalable and efficient ecosystem, unlocking new possibilities for Bitcoin-based applications.",
  mezo: "Mezo is a Bitcoin Layer 2 (L2) economic layer designed to enhance Bitcoin's scalability and utility by providing a faster, cost-effective platform for decentralized applications (dApps) and financial services. Fully compatible with the Ethereum Virtual Machine (EVM), Mezo enables seamless deployment of smart contracts and dApps, thereby expanding Bitcoin's functionality beyond simple transactions.",
  hashkey:
    "HashKey Chain is an EVM-compatible blockchain designed to provide a scalable, secure, and efficient infrastructure for Web3 applications. It enables seamless deployment of smart contracts and decentralized applications (dApps) while ensuring interoperability with Ethereum. Built for enterprises, DeFi, and NFTs, HashKey Chain offers a robust ecosystem with low fees, high performance, and a developer-friendly environment.",
  swell: "Swell is a decentralized liquid staking protocol designed to maximize Ethereum staking rewards while maintaining liquidity. By allowing users to stake ETH and receive liquid staking tokens (LSTs), it enables seamless participation in DeFi without locking assets.",
  ripple: "Ripple Chain is a  blockchain designed for efficient cross-border payments and asset tokenization. Built on the XRP Ledger (XRPL), it provides low-cost transactions, high scalability, and advanced programmability through native smart contract support. ",
};
