// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: celestia/core/v1/tx/tx.proto

package tx

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TxStatusRequest is the request type for the TxStatus gRPC method.
type TxStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// this is the hex encoded transaction hash (should be 64 characters long representing 32 bytes)
	TxId          string `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusRequest) Reset() {
	*x = TxStatusRequest{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusRequest) ProtoMessage() {}

func (x *TxStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusRequest.ProtoReflect.Descriptor instead.
func (*TxStatusRequest) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{0}
}

func (x *TxStatusRequest) GetTxId() string {
	if x != nil {
		return x.TxId
	}
	return ""
}

// TxStatusResponse is the response type for the TxStatus gRPC method.
type TxStatusResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Height int64                  `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Index  uint32                 `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	// execution_code is returned when the transaction has been committed
	// and returns whether it was successful or errored. A non zero
	// execution code indicated an error.
	ExecutionCode uint32 `protobuf:"varint,3,opt,name=execution_code,json=executionCode,proto3" json:"execution_code,omitempty"`
	// error log for failed transactions.
	Error string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	// status is the status of the transaction.
	Status string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	// the error namespace/module.
	Codespace string `protobuf:"bytes,6,opt,name=codespace,proto3" json:"codespace,omitempty"`
	// requested gas limit.
	GasWanted int64 `protobuf:"varint,7,opt,name=gas_wanted,json=gasWanted,proto3" json:"gas_wanted,omitempty"`
	// actual gas consumed.
	GasUsed int64 `protobuf:"varint,8,opt,name=gas_used,json=gasUsed,proto3" json:"gas_used,omitempty"`
	// signers of the transaction.
	Signers       []string `protobuf:"bytes,9,rep,name=signers,proto3" json:"signers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusResponse) Reset() {
	*x = TxStatusResponse{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResponse) ProtoMessage() {}

func (x *TxStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResponse.ProtoReflect.Descriptor instead.
func (*TxStatusResponse) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{1}
}

func (x *TxStatusResponse) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *TxStatusResponse) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *TxStatusResponse) GetExecutionCode() uint32 {
	if x != nil {
		return x.ExecutionCode
	}
	return 0
}

func (x *TxStatusResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TxStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *TxStatusResponse) GetCodespace() string {
	if x != nil {
		return x.Codespace
	}
	return ""
}

func (x *TxStatusResponse) GetGasWanted() int64 {
	if x != nil {
		return x.GasWanted
	}
	return 0
}

func (x *TxStatusResponse) GetGasUsed() int64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *TxStatusResponse) GetSigners() []string {
	if x != nil {
		return x.Signers
	}
	return nil
}

// TxStatusBatchRequest is the request type for the batch TxStatus gRPC method.
type TxStatusBatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// array of hex encoded tx hashes (each hash should be 64 characters long representing 32 bytes)
	TxIds         []string `protobuf:"bytes,1,rep,name=tx_ids,json=txIds,proto3" json:"tx_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusBatchRequest) Reset() {
	*x = TxStatusBatchRequest{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusBatchRequest) ProtoMessage() {}

func (x *TxStatusBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusBatchRequest.ProtoReflect.Descriptor instead.
func (*TxStatusBatchRequest) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{2}
}

func (x *TxStatusBatchRequest) GetTxIds() []string {
	if x != nil {
		return x.TxIds
	}
	return nil
}

// TxStatusResult represents a single transaction status result in a batch response.
type TxStatusResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxHash        string                 `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Status        *TxStatusResponse      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusResult) Reset() {
	*x = TxStatusResult{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusResult) ProtoMessage() {}

func (x *TxStatusResult) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusResult.ProtoReflect.Descriptor instead.
func (*TxStatusResult) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{3}
}

func (x *TxStatusResult) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxStatusResult) GetStatus() *TxStatusResponse {
	if x != nil {
		return x.Status
	}
	return nil
}

// TxStatusBatchResponse is a response type for batched TxStatus query. It contains an array of transaction status
// results.
type TxStatusBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*TxStatusResult      `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxStatusBatchResponse) Reset() {
	*x = TxStatusBatchResponse{}
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxStatusBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxStatusBatchResponse) ProtoMessage() {}

func (x *TxStatusBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_core_v1_tx_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxStatusBatchResponse.ProtoReflect.Descriptor instead.
func (*TxStatusBatchResponse) Descriptor() ([]byte, []int) {
	return file_celestia_core_v1_tx_tx_proto_rawDescGZIP(), []int{4}
}

func (x *TxStatusBatchResponse) GetStatuses() []*TxStatusResult {
	if x != nil {
		return x.Statuses
	}
	return nil
}

var File_celestia_core_v1_tx_tx_proto protoreflect.FileDescriptor

const file_celestia_core_v1_tx_tx_proto_rawDesc = "" +
	"\n" +
	"\x1ccelestia/core/v1/tx/tx.proto\x12\x13celestia.core.v1.tx\x1a\x1cgoogle/api/annotations.proto\"&\n" +
	"\x0fTxStatusRequest\x12\x13\n" +
	"\x05tx_id\x18\x01 \x01(\tR\x04txId\"\x87\x02\n" +
	"\x10TxStatusResponse\x12\x16\n" +
	"\x06height\x18\x01 \x01(\x03R\x06height\x12\x14\n" +
	"\x05index\x18\x02 \x01(\rR\x05index\x12%\n" +
	"\x0eexecution_code\x18\x03 \x01(\rR\rexecutionCode\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1c\n" +
	"\tcodespace\x18\x06 \x01(\tR\tcodespace\x12\x1d\n" +
	"\n" +
	"gas_wanted\x18\a \x01(\x03R\tgasWanted\x12\x19\n" +
	"\bgas_used\x18\b \x01(\x03R\agasUsed\x12\x18\n" +
	"\asigners\x18\t \x03(\tR\asigners\"-\n" +
	"\x14TxStatusBatchRequest\x12\x15\n" +
	"\x06tx_ids\x18\x01 \x03(\tR\x05txIds\"h\n" +
	"\x0eTxStatusResult\x12\x17\n" +
	"\atx_hash\x18\x01 \x01(\tR\x06txHash\x12=\n" +
	"\x06status\x18\x02 \x01(\v2%.celestia.core.v1.tx.TxStatusResponseR\x06status\"X\n" +
	"\x15TxStatusBatchResponse\x12?\n" +
	"\bstatuses\x18\x01 \x03(\v2#.celestia.core.v1.tx.TxStatusResultR\bstatuses2\x93\x02\n" +
	"\x02Tx\x12}\n" +
	"\bTxStatus\x12$.celestia.core.v1.tx.TxStatusRequest\x1a%.celestia.core.v1.tx.TxStatusResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/celestia/core/v1/tx/{tx_id}\x12\x8d\x01\n" +
	"\rTxStatusBatch\x12).celestia.core.v1.tx.TxStatusBatchRequest\x1a*.celestia.core.v1.tx.TxStatusBatchResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/celestia/core/v1/tx/batchB\xc5\x01\n" +
	"\x17com.celestia.core.v1.txB\aTxProtoP\x01Z1github.com/drpcorg/public/pkg/celestia/core/v1/tx\xa2\x02\x04CCVT\xaa\x02\x13Celestia.Core.V1.Tx\xca\x02\x13Celestia\\Core\\V1\\Tx\xe2\x02\x1fCelestia\\Core\\V1\\Tx\\GPBMetadata\xea\x02\x16Celestia::Core::V1::Txb\x06proto3"

var (
	file_celestia_core_v1_tx_tx_proto_rawDescOnce sync.Once
	file_celestia_core_v1_tx_tx_proto_rawDescData []byte
)

func file_celestia_core_v1_tx_tx_proto_rawDescGZIP() []byte {
	file_celestia_core_v1_tx_tx_proto_rawDescOnce.Do(func() {
		file_celestia_core_v1_tx_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_celestia_core_v1_tx_tx_proto_rawDesc), len(file_celestia_core_v1_tx_tx_proto_rawDesc)))
	})
	return file_celestia_core_v1_tx_tx_proto_rawDescData
}

var file_celestia_core_v1_tx_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_celestia_core_v1_tx_tx_proto_goTypes = []any{
	(*TxStatusRequest)(nil),       // 0: celestia.core.v1.tx.TxStatusRequest
	(*TxStatusResponse)(nil),      // 1: celestia.core.v1.tx.TxStatusResponse
	(*TxStatusBatchRequest)(nil),  // 2: celestia.core.v1.tx.TxStatusBatchRequest
	(*TxStatusResult)(nil),        // 3: celestia.core.v1.tx.TxStatusResult
	(*TxStatusBatchResponse)(nil), // 4: celestia.core.v1.tx.TxStatusBatchResponse
}
var file_celestia_core_v1_tx_tx_proto_depIdxs = []int32{
	1, // 0: celestia.core.v1.tx.TxStatusResult.status:type_name -> celestia.core.v1.tx.TxStatusResponse
	3, // 1: celestia.core.v1.tx.TxStatusBatchResponse.statuses:type_name -> celestia.core.v1.tx.TxStatusResult
	0, // 2: celestia.core.v1.tx.Tx.TxStatus:input_type -> celestia.core.v1.tx.TxStatusRequest
	2, // 3: celestia.core.v1.tx.Tx.TxStatusBatch:input_type -> celestia.core.v1.tx.TxStatusBatchRequest
	1, // 4: celestia.core.v1.tx.Tx.TxStatus:output_type -> celestia.core.v1.tx.TxStatusResponse
	4, // 5: celestia.core.v1.tx.Tx.TxStatusBatch:output_type -> celestia.core.v1.tx.TxStatusBatchResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_celestia_core_v1_tx_tx_proto_init() }
func file_celestia_core_v1_tx_tx_proto_init() {
	if File_celestia_core_v1_tx_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_celestia_core_v1_tx_tx_proto_rawDesc), len(file_celestia_core_v1_tx_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_celestia_core_v1_tx_tx_proto_goTypes,
		DependencyIndexes: file_celestia_core_v1_tx_tx_proto_depIdxs,
		MessageInfos:      file_celestia_core_v1_tx_tx_proto_msgTypes,
	}.Build()
	File_celestia_core_v1_tx_tx_proto = out.File
	file_celestia_core_v1_tx_tx_proto_goTypes = nil
	file_celestia_core_v1_tx_tx_proto_depIdxs = nil
}
