// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: celestia/minfee/v1/tx.proto

package minfeev1

import (
	_ "cosmossdk.io/api/cosmos/msg/v1"
	_ "github.com/drpcorg/public/pkg/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgUpdateMinfeeParams defines a message for updating the minimum fee parameters.
type MsgUpdateMinfeeParams struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// authority is the address of the governance account.
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// params defines the minfee parameters to update.
	//
	// NOTE: All parameters must be supplied.
	Params        *Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMinfeeParams) Reset() {
	*x = MsgUpdateMinfeeParams{}
	mi := &file_celestia_minfee_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMinfeeParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMinfeeParams) ProtoMessage() {}

func (x *MsgUpdateMinfeeParams) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_minfee_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMinfeeParams.ProtoReflect.Descriptor instead.
func (*MsgUpdateMinfeeParams) Descriptor() ([]byte, []int) {
	return file_celestia_minfee_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgUpdateMinfeeParams) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *MsgUpdateMinfeeParams) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// MsgUpdateMinfeeParamsResponse is the UpdateMinfeeParams response.
type MsgUpdateMinfeeParamsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateMinfeeParamsResponse) Reset() {
	*x = MsgUpdateMinfeeParamsResponse{}
	mi := &file_celestia_minfee_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateMinfeeParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateMinfeeParamsResponse) ProtoMessage() {}

func (x *MsgUpdateMinfeeParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_minfee_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateMinfeeParamsResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateMinfeeParamsResponse) Descriptor() ([]byte, []int) {
	return file_celestia_minfee_v1_tx_proto_rawDescGZIP(), []int{1}
}

var File_celestia_minfee_v1_tx_proto protoreflect.FileDescriptor

const file_celestia_minfee_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1bcelestia/minfee/v1/tx.proto\x12\x12celestia.minfee.v1\x1a\x1fcelestia/minfee/v1/params.proto\x1a\x14gogoproto/gogo.proto\x1a\x17cosmos/msg/v1/msg.proto\"\x7f\n" +
	"\x15MsgUpdateMinfeeParams\x12\x1c\n" +
	"\tauthority\x18\x01 \x01(\tR\tauthority\x128\n" +
	"\x06params\x18\x02 \x01(\v2\x1a.celestia.minfee.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params:\x0e\x82\xe7\xb0*\tauthority\"\x1f\n" +
	"\x1dMsgUpdateMinfeeParamsResponse2\x80\x01\n" +
	"\x03Msg\x12r\n" +
	"\x12UpdateMinfeeParams\x12).celestia.minfee.v1.MsgUpdateMinfeeParams\x1a1.celestia.minfee.v1.MsgUpdateMinfeeParamsResponse\x1a\x05\x80\xe7\xb0*\x01B\xc6\x01\n" +
	"\x16com.celestia.minfee.v1B\aTxProtoP\x01Z9github.com/drpcorg/public/pkg/celestia/minfee/v1;minfeev1\xa2\x02\x03CMX\xaa\x02\x12Celestia.Minfee.V1\xca\x02\x12Celestia\\Minfee\\V1\xe2\x02\x1eCelestia\\Minfee\\V1\\GPBMetadata\xea\x02\x14Celestia::Minfee::V1b\x06proto3"

var (
	file_celestia_minfee_v1_tx_proto_rawDescOnce sync.Once
	file_celestia_minfee_v1_tx_proto_rawDescData []byte
)

func file_celestia_minfee_v1_tx_proto_rawDescGZIP() []byte {
	file_celestia_minfee_v1_tx_proto_rawDescOnce.Do(func() {
		file_celestia_minfee_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_celestia_minfee_v1_tx_proto_rawDesc), len(file_celestia_minfee_v1_tx_proto_rawDesc)))
	})
	return file_celestia_minfee_v1_tx_proto_rawDescData
}

var file_celestia_minfee_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_celestia_minfee_v1_tx_proto_goTypes = []any{
	(*MsgUpdateMinfeeParams)(nil),         // 0: celestia.minfee.v1.MsgUpdateMinfeeParams
	(*MsgUpdateMinfeeParamsResponse)(nil), // 1: celestia.minfee.v1.MsgUpdateMinfeeParamsResponse
	(*Params)(nil),                        // 2: celestia.minfee.v1.Params
}
var file_celestia_minfee_v1_tx_proto_depIdxs = []int32{
	2, // 0: celestia.minfee.v1.MsgUpdateMinfeeParams.params:type_name -> celestia.minfee.v1.Params
	0, // 1: celestia.minfee.v1.Msg.UpdateMinfeeParams:input_type -> celestia.minfee.v1.MsgUpdateMinfeeParams
	1, // 2: celestia.minfee.v1.Msg.UpdateMinfeeParams:output_type -> celestia.minfee.v1.MsgUpdateMinfeeParamsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_celestia_minfee_v1_tx_proto_init() }
func file_celestia_minfee_v1_tx_proto_init() {
	if File_celestia_minfee_v1_tx_proto != nil {
		return
	}
	file_celestia_minfee_v1_params_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_celestia_minfee_v1_tx_proto_rawDesc), len(file_celestia_minfee_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_celestia_minfee_v1_tx_proto_goTypes,
		DependencyIndexes: file_celestia_minfee_v1_tx_proto_depIdxs,
		MessageInfos:      file_celestia_minfee_v1_tx_proto_msgTypes,
	}.Build()
	File_celestia_minfee_v1_tx_proto = out.File
	file_celestia_minfee_v1_tx_proto_goTypes = nil
	file_celestia_minfee_v1_tx_proto_depIdxs = nil
}
