// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/applications/transfer/v1/packet.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// FungibleTokenPacketData defines a struct for the packet payload
// See FungibleTokenPacketData spec:
// https://github.com/cosmos/ibc/tree/master/spec/app/ics-020-fungible-token-transfer#data-structures
type FungibleTokenPacketData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the token denomination to be transferred
	Denom string `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	// the token amount to be transferred
	Amount string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// the sender address
	Sender string `protobuf:"bytes,3,opt,name=sender,proto3" json:"sender,omitempty"`
	// the recipient address on the destination chain
	Receiver string `protobuf:"bytes,4,opt,name=receiver,proto3" json:"receiver,omitempty"`
	// optional memo
	Memo          string `protobuf:"bytes,5,opt,name=memo,proto3" json:"memo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FungibleTokenPacketData) Reset() {
	*x = FungibleTokenPacketData{}
	mi := &file_ibc_applications_transfer_v1_packet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FungibleTokenPacketData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FungibleTokenPacketData) ProtoMessage() {}

func (x *FungibleTokenPacketData) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_packet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FungibleTokenPacketData.ProtoReflect.Descriptor instead.
func (*FungibleTokenPacketData) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_packet_proto_rawDescGZIP(), []int{0}
}

func (x *FungibleTokenPacketData) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

func (x *FungibleTokenPacketData) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *FungibleTokenPacketData) GetSender() string {
	if x != nil {
		return x.Sender
	}
	return ""
}

func (x *FungibleTokenPacketData) GetReceiver() string {
	if x != nil {
		return x.Receiver
	}
	return ""
}

func (x *FungibleTokenPacketData) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

var File_ibc_applications_transfer_v1_packet_proto protoreflect.FileDescriptor

const file_ibc_applications_transfer_v1_packet_proto_rawDesc = "" +
	"\n" +
	")ibc/applications/transfer/v1/packet.proto\x12\x1cibc.applications.transfer.v1\"\x8f\x01\n" +
	"\x17FungibleTokenPacketData\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x16\n" +
	"\x06sender\x18\x03 \x01(\tR\x06sender\x12\x1a\n" +
	"\breceiver\x18\x04 \x01(\tR\breceiver\x12\x12\n" +
	"\x04memo\x18\x05 \x01(\tR\x04memoB\x89\x02\n" +
	" com.ibc.applications.transfer.v1B\vPacketProtoP\x01ZEgithub.com/drpcorg/public/pkg/ibc/applications/transfer/v1;transferv1\xa2\x02\x03IAT\xaa\x02\x1cIbc.Applications.Transfer.V1\xca\x02\x1cIbc\\Applications\\Transfer\\V1\xe2\x02(Ibc\\Applications\\Transfer\\V1\\GPBMetadata\xea\x02\x1fIbc::Applications::Transfer::V1b\x06proto3"

var (
	file_ibc_applications_transfer_v1_packet_proto_rawDescOnce sync.Once
	file_ibc_applications_transfer_v1_packet_proto_rawDescData []byte
)

func file_ibc_applications_transfer_v1_packet_proto_rawDescGZIP() []byte {
	file_ibc_applications_transfer_v1_packet_proto_rawDescOnce.Do(func() {
		file_ibc_applications_transfer_v1_packet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_packet_proto_rawDesc), len(file_ibc_applications_transfer_v1_packet_proto_rawDesc)))
	})
	return file_ibc_applications_transfer_v1_packet_proto_rawDescData
}

var file_ibc_applications_transfer_v1_packet_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ibc_applications_transfer_v1_packet_proto_goTypes = []any{
	(*FungibleTokenPacketData)(nil), // 0: ibc.applications.transfer.v1.FungibleTokenPacketData
}
var file_ibc_applications_transfer_v1_packet_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ibc_applications_transfer_v1_packet_proto_init() }
func file_ibc_applications_transfer_v1_packet_proto_init() {
	if File_ibc_applications_transfer_v1_packet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_packet_proto_rawDesc), len(file_ibc_applications_transfer_v1_packet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_applications_transfer_v1_packet_proto_goTypes,
		DependencyIndexes: file_ibc_applications_transfer_v1_packet_proto_depIdxs,
		MessageInfos:      file_ibc_applications_transfer_v1_packet_proto_msgTypes,
	}.Build()
	File_ibc_applications_transfer_v1_packet_proto = out.File
	file_ibc_applications_transfer_v1_packet_proto_goTypes = nil
	file_ibc_applications_transfer_v1_packet_proto_depIdxs = nil
}
