// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/applications/transfer/v1/query.proto

package transferv1

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/query/v1beta1"
	v1beta11 "cosmossdk.io/api/cosmos/base/v1beta1"
	_ "github.com/drpcorg/public/pkg/gogoproto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryParamsRequest is the request type for the Query/Params RPC method.
type QueryParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsRequest) Reset() {
	*x = QueryParamsRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsRequest) ProtoMessage() {}

func (x *QueryParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{0}
}

// QueryParamsResponse is the response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines the parameters of the module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParamsResponse) Reset() {
	*x = QueryParamsResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParamsResponse) ProtoMessage() {}

func (x *QueryParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryDenomRequest is the request type for the Query/Denom RPC
// method
type QueryDenomRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash (in hex format) or denom (full denom with ibc prefix) of the on chain denomination.
	Hash          string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomRequest) Reset() {
	*x = QueryDenomRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomRequest) ProtoMessage() {}

func (x *QueryDenomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomRequest.ProtoReflect.Descriptor instead.
func (*QueryDenomRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryDenomRequest) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// QueryDenomResponse is the response type for the Query/Denom RPC
// method.
type QueryDenomResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// denom returns the requested denomination.
	Denom         *Denom `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomResponse) Reset() {
	*x = QueryDenomResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomResponse) ProtoMessage() {}

func (x *QueryDenomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomResponse.ProtoReflect.Descriptor instead.
func (*QueryDenomResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryDenomResponse) GetDenom() *Denom {
	if x != nil {
		return x.Denom
	}
	return nil
}

// QueryDenomsRequest is the request type for the Query/Denoms RPC
// method
type QueryDenomsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination defines an optional pagination for the request.
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomsRequest) Reset() {
	*x = QueryDenomsRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomsRequest) ProtoMessage() {}

func (x *QueryDenomsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomsRequest.ProtoReflect.Descriptor instead.
func (*QueryDenomsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryDenomsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryDenomsResponse is the response type for the Query/Denoms RPC
// method.
type QueryDenomsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// denoms returns all denominations.
	Denoms []*Denom `protobuf:"bytes,1,rep,name=denoms,proto3" json:"denoms,omitempty"`
	// pagination defines the pagination in the response.
	Pagination    *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomsResponse) Reset() {
	*x = QueryDenomsResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomsResponse) ProtoMessage() {}

func (x *QueryDenomsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomsResponse.ProtoReflect.Descriptor instead.
func (*QueryDenomsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryDenomsResponse) GetDenoms() []*Denom {
	if x != nil {
		return x.Denoms
	}
	return nil
}

func (x *QueryDenomsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryDenomHashRequest is the request type for the Query/DenomHash RPC
// method
type QueryDenomHashRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The denomination trace ([port_id]/[channel_id])+/[denom]
	Trace         string `protobuf:"bytes,1,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomHashRequest) Reset() {
	*x = QueryDenomHashRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomHashRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomHashRequest) ProtoMessage() {}

func (x *QueryDenomHashRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomHashRequest.ProtoReflect.Descriptor instead.
func (*QueryDenomHashRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryDenomHashRequest) GetTrace() string {
	if x != nil {
		return x.Trace
	}
	return ""
}

// QueryDenomHashResponse is the response type for the Query/DenomHash RPC
// method.
type QueryDenomHashResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hash (in hex format) of the denomination trace information.
	Hash          string `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryDenomHashResponse) Reset() {
	*x = QueryDenomHashResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryDenomHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryDenomHashResponse) ProtoMessage() {}

func (x *QueryDenomHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryDenomHashResponse.ProtoReflect.Descriptor instead.
func (*QueryDenomHashResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryDenomHashResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

// QueryEscrowAddressRequest is the request type for the EscrowAddress RPC method.
type QueryEscrowAddressRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique port identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// unique channel identifier
	ChannelId     string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEscrowAddressRequest) Reset() {
	*x = QueryEscrowAddressRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEscrowAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEscrowAddressRequest) ProtoMessage() {}

func (x *QueryEscrowAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEscrowAddressRequest.ProtoReflect.Descriptor instead.
func (*QueryEscrowAddressRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryEscrowAddressRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryEscrowAddressRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// QueryEscrowAddressResponse is the response type of the EscrowAddress RPC method.
type QueryEscrowAddressResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// the escrow account address
	EscrowAddress string `protobuf:"bytes,1,opt,name=escrow_address,json=escrowAddress,proto3" json:"escrow_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryEscrowAddressResponse) Reset() {
	*x = QueryEscrowAddressResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryEscrowAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryEscrowAddressResponse) ProtoMessage() {}

func (x *QueryEscrowAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryEscrowAddressResponse.ProtoReflect.Descriptor instead.
func (*QueryEscrowAddressResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryEscrowAddressResponse) GetEscrowAddress() string {
	if x != nil {
		return x.EscrowAddress
	}
	return ""
}

// QueryTotalEscrowForDenomRequest is the request type for TotalEscrowForDenom RPC method.
type QueryTotalEscrowForDenomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Denom         string                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalEscrowForDenomRequest) Reset() {
	*x = QueryTotalEscrowForDenomRequest{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalEscrowForDenomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalEscrowForDenomRequest) ProtoMessage() {}

func (x *QueryTotalEscrowForDenomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalEscrowForDenomRequest.ProtoReflect.Descriptor instead.
func (*QueryTotalEscrowForDenomRequest) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryTotalEscrowForDenomRequest) GetDenom() string {
	if x != nil {
		return x.Denom
	}
	return ""
}

// QueryTotalEscrowForDenomResponse is the response type for TotalEscrowForDenom RPC method.
type QueryTotalEscrowForDenomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        *v1beta11.Coin         `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryTotalEscrowForDenomResponse) Reset() {
	*x = QueryTotalEscrowForDenomResponse{}
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryTotalEscrowForDenomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryTotalEscrowForDenomResponse) ProtoMessage() {}

func (x *QueryTotalEscrowForDenomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryTotalEscrowForDenomResponse.ProtoReflect.Descriptor instead.
func (*QueryTotalEscrowForDenomResponse) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryTotalEscrowForDenomResponse) GetAmount() *v1beta11.Coin {
	if x != nil {
		return x.Amount
	}
	return nil
}

var File_ibc_applications_transfer_v1_query_proto protoreflect.FileDescriptor

const file_ibc_applications_transfer_v1_query_proto_rawDesc = "" +
	"\n" +
	"(ibc/applications/transfer/v1/query.proto\x12\x1cibc.applications.transfer.v1\x1a\x14gogoproto/gogo.proto\x1a\x1ecosmos/base/v1beta1/coin.proto\x1a+ibc/applications/transfer/v1/transfer.proto\x1a(ibc/applications/transfer/v1/token.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1cgoogle/api/annotations.proto\"\x14\n" +
	"\x12QueryParamsRequest\"S\n" +
	"\x13QueryParamsResponse\x12<\n" +
	"\x06params\x18\x01 \x01(\v2$.ibc.applications.transfer.v1.ParamsR\x06params\"'\n" +
	"\x11QueryDenomRequest\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"O\n" +
	"\x12QueryDenomResponse\x129\n" +
	"\x05denom\x18\x01 \x01(\v2#.ibc.applications.transfer.v1.DenomR\x05denom\"\\\n" +
	"\x12QueryDenomsRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xab\x01\n" +
	"\x13QueryDenomsResponse\x12K\n" +
	"\x06denoms\x18\x01 \x03(\v2#.ibc.applications.transfer.v1.DenomB\x0e\xc8\xde\x1f\x00\xaa\xdf\x1f\x06DenomsR\x06denoms\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"-\n" +
	"\x15QueryDenomHashRequest\x12\x14\n" +
	"\x05trace\x18\x01 \x01(\tR\x05trace\",\n" +
	"\x16QueryDenomHashResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"S\n" +
	"\x19QueryEscrowAddressRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"C\n" +
	"\x1aQueryEscrowAddressResponse\x12%\n" +
	"\x0eescrow_address\x18\x01 \x01(\tR\rescrowAddress\"7\n" +
	"\x1fQueryTotalEscrowForDenomRequest\x12\x14\n" +
	"\x05denom\x18\x01 \x01(\tR\x05denom\"[\n" +
	" QueryTotalEscrowForDenomResponse\x127\n" +
	"\x06amount\x18\x01 \x01(\v2\x19.cosmos.base.v1beta1.CoinB\x04\xc8\xde\x1f\x00R\x06amount2\xa7\b\n" +
	"\x05Query\x12\x93\x01\n" +
	"\x06Params\x120.ibc.applications.transfer.v1.QueryParamsRequest\x1a1.ibc.applications.transfer.v1.QueryParamsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/ibc/apps/transfer/v1/params\x12\x93\x01\n" +
	"\x06Denoms\x120.ibc.applications.transfer.v1.QueryDenomsRequest\x1a1.ibc.applications.transfer.v1.QueryDenomsResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/ibc/apps/transfer/v1/denoms\x12\x9a\x01\n" +
	"\x05Denom\x12/.ibc.applications.transfer.v1.QueryDenomRequest\x1a0.ibc.applications.transfer.v1.QueryDenomResponse\".\x82\xd3\xe4\x93\x02(\x12&/ibc/apps/transfer/v1/denoms/{hash=**}\x12\xad\x01\n" +
	"\tDenomHash\x123.ibc.applications.transfer.v1.QueryDenomHashRequest\x1a4.ibc.applications.transfer.v1.QueryDenomHashResponse\"5\x82\xd3\xe4\x93\x02/\x12-/ibc/apps/transfer/v1/denom_hashes/{trace=**}\x12\xd6\x01\n" +
	"\rEscrowAddress\x127.ibc.applications.transfer.v1.QueryEscrowAddressRequest\x1a8.ibc.applications.transfer.v1.QueryEscrowAddressResponse\"R\x82\xd3\xe4\x93\x02L\x12J/ibc/apps/transfer/v1/channels/{channel_id}/ports/{port_id}/escrow_address\x12\xcb\x01\n" +
	"\x13TotalEscrowForDenom\x12=.ibc.applications.transfer.v1.QueryTotalEscrowForDenomRequest\x1a>.ibc.applications.transfer.v1.QueryTotalEscrowForDenomResponse\"5\x82\xd3\xe4\x93\x02/\x12-/ibc/apps/transfer/v1/total_escrow/{denom=**}B\x88\x02\n" +
	" com.ibc.applications.transfer.v1B\n" +
	"QueryProtoP\x01ZEgithub.com/drpcorg/public/pkg/ibc/applications/transfer/v1;transferv1\xa2\x02\x03IAT\xaa\x02\x1cIbc.Applications.Transfer.V1\xca\x02\x1cIbc\\Applications\\Transfer\\V1\xe2\x02(Ibc\\Applications\\Transfer\\V1\\GPBMetadata\xea\x02\x1fIbc::Applications::Transfer::V1b\x06proto3"

var (
	file_ibc_applications_transfer_v1_query_proto_rawDescOnce sync.Once
	file_ibc_applications_transfer_v1_query_proto_rawDescData []byte
)

func file_ibc_applications_transfer_v1_query_proto_rawDescGZIP() []byte {
	file_ibc_applications_transfer_v1_query_proto_rawDescOnce.Do(func() {
		file_ibc_applications_transfer_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_query_proto_rawDesc), len(file_ibc_applications_transfer_v1_query_proto_rawDesc)))
	})
	return file_ibc_applications_transfer_v1_query_proto_rawDescData
}

var file_ibc_applications_transfer_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ibc_applications_transfer_v1_query_proto_goTypes = []any{
	(*QueryParamsRequest)(nil),               // 0: ibc.applications.transfer.v1.QueryParamsRequest
	(*QueryParamsResponse)(nil),              // 1: ibc.applications.transfer.v1.QueryParamsResponse
	(*QueryDenomRequest)(nil),                // 2: ibc.applications.transfer.v1.QueryDenomRequest
	(*QueryDenomResponse)(nil),               // 3: ibc.applications.transfer.v1.QueryDenomResponse
	(*QueryDenomsRequest)(nil),               // 4: ibc.applications.transfer.v1.QueryDenomsRequest
	(*QueryDenomsResponse)(nil),              // 5: ibc.applications.transfer.v1.QueryDenomsResponse
	(*QueryDenomHashRequest)(nil),            // 6: ibc.applications.transfer.v1.QueryDenomHashRequest
	(*QueryDenomHashResponse)(nil),           // 7: ibc.applications.transfer.v1.QueryDenomHashResponse
	(*QueryEscrowAddressRequest)(nil),        // 8: ibc.applications.transfer.v1.QueryEscrowAddressRequest
	(*QueryEscrowAddressResponse)(nil),       // 9: ibc.applications.transfer.v1.QueryEscrowAddressResponse
	(*QueryTotalEscrowForDenomRequest)(nil),  // 10: ibc.applications.transfer.v1.QueryTotalEscrowForDenomRequest
	(*QueryTotalEscrowForDenomResponse)(nil), // 11: ibc.applications.transfer.v1.QueryTotalEscrowForDenomResponse
	(*Params)(nil),                           // 12: ibc.applications.transfer.v1.Params
	(*Denom)(nil),                            // 13: ibc.applications.transfer.v1.Denom
	(*v1beta1.PageRequest)(nil),              // 14: cosmos.base.query.v1beta1.PageRequest
	(*v1beta1.PageResponse)(nil),             // 15: cosmos.base.query.v1beta1.PageResponse
	(*v1beta11.Coin)(nil),                    // 16: cosmos.base.v1beta1.Coin
}
var file_ibc_applications_transfer_v1_query_proto_depIdxs = []int32{
	12, // 0: ibc.applications.transfer.v1.QueryParamsResponse.params:type_name -> ibc.applications.transfer.v1.Params
	13, // 1: ibc.applications.transfer.v1.QueryDenomResponse.denom:type_name -> ibc.applications.transfer.v1.Denom
	14, // 2: ibc.applications.transfer.v1.QueryDenomsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	13, // 3: ibc.applications.transfer.v1.QueryDenomsResponse.denoms:type_name -> ibc.applications.transfer.v1.Denom
	15, // 4: ibc.applications.transfer.v1.QueryDenomsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	16, // 5: ibc.applications.transfer.v1.QueryTotalEscrowForDenomResponse.amount:type_name -> cosmos.base.v1beta1.Coin
	0,  // 6: ibc.applications.transfer.v1.Query.Params:input_type -> ibc.applications.transfer.v1.QueryParamsRequest
	4,  // 7: ibc.applications.transfer.v1.Query.Denoms:input_type -> ibc.applications.transfer.v1.QueryDenomsRequest
	2,  // 8: ibc.applications.transfer.v1.Query.Denom:input_type -> ibc.applications.transfer.v1.QueryDenomRequest
	6,  // 9: ibc.applications.transfer.v1.Query.DenomHash:input_type -> ibc.applications.transfer.v1.QueryDenomHashRequest
	8,  // 10: ibc.applications.transfer.v1.Query.EscrowAddress:input_type -> ibc.applications.transfer.v1.QueryEscrowAddressRequest
	10, // 11: ibc.applications.transfer.v1.Query.TotalEscrowForDenom:input_type -> ibc.applications.transfer.v1.QueryTotalEscrowForDenomRequest
	1,  // 12: ibc.applications.transfer.v1.Query.Params:output_type -> ibc.applications.transfer.v1.QueryParamsResponse
	5,  // 13: ibc.applications.transfer.v1.Query.Denoms:output_type -> ibc.applications.transfer.v1.QueryDenomsResponse
	3,  // 14: ibc.applications.transfer.v1.Query.Denom:output_type -> ibc.applications.transfer.v1.QueryDenomResponse
	7,  // 15: ibc.applications.transfer.v1.Query.DenomHash:output_type -> ibc.applications.transfer.v1.QueryDenomHashResponse
	9,  // 16: ibc.applications.transfer.v1.Query.EscrowAddress:output_type -> ibc.applications.transfer.v1.QueryEscrowAddressResponse
	11, // 17: ibc.applications.transfer.v1.Query.TotalEscrowForDenom:output_type -> ibc.applications.transfer.v1.QueryTotalEscrowForDenomResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_ibc_applications_transfer_v1_query_proto_init() }
func file_ibc_applications_transfer_v1_query_proto_init() {
	if File_ibc_applications_transfer_v1_query_proto != nil {
		return
	}
	file_ibc_applications_transfer_v1_transfer_proto_init()
	file_ibc_applications_transfer_v1_token_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_query_proto_rawDesc), len(file_ibc_applications_transfer_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ibc_applications_transfer_v1_query_proto_goTypes,
		DependencyIndexes: file_ibc_applications_transfer_v1_query_proto_depIdxs,
		MessageInfos:      file_ibc_applications_transfer_v1_query_proto_msgTypes,
	}.Build()
	File_ibc_applications_transfer_v1_query_proto = out.File
	file_ibc_applications_transfer_v1_query_proto_goTypes = nil
	file_ibc_applications_transfer_v1_query_proto_depIdxs = nil
}
