// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/applications/transfer/v1/transfer.proto

package transferv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Params defines the set of IBC transfer parameters.
// NOTE: To prevent a single token from being transferred, set the
// TransfersEnabled parameter to true and then set the bank module's SendEnabled
// parameter for the denomination to false.
type Params struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// send_enabled enables or disables all cross-chain token transfers from this
	// chain.
	SendEnabled bool `protobuf:"varint,1,opt,name=send_enabled,json=sendEnabled,proto3" json:"send_enabled,omitempty"`
	// receive_enabled enables or disables all cross-chain token transfers to this
	// chain.
	ReceiveEnabled bool `protobuf:"varint,2,opt,name=receive_enabled,json=receiveEnabled,proto3" json:"receive_enabled,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Params) Reset() {
	*x = Params{}
	mi := &file_ibc_applications_transfer_v1_transfer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Params) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Params) ProtoMessage() {}

func (x *Params) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_applications_transfer_v1_transfer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Params.ProtoReflect.Descriptor instead.
func (*Params) Descriptor() ([]byte, []int) {
	return file_ibc_applications_transfer_v1_transfer_proto_rawDescGZIP(), []int{0}
}

func (x *Params) GetSendEnabled() bool {
	if x != nil {
		return x.SendEnabled
	}
	return false
}

func (x *Params) GetReceiveEnabled() bool {
	if x != nil {
		return x.ReceiveEnabled
	}
	return false
}

var File_ibc_applications_transfer_v1_transfer_proto protoreflect.FileDescriptor

const file_ibc_applications_transfer_v1_transfer_proto_rawDesc = "" +
	"\n" +
	"+ibc/applications/transfer/v1/transfer.proto\x12\x1cibc.applications.transfer.v1\"T\n" +
	"\x06Params\x12!\n" +
	"\fsend_enabled\x18\x01 \x01(\bR\vsendEnabled\x12'\n" +
	"\x0freceive_enabled\x18\x02 \x01(\bR\x0ereceiveEnabledB\x8b\x02\n" +
	" com.ibc.applications.transfer.v1B\rTransferProtoP\x01ZEgithub.com/drpcorg/public/pkg/ibc/applications/transfer/v1;transferv1\xa2\x02\x03IAT\xaa\x02\x1cIbc.Applications.Transfer.V1\xca\x02\x1cIbc\\Applications\\Transfer\\V1\xe2\x02(Ibc\\Applications\\Transfer\\V1\\GPBMetadata\xea\x02\x1fIbc::Applications::Transfer::V1b\x06proto3"

var (
	file_ibc_applications_transfer_v1_transfer_proto_rawDescOnce sync.Once
	file_ibc_applications_transfer_v1_transfer_proto_rawDescData []byte
)

func file_ibc_applications_transfer_v1_transfer_proto_rawDescGZIP() []byte {
	file_ibc_applications_transfer_v1_transfer_proto_rawDescOnce.Do(func() {
		file_ibc_applications_transfer_v1_transfer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_transfer_proto_rawDesc), len(file_ibc_applications_transfer_v1_transfer_proto_rawDesc)))
	})
	return file_ibc_applications_transfer_v1_transfer_proto_rawDescData
}

var file_ibc_applications_transfer_v1_transfer_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ibc_applications_transfer_v1_transfer_proto_goTypes = []any{
	(*Params)(nil), // 0: ibc.applications.transfer.v1.Params
}
var file_ibc_applications_transfer_v1_transfer_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ibc_applications_transfer_v1_transfer_proto_init() }
func file_ibc_applications_transfer_v1_transfer_proto_init() {
	if File_ibc_applications_transfer_v1_transfer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_applications_transfer_v1_transfer_proto_rawDesc), len(file_ibc_applications_transfer_v1_transfer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_applications_transfer_v1_transfer_proto_goTypes,
		DependencyIndexes: file_ibc_applications_transfer_v1_transfer_proto_depIdxs,
		MessageInfos:      file_ibc_applications_transfer_v1_transfer_proto_msgTypes,
	}.Build()
	File_ibc_applications_transfer_v1_transfer_proto = out.File
	file_ibc_applications_transfer_v1_transfer_proto_goTypes = nil
	file_ibc_applications_transfer_v1_transfer_proto_depIdxs = nil
}
