// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/core/channel/v1/query.proto

package channelv1

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/query/v1beta1"
	_ "github.com/cosmos/gogoproto/gogoproto"
	v1 "github.com/drpcorg/public/pkg/ibc/core/client/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryChannelRequest is the request type for the Query/Channel RPC method
type QueryChannelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId     string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelRequest) Reset() {
	*x = QueryChannelRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelRequest) ProtoMessage() {}

func (x *QueryChannelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelRequest.ProtoReflect.Descriptor instead.
func (*QueryChannelRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryChannelRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryChannelRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// QueryChannelResponse is the response type for the Query/Channel RPC method.
// Besides the Channel end, it includes a proof and the height from which the
// proof was retrieved.
type QueryChannelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// channel associated with the request identifiers
	Channel *Channel `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelResponse) Reset() {
	*x = QueryChannelResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelResponse) ProtoMessage() {}

func (x *QueryChannelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelResponse.ProtoReflect.Descriptor instead.
func (*QueryChannelResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryChannelResponse) GetChannel() *Channel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *QueryChannelResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryChannelResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryChannelsRequest is the request type for the Query/Channels RPC method
type QueryChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelsRequest) Reset() {
	*x = QueryChannelsRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelsRequest) ProtoMessage() {}

func (x *QueryChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelsRequest.ProtoReflect.Descriptor instead.
func (*QueryChannelsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryChannelsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryChannelsResponse is the response type for the Query/Channels RPC method.
type QueryChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of stored channels of the chain.
	Channels []*IdentifiedChannel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	// pagination response
	Pagination *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelsResponse) Reset() {
	*x = QueryChannelsResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelsResponse) ProtoMessage() {}

func (x *QueryChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelsResponse.ProtoReflect.Descriptor instead.
func (*QueryChannelsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryChannelsResponse) GetChannels() []*IdentifiedChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *QueryChannelsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryChannelsResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryConnectionChannelsRequest is the request type for the
// Query/QueryConnectionChannels RPC method
type QueryConnectionChannelsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection unique identifier
	Connection string `protobuf:"bytes,1,opt,name=connection,proto3" json:"connection,omitempty"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConnectionChannelsRequest) Reset() {
	*x = QueryConnectionChannelsRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConnectionChannelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConnectionChannelsRequest) ProtoMessage() {}

func (x *QueryConnectionChannelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConnectionChannelsRequest.ProtoReflect.Descriptor instead.
func (*QueryConnectionChannelsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryConnectionChannelsRequest) GetConnection() string {
	if x != nil {
		return x.Connection
	}
	return ""
}

func (x *QueryConnectionChannelsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryConnectionChannelsResponse is the Response type for the
// Query/QueryConnectionChannels RPC method
type QueryConnectionChannelsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of channels associated with a connection.
	Channels []*IdentifiedChannel `protobuf:"bytes,1,rep,name=channels,proto3" json:"channels,omitempty"`
	// pagination response
	Pagination *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConnectionChannelsResponse) Reset() {
	*x = QueryConnectionChannelsResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConnectionChannelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConnectionChannelsResponse) ProtoMessage() {}

func (x *QueryConnectionChannelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConnectionChannelsResponse.ProtoReflect.Descriptor instead.
func (*QueryConnectionChannelsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryConnectionChannelsResponse) GetChannels() []*IdentifiedChannel {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *QueryConnectionChannelsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryConnectionChannelsResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryChannelClientStateRequest is the request type for the Query/ClientState
// RPC method
type QueryChannelClientStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId     string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelClientStateRequest) Reset() {
	*x = QueryChannelClientStateRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelClientStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelClientStateRequest) ProtoMessage() {}

func (x *QueryChannelClientStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelClientStateRequest.ProtoReflect.Descriptor instead.
func (*QueryChannelClientStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryChannelClientStateRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryChannelClientStateRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// QueryChannelClientStateResponse is the Response type for the
// Query/QueryChannelClientState RPC method
type QueryChannelClientStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client state associated with the channel
	IdentifiedClientState *v1.IdentifiedClientState `protobuf:"bytes,1,opt,name=identified_client_state,json=identifiedClientState,proto3" json:"identified_client_state,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelClientStateResponse) Reset() {
	*x = QueryChannelClientStateResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelClientStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelClientStateResponse) ProtoMessage() {}

func (x *QueryChannelClientStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelClientStateResponse.ProtoReflect.Descriptor instead.
func (*QueryChannelClientStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryChannelClientStateResponse) GetIdentifiedClientState() *v1.IdentifiedClientState {
	if x != nil {
		return x.IdentifiedClientState
	}
	return nil
}

func (x *QueryChannelClientStateResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryChannelClientStateResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryChannelConsensusStateRequest is the request type for the
// Query/ConsensusState RPC method
type QueryChannelConsensusStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// revision number of the consensus state
	RevisionNumber uint64 `protobuf:"varint,3,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// revision height of the consensus state
	RevisionHeight uint64 `protobuf:"varint,4,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *QueryChannelConsensusStateRequest) Reset() {
	*x = QueryChannelConsensusStateRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelConsensusStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelConsensusStateRequest) ProtoMessage() {}

func (x *QueryChannelConsensusStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelConsensusStateRequest.ProtoReflect.Descriptor instead.
func (*QueryChannelConsensusStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryChannelConsensusStateRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryChannelConsensusStateRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryChannelConsensusStateRequest) GetRevisionNumber() uint64 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *QueryChannelConsensusStateRequest) GetRevisionHeight() uint64 {
	if x != nil {
		return x.RevisionHeight
	}
	return 0
}

// QueryChannelClientStateResponse is the Response type for the
// Query/QueryChannelClientState RPC method
type QueryChannelConsensusStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consensus state associated with the channel
	ConsensusState *anypb.Any `protobuf:"bytes,1,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	// client ID associated with the consensus state
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,4,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryChannelConsensusStateResponse) Reset() {
	*x = QueryChannelConsensusStateResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryChannelConsensusStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryChannelConsensusStateResponse) ProtoMessage() {}

func (x *QueryChannelConsensusStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryChannelConsensusStateResponse.ProtoReflect.Descriptor instead.
func (*QueryChannelConsensusStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryChannelConsensusStateResponse) GetConsensusState() *anypb.Any {
	if x != nil {
		return x.ConsensusState
	}
	return nil
}

func (x *QueryChannelConsensusStateResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryChannelConsensusStateResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryChannelConsensusStateResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryPacketCommitmentRequest is the request type for the
// Query/PacketCommitment RPC method
type QueryPacketCommitmentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// packet sequence
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketCommitmentRequest) Reset() {
	*x = QueryPacketCommitmentRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketCommitmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketCommitmentRequest) ProtoMessage() {}

func (x *QueryPacketCommitmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketCommitmentRequest.ProtoReflect.Descriptor instead.
func (*QueryPacketCommitmentRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryPacketCommitmentRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryPacketCommitmentRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPacketCommitmentRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// QueryPacketCommitmentResponse defines the client query response for a packet
// which also includes a proof and the height from which the proof was
// retrieved
type QueryPacketCommitmentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// packet associated with the request fields
	Commitment []byte `protobuf:"bytes,1,opt,name=commitment,proto3" json:"commitment,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketCommitmentResponse) Reset() {
	*x = QueryPacketCommitmentResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketCommitmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketCommitmentResponse) ProtoMessage() {}

func (x *QueryPacketCommitmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketCommitmentResponse.ProtoReflect.Descriptor instead.
func (*QueryPacketCommitmentResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryPacketCommitmentResponse) GetCommitment() []byte {
	if x != nil {
		return x.Commitment
	}
	return nil
}

func (x *QueryPacketCommitmentResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryPacketCommitmentResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryPacketCommitmentsRequest is the request type for the
// Query/QueryPacketCommitments RPC method
type QueryPacketCommitmentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketCommitmentsRequest) Reset() {
	*x = QueryPacketCommitmentsRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketCommitmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketCommitmentsRequest) ProtoMessage() {}

func (x *QueryPacketCommitmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketCommitmentsRequest.ProtoReflect.Descriptor instead.
func (*QueryPacketCommitmentsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{12}
}

func (x *QueryPacketCommitmentsRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryPacketCommitmentsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPacketCommitmentsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryPacketCommitmentsResponse is the request type for the
// Query/QueryPacketCommitments RPC method
type QueryPacketCommitmentsResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Commitments []*PacketState         `protobuf:"bytes,1,rep,name=commitments,proto3" json:"commitments,omitempty"`
	// pagination response
	Pagination *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketCommitmentsResponse) Reset() {
	*x = QueryPacketCommitmentsResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketCommitmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketCommitmentsResponse) ProtoMessage() {}

func (x *QueryPacketCommitmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketCommitmentsResponse.ProtoReflect.Descriptor instead.
func (*QueryPacketCommitmentsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryPacketCommitmentsResponse) GetCommitments() []*PacketState {
	if x != nil {
		return x.Commitments
	}
	return nil
}

func (x *QueryPacketCommitmentsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryPacketCommitmentsResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryPacketReceiptRequest is the request type for the
// Query/PacketReceipt RPC method
type QueryPacketReceiptRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// packet sequence
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketReceiptRequest) Reset() {
	*x = QueryPacketReceiptRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketReceiptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketReceiptRequest) ProtoMessage() {}

func (x *QueryPacketReceiptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketReceiptRequest.ProtoReflect.Descriptor instead.
func (*QueryPacketReceiptRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryPacketReceiptRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryPacketReceiptRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPacketReceiptRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// QueryPacketReceiptResponse defines the client query response for a packet
// receipt which also includes a proof, and the height from which the proof was
// retrieved
type QueryPacketReceiptResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success flag for if receipt exists
	Received bool `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,4,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketReceiptResponse) Reset() {
	*x = QueryPacketReceiptResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketReceiptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketReceiptResponse) ProtoMessage() {}

func (x *QueryPacketReceiptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketReceiptResponse.ProtoReflect.Descriptor instead.
func (*QueryPacketReceiptResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryPacketReceiptResponse) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *QueryPacketReceiptResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryPacketReceiptResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryPacketAcknowledgementRequest is the request type for the
// Query/PacketAcknowledgement RPC method
type QueryPacketAcknowledgementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// packet sequence
	Sequence      uint64 `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketAcknowledgementRequest) Reset() {
	*x = QueryPacketAcknowledgementRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketAcknowledgementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketAcknowledgementRequest) ProtoMessage() {}

func (x *QueryPacketAcknowledgementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketAcknowledgementRequest.ProtoReflect.Descriptor instead.
func (*QueryPacketAcknowledgementRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{16}
}

func (x *QueryPacketAcknowledgementRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryPacketAcknowledgementRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPacketAcknowledgementRequest) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// QueryPacketAcknowledgementResponse defines the client query response for a
// packet which also includes a proof and the height from which the
// proof was retrieved
type QueryPacketAcknowledgementResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// packet associated with the request fields
	Acknowledgement []byte `protobuf:"bytes,1,opt,name=acknowledgement,proto3" json:"acknowledgement,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketAcknowledgementResponse) Reset() {
	*x = QueryPacketAcknowledgementResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketAcknowledgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketAcknowledgementResponse) ProtoMessage() {}

func (x *QueryPacketAcknowledgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketAcknowledgementResponse.ProtoReflect.Descriptor instead.
func (*QueryPacketAcknowledgementResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryPacketAcknowledgementResponse) GetAcknowledgement() []byte {
	if x != nil {
		return x.Acknowledgement
	}
	return nil
}

func (x *QueryPacketAcknowledgementResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryPacketAcknowledgementResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryPacketAcknowledgementsRequest is the request type for the
// Query/QueryPacketCommitments RPC method
type QueryPacketAcknowledgementsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// pagination request
	Pagination *v1beta1.PageRequest `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// list of packet sequences
	PacketCommitmentSequences []uint64 `protobuf:"varint,4,rep,packed,name=packet_commitment_sequences,json=packetCommitmentSequences,proto3" json:"packet_commitment_sequences,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *QueryPacketAcknowledgementsRequest) Reset() {
	*x = QueryPacketAcknowledgementsRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketAcknowledgementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketAcknowledgementsRequest) ProtoMessage() {}

func (x *QueryPacketAcknowledgementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketAcknowledgementsRequest.ProtoReflect.Descriptor instead.
func (*QueryPacketAcknowledgementsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{18}
}

func (x *QueryPacketAcknowledgementsRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryPacketAcknowledgementsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryPacketAcknowledgementsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryPacketAcknowledgementsRequest) GetPacketCommitmentSequences() []uint64 {
	if x != nil {
		return x.PacketCommitmentSequences
	}
	return nil
}

// QueryPacketAcknowledgemetsResponse is the request type for the
// Query/QueryPacketAcknowledgements RPC method
type QueryPacketAcknowledgementsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Acknowledgements []*PacketState         `protobuf:"bytes,1,rep,name=acknowledgements,proto3" json:"acknowledgements,omitempty"`
	// pagination response
	Pagination *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPacketAcknowledgementsResponse) Reset() {
	*x = QueryPacketAcknowledgementsResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPacketAcknowledgementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPacketAcknowledgementsResponse) ProtoMessage() {}

func (x *QueryPacketAcknowledgementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPacketAcknowledgementsResponse.ProtoReflect.Descriptor instead.
func (*QueryPacketAcknowledgementsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryPacketAcknowledgementsResponse) GetAcknowledgements() []*PacketState {
	if x != nil {
		return x.Acknowledgements
	}
	return nil
}

func (x *QueryPacketAcknowledgementsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *QueryPacketAcknowledgementsResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryUnreceivedPacketsRequest is the request type for the
// Query/UnreceivedPackets RPC method
type QueryUnreceivedPacketsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// list of packet sequences
	PacketCommitmentSequences []uint64 `protobuf:"varint,3,rep,packed,name=packet_commitment_sequences,json=packetCommitmentSequences,proto3" json:"packet_commitment_sequences,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *QueryUnreceivedPacketsRequest) Reset() {
	*x = QueryUnreceivedPacketsRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnreceivedPacketsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnreceivedPacketsRequest) ProtoMessage() {}

func (x *QueryUnreceivedPacketsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnreceivedPacketsRequest.ProtoReflect.Descriptor instead.
func (*QueryUnreceivedPacketsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{20}
}

func (x *QueryUnreceivedPacketsRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryUnreceivedPacketsRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryUnreceivedPacketsRequest) GetPacketCommitmentSequences() []uint64 {
	if x != nil {
		return x.PacketCommitmentSequences
	}
	return nil
}

// QueryUnreceivedPacketsResponse is the response type for the
// Query/UnreceivedPacketCommitments RPC method
type QueryUnreceivedPacketsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of unreceived packet sequences
	Sequences []uint64 `protobuf:"varint,1,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnreceivedPacketsResponse) Reset() {
	*x = QueryUnreceivedPacketsResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnreceivedPacketsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnreceivedPacketsResponse) ProtoMessage() {}

func (x *QueryUnreceivedPacketsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnreceivedPacketsResponse.ProtoReflect.Descriptor instead.
func (*QueryUnreceivedPacketsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *QueryUnreceivedPacketsResponse) GetSequences() []uint64 {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *QueryUnreceivedPacketsResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryUnreceivedAcks is the request type for the
// Query/UnreceivedAcks RPC method
type QueryUnreceivedAcksRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// list of acknowledgement sequences
	PacketAckSequences []uint64 `protobuf:"varint,3,rep,packed,name=packet_ack_sequences,json=packetAckSequences,proto3" json:"packet_ack_sequences,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *QueryUnreceivedAcksRequest) Reset() {
	*x = QueryUnreceivedAcksRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnreceivedAcksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnreceivedAcksRequest) ProtoMessage() {}

func (x *QueryUnreceivedAcksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnreceivedAcksRequest.ProtoReflect.Descriptor instead.
func (*QueryUnreceivedAcksRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{22}
}

func (x *QueryUnreceivedAcksRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryUnreceivedAcksRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *QueryUnreceivedAcksRequest) GetPacketAckSequences() []uint64 {
	if x != nil {
		return x.PacketAckSequences
	}
	return nil
}

// QueryUnreceivedAcksResponse is the response type for the
// Query/UnreceivedAcks RPC method
type QueryUnreceivedAcksResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of unreceived acknowledgement sequences
	Sequences []uint64 `protobuf:"varint,1,rep,packed,name=sequences,proto3" json:"sequences,omitempty"`
	// query block height
	Height        *v1.Height `protobuf:"bytes,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUnreceivedAcksResponse) Reset() {
	*x = QueryUnreceivedAcksResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUnreceivedAcksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUnreceivedAcksResponse) ProtoMessage() {}

func (x *QueryUnreceivedAcksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUnreceivedAcksResponse.ProtoReflect.Descriptor instead.
func (*QueryUnreceivedAcksResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{23}
}

func (x *QueryUnreceivedAcksResponse) GetSequences() []uint64 {
	if x != nil {
		return x.Sequences
	}
	return nil
}

func (x *QueryUnreceivedAcksResponse) GetHeight() *v1.Height {
	if x != nil {
		return x.Height
	}
	return nil
}

// QueryNextSequenceReceiveRequest is the request type for the
// Query/QueryNextSequenceReceiveRequest RPC method
type QueryNextSequenceReceiveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId     string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNextSequenceReceiveRequest) Reset() {
	*x = QueryNextSequenceReceiveRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNextSequenceReceiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNextSequenceReceiveRequest) ProtoMessage() {}

func (x *QueryNextSequenceReceiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNextSequenceReceiveRequest.ProtoReflect.Descriptor instead.
func (*QueryNextSequenceReceiveRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{24}
}

func (x *QueryNextSequenceReceiveRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryNextSequenceReceiveRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// QuerySequenceResponse is the response type for the
// Query/QueryNextSequenceReceiveResponse RPC method
type QueryNextSequenceReceiveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// next sequence receive number
	NextSequenceReceive uint64 `protobuf:"varint,1,opt,name=next_sequence_receive,json=nextSequenceReceive,proto3" json:"next_sequence_receive,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNextSequenceReceiveResponse) Reset() {
	*x = QueryNextSequenceReceiveResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNextSequenceReceiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNextSequenceReceiveResponse) ProtoMessage() {}

func (x *QueryNextSequenceReceiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNextSequenceReceiveResponse.ProtoReflect.Descriptor instead.
func (*QueryNextSequenceReceiveResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{25}
}

func (x *QueryNextSequenceReceiveResponse) GetNextSequenceReceive() uint64 {
	if x != nil {
		return x.NextSequenceReceive
	}
	return 0
}

func (x *QueryNextSequenceReceiveResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryNextSequenceReceiveResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryNextSequenceSendRequest is the request type for the
// Query/QueryNextSequenceSend RPC method
type QueryNextSequenceSendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// port unique identifier
	PortId string `protobuf:"bytes,1,opt,name=port_id,json=portId,proto3" json:"port_id,omitempty"`
	// channel unique identifier
	ChannelId     string `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNextSequenceSendRequest) Reset() {
	*x = QueryNextSequenceSendRequest{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNextSequenceSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNextSequenceSendRequest) ProtoMessage() {}

func (x *QueryNextSequenceSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNextSequenceSendRequest.ProtoReflect.Descriptor instead.
func (*QueryNextSequenceSendRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{26}
}

func (x *QueryNextSequenceSendRequest) GetPortId() string {
	if x != nil {
		return x.PortId
	}
	return ""
}

func (x *QueryNextSequenceSendRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

// QueryNextSequenceSendResponse is the request type for the
// Query/QueryNextSequenceSend RPC method
type QueryNextSequenceSendResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// next sequence send number
	NextSequenceSend uint64 `protobuf:"varint,1,opt,name=next_sequence_send,json=nextSequenceSend,proto3" json:"next_sequence_send,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *v1.Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNextSequenceSendResponse) Reset() {
	*x = QueryNextSequenceSendResponse{}
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNextSequenceSendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNextSequenceSendResponse) ProtoMessage() {}

func (x *QueryNextSequenceSendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_channel_v1_query_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNextSequenceSendResponse.ProtoReflect.Descriptor instead.
func (*QueryNextSequenceSendResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_channel_v1_query_proto_rawDescGZIP(), []int{27}
}

func (x *QueryNextSequenceSendResponse) GetNextSequenceSend() uint64 {
	if x != nil {
		return x.NextSequenceSend
	}
	return 0
}

func (x *QueryNextSequenceSendResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryNextSequenceSendResponse) GetProofHeight() *v1.Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

var File_ibc_core_channel_v1_query_proto protoreflect.FileDescriptor

const file_ibc_core_channel_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1fibc/core/channel/v1/query.proto\x12\x13ibc.core.channel.v1\x1a\x1fibc/core/client/v1/client.proto\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a!ibc/core/channel/v1/channel.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/protobuf/any.proto\x1a\x14gogoproto/gogo.proto\"M\n" +
	"\x13QueryChannelRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xa9\x01\n" +
	"\x14QueryChannelResponse\x126\n" +
	"\achannel\x18\x01 \x01(\v2\x1c.ibc.core.channel.v1.ChannelR\achannel\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"^\n" +
	"\x14QueryChannelsRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xde\x01\n" +
	"\x15QueryChannelsResponse\x12B\n" +
	"\bchannels\x18\x01 \x03(\v2&.ibc.core.channel.v1.IdentifiedChannelR\bchannels\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\x128\n" +
	"\x06height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"\x88\x01\n" +
	"\x1eQueryConnectionChannelsRequest\x12\x1e\n" +
	"\n" +
	"connection\x18\x01 \x01(\tR\n" +
	"connection\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xe8\x01\n" +
	"\x1fQueryConnectionChannelsResponse\x12B\n" +
	"\bchannels\x18\x01 \x03(\v2&.ibc.core.channel.v1.IdentifiedChannelR\bchannels\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\x128\n" +
	"\x06height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"X\n" +
	"\x1eQueryChannelClientStateRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xdf\x01\n" +
	"\x1fQueryChannelClientStateResponse\x12a\n" +
	"\x17identified_client_state\x18\x01 \x01(\v2).ibc.core.client.v1.IdentifiedClientStateR\x15identifiedClientState\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"\xad\x01\n" +
	"!QueryChannelConsensusStateRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12'\n" +
	"\x0frevision_number\x18\x03 \x01(\x04R\x0erevisionNumber\x12'\n" +
	"\x0frevision_height\x18\x04 \x01(\x04R\x0erevisionHeight\"\xdb\x01\n" +
	"\"QueryChannelConsensusStateResponse\x12=\n" +
	"\x0fconsensus_state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x0econsensusState\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x04 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"r\n" +
	"\x1cQueryPacketCommitmentRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\x9a\x01\n" +
	"\x1dQueryPacketCommitmentResponse\x12\x1e\n" +
	"\n" +
	"commitment\x18\x01 \x01(\fR\n" +
	"commitment\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"\x9f\x01\n" +
	"\x1dQueryPacketCommitmentsRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12F\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xe7\x01\n" +
	"\x1eQueryPacketCommitmentsResponse\x12B\n" +
	"\vcommitments\x18\x01 \x03(\v2 .ibc.core.channel.v1.PacketStateR\vcommitments\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\x128\n" +
	"\x06height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"o\n" +
	"\x19QueryPacketReceiptRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\x93\x01\n" +
	"\x1aQueryPacketReceiptResponse\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\bR\breceived\x12\x14\n" +
	"\x05proof\x18\x03 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x04 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"w\n" +
	"!QueryPacketAcknowledgementRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x04R\bsequence\"\xa9\x01\n" +
	"\"QueryPacketAcknowledgementResponse\x12(\n" +
	"\x0facknowledgement\x18\x01 \x01(\fR\x0facknowledgement\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"\xe4\x01\n" +
	"\"QueryPacketAcknowledgementsRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12F\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\x12>\n" +
	"\x1bpacket_commitment_sequences\x18\x04 \x03(\x04R\x19packetCommitmentSequences\"\xf6\x01\n" +
	"#QueryPacketAcknowledgementsResponse\x12L\n" +
	"\x10acknowledgements\x18\x01 \x03(\v2 .ibc.core.channel.v1.PacketStateR\x10acknowledgements\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\x128\n" +
	"\x06height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"\x97\x01\n" +
	"\x1dQueryUnreceivedPacketsRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12>\n" +
	"\x1bpacket_commitment_sequences\x18\x03 \x03(\x04R\x19packetCommitmentSequences\"x\n" +
	"\x1eQueryUnreceivedPacketsResponse\x12\x1c\n" +
	"\tsequences\x18\x01 \x03(\x04R\tsequences\x128\n" +
	"\x06height\x18\x02 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"\x86\x01\n" +
	"\x1aQueryUnreceivedAcksRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x120\n" +
	"\x14packet_ack_sequences\x18\x03 \x03(\x04R\x12packetAckSequences\"u\n" +
	"\x1bQueryUnreceivedAcksResponse\x12\x1c\n" +
	"\tsequences\x18\x01 \x03(\x04R\tsequences\x128\n" +
	"\x06height\x18\x02 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x06height\"Y\n" +
	"\x1fQueryNextSequenceReceiveRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xb1\x01\n" +
	" QueryNextSequenceReceiveResponse\x122\n" +
	"\x15next_sequence_receive\x18\x01 \x01(\x04R\x13nextSequenceReceive\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"V\n" +
	"\x1cQueryNextSequenceSendRequest\x12\x17\n" +
	"\aport_id\x18\x01 \x01(\tR\x06portId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\"\xa8\x01\n" +
	"\x1dQueryNextSequenceSendResponse\x12,\n" +
	"\x12next_sequence_send\x18\x01 \x01(\x04R\x10nextSequenceSend\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight2\xde\x17\n" +
	"\x05Query\x12\xa2\x01\n" +
	"\aChannel\x12(.ibc.core.channel.v1.QueryChannelRequest\x1a).ibc.core.channel.v1.QueryChannelResponse\"B\x82\xd3\xe4\x93\x02<\x12:/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}\x12\x88\x01\n" +
	"\bChannels\x12).ibc.core.channel.v1.QueryChannelsRequest\x1a*.ibc.core.channel.v1.QueryChannelsResponse\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/ibc/core/channel/v1/channels\x12\xbf\x01\n" +
	"\x12ConnectionChannels\x123.ibc.core.channel.v1.QueryConnectionChannelsRequest\x1a4.ibc.core.channel.v1.QueryConnectionChannelsResponse\">\x82\xd3\xe4\x93\x028\x126/ibc/core/channel/v1/connections/{connection}/channels\x12\xd0\x01\n" +
	"\x12ChannelClientState\x123.ibc.core.channel.v1.QueryChannelClientStateRequest\x1a4.ibc.core.channel.v1.QueryChannelClientStateResponse\"O\x82\xd3\xe4\x93\x02I\x12G/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/client_state\x12\x92\x02\n" +
	"\x15ChannelConsensusState\x126.ibc.core.channel.v1.QueryChannelConsensusStateRequest\x1a7.ibc.core.channel.v1.QueryChannelConsensusStateResponse\"\x87\x01\x82\xd3\xe4\x93\x02\x80\x01\x12~/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/consensus_state/revision/{revision_number}/height/{revision_height}\x12\xdb\x01\n" +
	"\x10PacketCommitment\x121.ibc.core.channel.v1.QueryPacketCommitmentRequest\x1a2.ibc.core.channel.v1.QueryPacketCommitmentResponse\"`\x82\xd3\xe4\x93\x02Z\x12X/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_commitments/{sequence}\x12\xd3\x01\n" +
	"\x11PacketCommitments\x122.ibc.core.channel.v1.QueryPacketCommitmentsRequest\x1a3.ibc.core.channel.v1.QueryPacketCommitmentsResponse\"U\x82\xd3\xe4\x93\x02O\x12M/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_commitments\x12\xcf\x01\n" +
	"\rPacketReceipt\x12..ibc.core.channel.v1.QueryPacketReceiptRequest\x1a/.ibc.core.channel.v1.QueryPacketReceiptResponse\"]\x82\xd3\xe4\x93\x02W\x12U/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_receipts/{sequence}\x12\xe3\x01\n" +
	"\x15PacketAcknowledgement\x126.ibc.core.channel.v1.QueryPacketAcknowledgementRequest\x1a7.ibc.core.channel.v1.QueryPacketAcknowledgementResponse\"Y\x82\xd3\xe4\x93\x02S\x12Q/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_acks/{sequence}\x12\xe7\x01\n" +
	"\x16PacketAcknowledgements\x127.ibc.core.channel.v1.QueryPacketAcknowledgementsRequest\x1a8.ibc.core.channel.v1.QueryPacketAcknowledgementsResponse\"Z\x82\xd3\xe4\x93\x02T\x12R/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_acknowledgements\x12\x86\x02\n" +
	"\x11UnreceivedPackets\x122.ibc.core.channel.v1.QueryUnreceivedPacketsRequest\x1a3.ibc.core.channel.v1.QueryUnreceivedPacketsResponse\"\x87\x01\x82\xd3\xe4\x93\x02\x80\x01\x12~/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_commitments/{packet_commitment_sequences}/unreceived_packets\x12\xf1\x01\n" +
	"\x0eUnreceivedAcks\x12/.ibc.core.channel.v1.QueryUnreceivedAcksRequest\x1a0.ibc.core.channel.v1.QueryUnreceivedAcksResponse\"|\x82\xd3\xe4\x93\x02v\x12t/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/packet_commitments/{packet_ack_sequences}/unreceived_acks\x12\xd4\x01\n" +
	"\x13NextSequenceReceive\x124.ibc.core.channel.v1.QueryNextSequenceReceiveRequest\x1a5.ibc.core.channel.v1.QueryNextSequenceReceiveResponse\"P\x82\xd3\xe4\x93\x02J\x12H/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/next_sequence\x12\xd0\x01\n" +
	"\x10NextSequenceSend\x121.ibc.core.channel.v1.QueryNextSequenceSendRequest\x1a2.ibc.core.channel.v1.QueryNextSequenceSendResponse\"U\x82\xd3\xe4\x93\x02O\x12M/ibc/core/channel/v1/channels/{channel_id}/ports/{port_id}/next_sequence_sendB\xd1\x01\n" +
	"\x17com.ibc.core.channel.v1B\n" +
	"QueryProtoP\x01Z;github.com/drpcorg/public/pkg/ibc/core/channel/v1;channelv1\xa2\x02\x03ICC\xaa\x02\x13Ibc.Core.Channel.V1\xca\x02\x13Ibc\\Core\\Channel\\V1\xe2\x02\x1fIbc\\Core\\Channel\\V1\\GPBMetadata\xea\x02\x16Ibc::Core::Channel::V1b\x06proto3"

var (
	file_ibc_core_channel_v1_query_proto_rawDescOnce sync.Once
	file_ibc_core_channel_v1_query_proto_rawDescData []byte
)

func file_ibc_core_channel_v1_query_proto_rawDescGZIP() []byte {
	file_ibc_core_channel_v1_query_proto_rawDescOnce.Do(func() {
		file_ibc_core_channel_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_core_channel_v1_query_proto_rawDesc), len(file_ibc_core_channel_v1_query_proto_rawDesc)))
	})
	return file_ibc_core_channel_v1_query_proto_rawDescData
}

var file_ibc_core_channel_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_ibc_core_channel_v1_query_proto_goTypes = []any{
	(*QueryChannelRequest)(nil),                 // 0: ibc.core.channel.v1.QueryChannelRequest
	(*QueryChannelResponse)(nil),                // 1: ibc.core.channel.v1.QueryChannelResponse
	(*QueryChannelsRequest)(nil),                // 2: ibc.core.channel.v1.QueryChannelsRequest
	(*QueryChannelsResponse)(nil),               // 3: ibc.core.channel.v1.QueryChannelsResponse
	(*QueryConnectionChannelsRequest)(nil),      // 4: ibc.core.channel.v1.QueryConnectionChannelsRequest
	(*QueryConnectionChannelsResponse)(nil),     // 5: ibc.core.channel.v1.QueryConnectionChannelsResponse
	(*QueryChannelClientStateRequest)(nil),      // 6: ibc.core.channel.v1.QueryChannelClientStateRequest
	(*QueryChannelClientStateResponse)(nil),     // 7: ibc.core.channel.v1.QueryChannelClientStateResponse
	(*QueryChannelConsensusStateRequest)(nil),   // 8: ibc.core.channel.v1.QueryChannelConsensusStateRequest
	(*QueryChannelConsensusStateResponse)(nil),  // 9: ibc.core.channel.v1.QueryChannelConsensusStateResponse
	(*QueryPacketCommitmentRequest)(nil),        // 10: ibc.core.channel.v1.QueryPacketCommitmentRequest
	(*QueryPacketCommitmentResponse)(nil),       // 11: ibc.core.channel.v1.QueryPacketCommitmentResponse
	(*QueryPacketCommitmentsRequest)(nil),       // 12: ibc.core.channel.v1.QueryPacketCommitmentsRequest
	(*QueryPacketCommitmentsResponse)(nil),      // 13: ibc.core.channel.v1.QueryPacketCommitmentsResponse
	(*QueryPacketReceiptRequest)(nil),           // 14: ibc.core.channel.v1.QueryPacketReceiptRequest
	(*QueryPacketReceiptResponse)(nil),          // 15: ibc.core.channel.v1.QueryPacketReceiptResponse
	(*QueryPacketAcknowledgementRequest)(nil),   // 16: ibc.core.channel.v1.QueryPacketAcknowledgementRequest
	(*QueryPacketAcknowledgementResponse)(nil),  // 17: ibc.core.channel.v1.QueryPacketAcknowledgementResponse
	(*QueryPacketAcknowledgementsRequest)(nil),  // 18: ibc.core.channel.v1.QueryPacketAcknowledgementsRequest
	(*QueryPacketAcknowledgementsResponse)(nil), // 19: ibc.core.channel.v1.QueryPacketAcknowledgementsResponse
	(*QueryUnreceivedPacketsRequest)(nil),       // 20: ibc.core.channel.v1.QueryUnreceivedPacketsRequest
	(*QueryUnreceivedPacketsResponse)(nil),      // 21: ibc.core.channel.v1.QueryUnreceivedPacketsResponse
	(*QueryUnreceivedAcksRequest)(nil),          // 22: ibc.core.channel.v1.QueryUnreceivedAcksRequest
	(*QueryUnreceivedAcksResponse)(nil),         // 23: ibc.core.channel.v1.QueryUnreceivedAcksResponse
	(*QueryNextSequenceReceiveRequest)(nil),     // 24: ibc.core.channel.v1.QueryNextSequenceReceiveRequest
	(*QueryNextSequenceReceiveResponse)(nil),    // 25: ibc.core.channel.v1.QueryNextSequenceReceiveResponse
	(*QueryNextSequenceSendRequest)(nil),        // 26: ibc.core.channel.v1.QueryNextSequenceSendRequest
	(*QueryNextSequenceSendResponse)(nil),       // 27: ibc.core.channel.v1.QueryNextSequenceSendResponse
	(*Channel)(nil),                             // 28: ibc.core.channel.v1.Channel
	(*v1.Height)(nil),                           // 29: ibc.core.client.v1.Height
	(*v1beta1.PageRequest)(nil),                 // 30: cosmos.base.query.v1beta1.PageRequest
	(*IdentifiedChannel)(nil),                   // 31: ibc.core.channel.v1.IdentifiedChannel
	(*v1beta1.PageResponse)(nil),                // 32: cosmos.base.query.v1beta1.PageResponse
	(*v1.IdentifiedClientState)(nil),            // 33: ibc.core.client.v1.IdentifiedClientState
	(*anypb.Any)(nil),                           // 34: google.protobuf.Any
	(*PacketState)(nil),                         // 35: ibc.core.channel.v1.PacketState
}
var file_ibc_core_channel_v1_query_proto_depIdxs = []int32{
	28, // 0: ibc.core.channel.v1.QueryChannelResponse.channel:type_name -> ibc.core.channel.v1.Channel
	29, // 1: ibc.core.channel.v1.QueryChannelResponse.proof_height:type_name -> ibc.core.client.v1.Height
	30, // 2: ibc.core.channel.v1.QueryChannelsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	31, // 3: ibc.core.channel.v1.QueryChannelsResponse.channels:type_name -> ibc.core.channel.v1.IdentifiedChannel
	32, // 4: ibc.core.channel.v1.QueryChannelsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	29, // 5: ibc.core.channel.v1.QueryChannelsResponse.height:type_name -> ibc.core.client.v1.Height
	30, // 6: ibc.core.channel.v1.QueryConnectionChannelsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	31, // 7: ibc.core.channel.v1.QueryConnectionChannelsResponse.channels:type_name -> ibc.core.channel.v1.IdentifiedChannel
	32, // 8: ibc.core.channel.v1.QueryConnectionChannelsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	29, // 9: ibc.core.channel.v1.QueryConnectionChannelsResponse.height:type_name -> ibc.core.client.v1.Height
	33, // 10: ibc.core.channel.v1.QueryChannelClientStateResponse.identified_client_state:type_name -> ibc.core.client.v1.IdentifiedClientState
	29, // 11: ibc.core.channel.v1.QueryChannelClientStateResponse.proof_height:type_name -> ibc.core.client.v1.Height
	34, // 12: ibc.core.channel.v1.QueryChannelConsensusStateResponse.consensus_state:type_name -> google.protobuf.Any
	29, // 13: ibc.core.channel.v1.QueryChannelConsensusStateResponse.proof_height:type_name -> ibc.core.client.v1.Height
	29, // 14: ibc.core.channel.v1.QueryPacketCommitmentResponse.proof_height:type_name -> ibc.core.client.v1.Height
	30, // 15: ibc.core.channel.v1.QueryPacketCommitmentsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	35, // 16: ibc.core.channel.v1.QueryPacketCommitmentsResponse.commitments:type_name -> ibc.core.channel.v1.PacketState
	32, // 17: ibc.core.channel.v1.QueryPacketCommitmentsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	29, // 18: ibc.core.channel.v1.QueryPacketCommitmentsResponse.height:type_name -> ibc.core.client.v1.Height
	29, // 19: ibc.core.channel.v1.QueryPacketReceiptResponse.proof_height:type_name -> ibc.core.client.v1.Height
	29, // 20: ibc.core.channel.v1.QueryPacketAcknowledgementResponse.proof_height:type_name -> ibc.core.client.v1.Height
	30, // 21: ibc.core.channel.v1.QueryPacketAcknowledgementsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	35, // 22: ibc.core.channel.v1.QueryPacketAcknowledgementsResponse.acknowledgements:type_name -> ibc.core.channel.v1.PacketState
	32, // 23: ibc.core.channel.v1.QueryPacketAcknowledgementsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	29, // 24: ibc.core.channel.v1.QueryPacketAcknowledgementsResponse.height:type_name -> ibc.core.client.v1.Height
	29, // 25: ibc.core.channel.v1.QueryUnreceivedPacketsResponse.height:type_name -> ibc.core.client.v1.Height
	29, // 26: ibc.core.channel.v1.QueryUnreceivedAcksResponse.height:type_name -> ibc.core.client.v1.Height
	29, // 27: ibc.core.channel.v1.QueryNextSequenceReceiveResponse.proof_height:type_name -> ibc.core.client.v1.Height
	29, // 28: ibc.core.channel.v1.QueryNextSequenceSendResponse.proof_height:type_name -> ibc.core.client.v1.Height
	0,  // 29: ibc.core.channel.v1.Query.Channel:input_type -> ibc.core.channel.v1.QueryChannelRequest
	2,  // 30: ibc.core.channel.v1.Query.Channels:input_type -> ibc.core.channel.v1.QueryChannelsRequest
	4,  // 31: ibc.core.channel.v1.Query.ConnectionChannels:input_type -> ibc.core.channel.v1.QueryConnectionChannelsRequest
	6,  // 32: ibc.core.channel.v1.Query.ChannelClientState:input_type -> ibc.core.channel.v1.QueryChannelClientStateRequest
	8,  // 33: ibc.core.channel.v1.Query.ChannelConsensusState:input_type -> ibc.core.channel.v1.QueryChannelConsensusStateRequest
	10, // 34: ibc.core.channel.v1.Query.PacketCommitment:input_type -> ibc.core.channel.v1.QueryPacketCommitmentRequest
	12, // 35: ibc.core.channel.v1.Query.PacketCommitments:input_type -> ibc.core.channel.v1.QueryPacketCommitmentsRequest
	14, // 36: ibc.core.channel.v1.Query.PacketReceipt:input_type -> ibc.core.channel.v1.QueryPacketReceiptRequest
	16, // 37: ibc.core.channel.v1.Query.PacketAcknowledgement:input_type -> ibc.core.channel.v1.QueryPacketAcknowledgementRequest
	18, // 38: ibc.core.channel.v1.Query.PacketAcknowledgements:input_type -> ibc.core.channel.v1.QueryPacketAcknowledgementsRequest
	20, // 39: ibc.core.channel.v1.Query.UnreceivedPackets:input_type -> ibc.core.channel.v1.QueryUnreceivedPacketsRequest
	22, // 40: ibc.core.channel.v1.Query.UnreceivedAcks:input_type -> ibc.core.channel.v1.QueryUnreceivedAcksRequest
	24, // 41: ibc.core.channel.v1.Query.NextSequenceReceive:input_type -> ibc.core.channel.v1.QueryNextSequenceReceiveRequest
	26, // 42: ibc.core.channel.v1.Query.NextSequenceSend:input_type -> ibc.core.channel.v1.QueryNextSequenceSendRequest
	1,  // 43: ibc.core.channel.v1.Query.Channel:output_type -> ibc.core.channel.v1.QueryChannelResponse
	3,  // 44: ibc.core.channel.v1.Query.Channels:output_type -> ibc.core.channel.v1.QueryChannelsResponse
	5,  // 45: ibc.core.channel.v1.Query.ConnectionChannels:output_type -> ibc.core.channel.v1.QueryConnectionChannelsResponse
	7,  // 46: ibc.core.channel.v1.Query.ChannelClientState:output_type -> ibc.core.channel.v1.QueryChannelClientStateResponse
	9,  // 47: ibc.core.channel.v1.Query.ChannelConsensusState:output_type -> ibc.core.channel.v1.QueryChannelConsensusStateResponse
	11, // 48: ibc.core.channel.v1.Query.PacketCommitment:output_type -> ibc.core.channel.v1.QueryPacketCommitmentResponse
	13, // 49: ibc.core.channel.v1.Query.PacketCommitments:output_type -> ibc.core.channel.v1.QueryPacketCommitmentsResponse
	15, // 50: ibc.core.channel.v1.Query.PacketReceipt:output_type -> ibc.core.channel.v1.QueryPacketReceiptResponse
	17, // 51: ibc.core.channel.v1.Query.PacketAcknowledgement:output_type -> ibc.core.channel.v1.QueryPacketAcknowledgementResponse
	19, // 52: ibc.core.channel.v1.Query.PacketAcknowledgements:output_type -> ibc.core.channel.v1.QueryPacketAcknowledgementsResponse
	21, // 53: ibc.core.channel.v1.Query.UnreceivedPackets:output_type -> ibc.core.channel.v1.QueryUnreceivedPacketsResponse
	23, // 54: ibc.core.channel.v1.Query.UnreceivedAcks:output_type -> ibc.core.channel.v1.QueryUnreceivedAcksResponse
	25, // 55: ibc.core.channel.v1.Query.NextSequenceReceive:output_type -> ibc.core.channel.v1.QueryNextSequenceReceiveResponse
	27, // 56: ibc.core.channel.v1.Query.NextSequenceSend:output_type -> ibc.core.channel.v1.QueryNextSequenceSendResponse
	43, // [43:57] is the sub-list for method output_type
	29, // [29:43] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_ibc_core_channel_v1_query_proto_init() }
func file_ibc_core_channel_v1_query_proto_init() {
	if File_ibc_core_channel_v1_query_proto != nil {
		return
	}
	file_ibc_core_channel_v1_channel_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_core_channel_v1_query_proto_rawDesc), len(file_ibc_core_channel_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ibc_core_channel_v1_query_proto_goTypes,
		DependencyIndexes: file_ibc_core_channel_v1_query_proto_depIdxs,
		MessageInfos:      file_ibc_core_channel_v1_query_proto_msgTypes,
	}.Build()
	File_ibc_core_channel_v1_query_proto = out.File
	file_ibc_core_channel_v1_query_proto_goTypes = nil
	file_ibc_core_channel_v1_query_proto_depIdxs = nil
}
