// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/core/client/v1/genesis.proto

package clientv1

import (
	_ "github.com/drpcorg/public/pkg/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenesisState defines the ibc client submodule's genesis state.
type GenesisState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client states with their corresponding identifiers
	Clients []*IdentifiedClientState `protobuf:"bytes,1,rep,name=clients,proto3" json:"clients,omitempty"`
	// consensus states from each client
	ClientsConsensus []*ClientConsensusStates `protobuf:"bytes,2,rep,name=clients_consensus,json=clientsConsensus,proto3" json:"clients_consensus,omitempty"`
	// metadata from each client
	ClientsMetadata []*IdentifiedGenesisMetadata `protobuf:"bytes,3,rep,name=clients_metadata,json=clientsMetadata,proto3" json:"clients_metadata,omitempty"`
	Params          *Params                      `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	// Deprecated: create_localhost has been deprecated.
	// The localhost client is automatically created at genesis.
	//
	// Deprecated: Marked as deprecated in ibc/core/client/v1/genesis.proto.
	CreateLocalhost bool `protobuf:"varint,5,opt,name=create_localhost,json=createLocalhost,proto3" json:"create_localhost,omitempty"`
	// the sequence for the next generated client identifier
	NextClientSequence uint64 `protobuf:"varint,6,opt,name=next_client_sequence,json=nextClientSequence,proto3" json:"next_client_sequence,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenesisState) Reset() {
	*x = GenesisState{}
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisState) ProtoMessage() {}

func (x *GenesisState) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisState.ProtoReflect.Descriptor instead.
func (*GenesisState) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_genesis_proto_rawDescGZIP(), []int{0}
}

func (x *GenesisState) GetClients() []*IdentifiedClientState {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *GenesisState) GetClientsConsensus() []*ClientConsensusStates {
	if x != nil {
		return x.ClientsConsensus
	}
	return nil
}

func (x *GenesisState) GetClientsMetadata() []*IdentifiedGenesisMetadata {
	if x != nil {
		return x.ClientsMetadata
	}
	return nil
}

func (x *GenesisState) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// Deprecated: Marked as deprecated in ibc/core/client/v1/genesis.proto.
func (x *GenesisState) GetCreateLocalhost() bool {
	if x != nil {
		return x.CreateLocalhost
	}
	return false
}

func (x *GenesisState) GetNextClientSequence() uint64 {
	if x != nil {
		return x.NextClientSequence
	}
	return 0
}

// GenesisMetadata defines the genesis type for metadata that will be used
// to export all client store keys that are not client or consensus states.
type GenesisMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// store key of metadata without clientID-prefix
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// metadata value
	Value         []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenesisMetadata) Reset() {
	*x = GenesisMetadata{}
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenesisMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenesisMetadata) ProtoMessage() {}

func (x *GenesisMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenesisMetadata.ProtoReflect.Descriptor instead.
func (*GenesisMetadata) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_genesis_proto_rawDescGZIP(), []int{1}
}

func (x *GenesisMetadata) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *GenesisMetadata) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

// IdentifiedGenesisMetadata has the client metadata with the corresponding
// client id.
type IdentifiedGenesisMetadata struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientMetadata []*GenesisMetadata     `protobuf:"bytes,2,rep,name=client_metadata,json=clientMetadata,proto3" json:"client_metadata,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IdentifiedGenesisMetadata) Reset() {
	*x = IdentifiedGenesisMetadata{}
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdentifiedGenesisMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdentifiedGenesisMetadata) ProtoMessage() {}

func (x *IdentifiedGenesisMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_genesis_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdentifiedGenesisMetadata.ProtoReflect.Descriptor instead.
func (*IdentifiedGenesisMetadata) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_genesis_proto_rawDescGZIP(), []int{2}
}

func (x *IdentifiedGenesisMetadata) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *IdentifiedGenesisMetadata) GetClientMetadata() []*GenesisMetadata {
	if x != nil {
		return x.ClientMetadata
	}
	return nil
}

var File_ibc_core_client_v1_genesis_proto protoreflect.FileDescriptor

const file_ibc_core_client_v1_genesis_proto_rawDesc = "" +
	"\n" +
	" ibc/core/client/v1/genesis.proto\x12\x12ibc.core.client.v1\x1a\x1fibc/core/client/v1/client.proto\x1a\x14gogoproto/gogo.proto\"\xe6\x03\n" +
	"\fGenesisState\x12c\n" +
	"\aclients\x18\x01 \x03(\v2).ibc.core.client.v1.IdentifiedClientStateB\x1e\xc8\xde\x1f\x00\xaa\xdf\x1f\x16IdentifiedClientStatesR\aclients\x12v\n" +
	"\x11clients_consensus\x18\x02 \x03(\v2).ibc.core.client.v1.ClientConsensusStatesB\x1e\xc8\xde\x1f\x00\xaa\xdf\x1f\x16ClientsConsensusStatesR\x10clientsConsensus\x12^\n" +
	"\x10clients_metadata\x18\x03 \x03(\v2-.ibc.core.client.v1.IdentifiedGenesisMetadataB\x04\xc8\xde\x1f\x00R\x0fclientsMetadata\x128\n" +
	"\x06params\x18\x04 \x01(\v2\x1a.ibc.core.client.v1.ParamsB\x04\xc8\xde\x1f\x00R\x06params\x12-\n" +
	"\x10create_localhost\x18\x05 \x01(\bB\x02\x18\x01R\x0fcreateLocalhost\x120\n" +
	"\x14next_client_sequence\x18\x06 \x01(\x04R\x12nextClientSequence\"?\n" +
	"\x0fGenesisMetadata\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x04\x88\xa0\x1f\x00\"\x8c\x01\n" +
	"\x19IdentifiedGenesisMetadata\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12R\n" +
	"\x0fclient_metadata\x18\x02 \x03(\v2#.ibc.core.client.v1.GenesisMetadataB\x04\xc8\xde\x1f\x00R\x0eclientMetadataB\xcc\x01\n" +
	"\x16com.ibc.core.client.v1B\fGenesisProtoP\x01Z9github.com/drpcorg/public/pkg/ibc/core/client/v1;clientv1\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V1\xca\x02\x12Ibc\\Core\\Client\\V1\xe2\x02\x1eIbc\\Core\\Client\\V1\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V1b\x06proto3"

var (
	file_ibc_core_client_v1_genesis_proto_rawDescOnce sync.Once
	file_ibc_core_client_v1_genesis_proto_rawDescData []byte
)

func file_ibc_core_client_v1_genesis_proto_rawDescGZIP() []byte {
	file_ibc_core_client_v1_genesis_proto_rawDescOnce.Do(func() {
		file_ibc_core_client_v1_genesis_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_core_client_v1_genesis_proto_rawDesc), len(file_ibc_core_client_v1_genesis_proto_rawDesc)))
	})
	return file_ibc_core_client_v1_genesis_proto_rawDescData
}

var file_ibc_core_client_v1_genesis_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ibc_core_client_v1_genesis_proto_goTypes = []any{
	(*GenesisState)(nil),              // 0: ibc.core.client.v1.GenesisState
	(*GenesisMetadata)(nil),           // 1: ibc.core.client.v1.GenesisMetadata
	(*IdentifiedGenesisMetadata)(nil), // 2: ibc.core.client.v1.IdentifiedGenesisMetadata
	(*IdentifiedClientState)(nil),     // 3: ibc.core.client.v1.IdentifiedClientState
	(*ClientConsensusStates)(nil),     // 4: ibc.core.client.v1.ClientConsensusStates
	(*Params)(nil),                    // 5: ibc.core.client.v1.Params
}
var file_ibc_core_client_v1_genesis_proto_depIdxs = []int32{
	3, // 0: ibc.core.client.v1.GenesisState.clients:type_name -> ibc.core.client.v1.IdentifiedClientState
	4, // 1: ibc.core.client.v1.GenesisState.clients_consensus:type_name -> ibc.core.client.v1.ClientConsensusStates
	2, // 2: ibc.core.client.v1.GenesisState.clients_metadata:type_name -> ibc.core.client.v1.IdentifiedGenesisMetadata
	5, // 3: ibc.core.client.v1.GenesisState.params:type_name -> ibc.core.client.v1.Params
	1, // 4: ibc.core.client.v1.IdentifiedGenesisMetadata.client_metadata:type_name -> ibc.core.client.v1.GenesisMetadata
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ibc_core_client_v1_genesis_proto_init() }
func file_ibc_core_client_v1_genesis_proto_init() {
	if File_ibc_core_client_v1_genesis_proto != nil {
		return
	}
	file_ibc_core_client_v1_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_core_client_v1_genesis_proto_rawDesc), len(file_ibc_core_client_v1_genesis_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ibc_core_client_v1_genesis_proto_goTypes,
		DependencyIndexes: file_ibc_core_client_v1_genesis_proto_depIdxs,
		MessageInfos:      file_ibc_core_client_v1_genesis_proto_msgTypes,
	}.Build()
	File_ibc_core_client_v1_genesis_proto = out.File
	file_ibc_core_client_v1_genesis_proto_goTypes = nil
	file_ibc_core_client_v1_genesis_proto_depIdxs = nil
}
