// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: ibc/core/client/v1/query.proto

package clientv1

import (
	v1beta1 "cosmossdk.io/api/cosmos/base/query/v1beta1"
	_ "cosmossdk.io/api/cosmos/query/v1"
	_ "github.com/cosmos/gogoproto/gogoproto"
	v2 "github.com/drpcorg/public/pkg/ibc/core/commitment/v2"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueryClientStateRequest is the request type for the Query/ClientState RPC
// method
type QueryClientStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client state unique identifier
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStateRequest) Reset() {
	*x = QueryClientStateRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStateRequest) ProtoMessage() {}

func (x *QueryClientStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStateRequest.ProtoReflect.Descriptor instead.
func (*QueryClientStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{0}
}

func (x *QueryClientStateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// QueryClientStateResponse is the response type for the Query/ClientState RPC
// method. Besides the client state, it includes a proof and the height from
// which the proof was retrieved.
type QueryClientStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client state associated with the request identifier
	ClientState *anypb.Any `protobuf:"bytes,1,opt,name=client_state,json=clientState,proto3" json:"client_state,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStateResponse) Reset() {
	*x = QueryClientStateResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStateResponse) ProtoMessage() {}

func (x *QueryClientStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStateResponse.ProtoReflect.Descriptor instead.
func (*QueryClientStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{1}
}

func (x *QueryClientStateResponse) GetClientState() *anypb.Any {
	if x != nil {
		return x.ClientState
	}
	return nil
}

func (x *QueryClientStateResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryClientStateResponse) GetProofHeight() *Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryClientStatesRequest is the request type for the Query/ClientStates RPC
// method
type QueryClientStatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStatesRequest) Reset() {
	*x = QueryClientStatesRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStatesRequest) ProtoMessage() {}

func (x *QueryClientStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStatesRequest.ProtoReflect.Descriptor instead.
func (*QueryClientStatesRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{2}
}

func (x *QueryClientStatesRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryClientStatesResponse is the response type for the Query/ClientStates RPC
// method.
type QueryClientStatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// list of stored ClientStates of the chain.
	ClientStates []*IdentifiedClientState `protobuf:"bytes,1,rep,name=client_states,json=clientStates,proto3" json:"client_states,omitempty"`
	// pagination response
	Pagination    *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStatesResponse) Reset() {
	*x = QueryClientStatesResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStatesResponse) ProtoMessage() {}

func (x *QueryClientStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStatesResponse.ProtoReflect.Descriptor instead.
func (*QueryClientStatesResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{3}
}

func (x *QueryClientStatesResponse) GetClientStates() []*IdentifiedClientState {
	if x != nil {
		return x.ClientStates
	}
	return nil
}

func (x *QueryClientStatesResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryConsensusStateRequest is the request type for the Query/ConsensusState
// RPC method. Besides the consensus state, it includes a proof and the height
// from which the proof was retrieved.
type QueryConsensusStateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// consensus state revision number
	RevisionNumber uint64 `protobuf:"varint,2,opt,name=revision_number,json=revisionNumber,proto3" json:"revision_number,omitempty"`
	// consensus state revision height
	RevisionHeight uint64 `protobuf:"varint,3,opt,name=revision_height,json=revisionHeight,proto3" json:"revision_height,omitempty"`
	// latest_height overrides the height field and queries the latest stored
	// ConsensusState
	LatestHeight  bool `protobuf:"varint,4,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStateRequest) Reset() {
	*x = QueryConsensusStateRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStateRequest) ProtoMessage() {}

func (x *QueryConsensusStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStateRequest.ProtoReflect.Descriptor instead.
func (*QueryConsensusStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{4}
}

func (x *QueryConsensusStateRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryConsensusStateRequest) GetRevisionNumber() uint64 {
	if x != nil {
		return x.RevisionNumber
	}
	return 0
}

func (x *QueryConsensusStateRequest) GetRevisionHeight() uint64 {
	if x != nil {
		return x.RevisionHeight
	}
	return 0
}

func (x *QueryConsensusStateRequest) GetLatestHeight() bool {
	if x != nil {
		return x.LatestHeight
	}
	return false
}

// QueryConsensusStateResponse is the response type for the Query/ConsensusState
// RPC method
type QueryConsensusStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consensus state associated with the client identifier at the given height
	ConsensusState *anypb.Any `protobuf:"bytes,1,opt,name=consensus_state,json=consensusState,proto3" json:"consensus_state,omitempty"`
	// merkle proof of existence
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// height at which the proof was retrieved
	ProofHeight   *Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStateResponse) Reset() {
	*x = QueryConsensusStateResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStateResponse) ProtoMessage() {}

func (x *QueryConsensusStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStateResponse.ProtoReflect.Descriptor instead.
func (*QueryConsensusStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{5}
}

func (x *QueryConsensusStateResponse) GetConsensusState() *anypb.Any {
	if x != nil {
		return x.ConsensusState
	}
	return nil
}

func (x *QueryConsensusStateResponse) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryConsensusStateResponse) GetProofHeight() *Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

// QueryConsensusStatesRequest is the request type for the Query/ConsensusStates
// RPC method.
type QueryConsensusStatesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStatesRequest) Reset() {
	*x = QueryConsensusStatesRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStatesRequest) ProtoMessage() {}

func (x *QueryConsensusStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStatesRequest.ProtoReflect.Descriptor instead.
func (*QueryConsensusStatesRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{6}
}

func (x *QueryConsensusStatesRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryConsensusStatesRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryConsensusStatesResponse is the response type for the
// Query/ConsensusStates RPC method
type QueryConsensusStatesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consensus states associated with the identifier
	ConsensusStates []*ConsensusStateWithHeight `protobuf:"bytes,1,rep,name=consensus_states,json=consensusStates,proto3" json:"consensus_states,omitempty"`
	// pagination response
	Pagination    *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStatesResponse) Reset() {
	*x = QueryConsensusStatesResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStatesResponse) ProtoMessage() {}

func (x *QueryConsensusStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStatesResponse.ProtoReflect.Descriptor instead.
func (*QueryConsensusStatesResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{7}
}

func (x *QueryConsensusStatesResponse) GetConsensusStates() []*ConsensusStateWithHeight {
	if x != nil {
		return x.ConsensusStates
	}
	return nil
}

func (x *QueryConsensusStatesResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryConsensusStateHeightsRequest is the request type for Query/ConsensusStateHeights
// RPC method.
type QueryConsensusStateHeightsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client identifier
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// pagination request
	Pagination    *v1beta1.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStateHeightsRequest) Reset() {
	*x = QueryConsensusStateHeightsRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStateHeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStateHeightsRequest) ProtoMessage() {}

func (x *QueryConsensusStateHeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStateHeightsRequest.ProtoReflect.Descriptor instead.
func (*QueryConsensusStateHeightsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{8}
}

func (x *QueryConsensusStateHeightsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryConsensusStateHeightsRequest) GetPagination() *v1beta1.PageRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryConsensusStateHeightsResponse is the response type for the
// Query/ConsensusStateHeights RPC method
type QueryConsensusStateHeightsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// consensus state heights
	ConsensusStateHeights []*Height `protobuf:"bytes,1,rep,name=consensus_state_heights,json=consensusStateHeights,proto3" json:"consensus_state_heights,omitempty"`
	// pagination response
	Pagination    *v1beta1.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConsensusStateHeightsResponse) Reset() {
	*x = QueryConsensusStateHeightsResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConsensusStateHeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConsensusStateHeightsResponse) ProtoMessage() {}

func (x *QueryConsensusStateHeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConsensusStateHeightsResponse.ProtoReflect.Descriptor instead.
func (*QueryConsensusStateHeightsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{9}
}

func (x *QueryConsensusStateHeightsResponse) GetConsensusStateHeights() []*Height {
	if x != nil {
		return x.ConsensusStateHeights
	}
	return nil
}

func (x *QueryConsensusStateHeightsResponse) GetPagination() *v1beta1.PageResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// QueryClientStatusRequest is the request type for the Query/ClientStatus RPC
// method
type QueryClientStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client unique identifier
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStatusRequest) Reset() {
	*x = QueryClientStatusRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStatusRequest) ProtoMessage() {}

func (x *QueryClientStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStatusRequest.ProtoReflect.Descriptor instead.
func (*QueryClientStatusRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{10}
}

func (x *QueryClientStatusRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// QueryClientStatusResponse is the response type for the Query/ClientStatus RPC
// method. It returns the current status of the IBC client.
type QueryClientStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientStatusResponse) Reset() {
	*x = QueryClientStatusResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientStatusResponse) ProtoMessage() {}

func (x *QueryClientStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientStatusResponse.ProtoReflect.Descriptor instead.
func (*QueryClientStatusResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{11}
}

func (x *QueryClientStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// QueryClientParamsRequest is the request type for the Query/ClientParams RPC
// method.
type QueryClientParamsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientParamsRequest) Reset() {
	*x = QueryClientParamsRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientParamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientParamsRequest) ProtoMessage() {}

func (x *QueryClientParamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientParamsRequest.ProtoReflect.Descriptor instead.
func (*QueryClientParamsRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{12}
}

// QueryClientParamsResponse is the response type for the Query/ClientParams RPC
// method.
type QueryClientParamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// params defines the parameters of the module.
	Params        *Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientParamsResponse) Reset() {
	*x = QueryClientParamsResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientParamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientParamsResponse) ProtoMessage() {}

func (x *QueryClientParamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientParamsResponse.ProtoReflect.Descriptor instead.
func (*QueryClientParamsResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{13}
}

func (x *QueryClientParamsResponse) GetParams() *Params {
	if x != nil {
		return x.Params
	}
	return nil
}

// QueryClientCreatorRequest is the request type for the Query/ClientCreator RPC
// method.
type QueryClientCreatorRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client unique identifier
	ClientId      string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientCreatorRequest) Reset() {
	*x = QueryClientCreatorRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientCreatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientCreatorRequest) ProtoMessage() {}

func (x *QueryClientCreatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientCreatorRequest.ProtoReflect.Descriptor instead.
func (*QueryClientCreatorRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{14}
}

func (x *QueryClientCreatorRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// QueryClientCreatorResponse is the response type for the Query/ClientCreator RPC
// method.
type QueryClientCreatorResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// creator of the client
	Creator       string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryClientCreatorResponse) Reset() {
	*x = QueryClientCreatorResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryClientCreatorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryClientCreatorResponse) ProtoMessage() {}

func (x *QueryClientCreatorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryClientCreatorResponse.ProtoReflect.Descriptor instead.
func (*QueryClientCreatorResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{15}
}

func (x *QueryClientCreatorResponse) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

// QueryUpgradedClientStateRequest is the request type for the
// Query/UpgradedClientState RPC method
type QueryUpgradedClientStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUpgradedClientStateRequest) Reset() {
	*x = QueryUpgradedClientStateRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUpgradedClientStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUpgradedClientStateRequest) ProtoMessage() {}

func (x *QueryUpgradedClientStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUpgradedClientStateRequest.ProtoReflect.Descriptor instead.
func (*QueryUpgradedClientStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{16}
}

// QueryUpgradedClientStateResponse is the response type for the
// Query/UpgradedClientState RPC method.
type QueryUpgradedClientStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client state associated with the request identifier
	UpgradedClientState *anypb.Any `protobuf:"bytes,1,opt,name=upgraded_client_state,json=upgradedClientState,proto3" json:"upgraded_client_state,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *QueryUpgradedClientStateResponse) Reset() {
	*x = QueryUpgradedClientStateResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUpgradedClientStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUpgradedClientStateResponse) ProtoMessage() {}

func (x *QueryUpgradedClientStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUpgradedClientStateResponse.ProtoReflect.Descriptor instead.
func (*QueryUpgradedClientStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{17}
}

func (x *QueryUpgradedClientStateResponse) GetUpgradedClientState() *anypb.Any {
	if x != nil {
		return x.UpgradedClientState
	}
	return nil
}

// QueryUpgradedConsensusStateRequest is the request type for the
// Query/UpgradedConsensusState RPC method
type QueryUpgradedConsensusStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUpgradedConsensusStateRequest) Reset() {
	*x = QueryUpgradedConsensusStateRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUpgradedConsensusStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUpgradedConsensusStateRequest) ProtoMessage() {}

func (x *QueryUpgradedConsensusStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUpgradedConsensusStateRequest.ProtoReflect.Descriptor instead.
func (*QueryUpgradedConsensusStateRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{18}
}

// QueryUpgradedConsensusStateResponse is the response type for the
// Query/UpgradedConsensusState RPC method.
type QueryUpgradedConsensusStateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consensus state associated with the request identifier
	UpgradedConsensusState *anypb.Any `protobuf:"bytes,1,opt,name=upgraded_consensus_state,json=upgradedConsensusState,proto3" json:"upgraded_consensus_state,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *QueryUpgradedConsensusStateResponse) Reset() {
	*x = QueryUpgradedConsensusStateResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUpgradedConsensusStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUpgradedConsensusStateResponse) ProtoMessage() {}

func (x *QueryUpgradedConsensusStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUpgradedConsensusStateResponse.ProtoReflect.Descriptor instead.
func (*QueryUpgradedConsensusStateResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{19}
}

func (x *QueryUpgradedConsensusStateResponse) GetUpgradedConsensusState() *anypb.Any {
	if x != nil {
		return x.UpgradedConsensusState
	}
	return nil
}

// QueryVerifyMembershipRequest is the request type for the Query/VerifyMembership RPC method
type QueryVerifyMembershipRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client unique identifier.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// the proof to be verified by the client.
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// the height of the commitment root at which the proof is verified.
	ProofHeight *Height `protobuf:"bytes,3,opt,name=proof_height,json=proofHeight,proto3" json:"proof_height,omitempty"`
	// the value which is proven.
	Value []byte `protobuf:"bytes,5,opt,name=value,proto3" json:"value,omitempty"`
	// optional time delay
	TimeDelay uint64 `protobuf:"varint,6,opt,name=time_delay,json=timeDelay,proto3" json:"time_delay,omitempty"`
	// optional block delay
	BlockDelay uint64 `protobuf:"varint,7,opt,name=block_delay,json=blockDelay,proto3" json:"block_delay,omitempty"`
	// the commitment key path.
	MerklePath    *v2.MerklePath `protobuf:"bytes,8,opt,name=merkle_path,json=merklePath,proto3" json:"merkle_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifyMembershipRequest) Reset() {
	*x = QueryVerifyMembershipRequest{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifyMembershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifyMembershipRequest) ProtoMessage() {}

func (x *QueryVerifyMembershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifyMembershipRequest.ProtoReflect.Descriptor instead.
func (*QueryVerifyMembershipRequest) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{20}
}

func (x *QueryVerifyMembershipRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *QueryVerifyMembershipRequest) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *QueryVerifyMembershipRequest) GetProofHeight() *Height {
	if x != nil {
		return x.ProofHeight
	}
	return nil
}

func (x *QueryVerifyMembershipRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *QueryVerifyMembershipRequest) GetTimeDelay() uint64 {
	if x != nil {
		return x.TimeDelay
	}
	return 0
}

func (x *QueryVerifyMembershipRequest) GetBlockDelay() uint64 {
	if x != nil {
		return x.BlockDelay
	}
	return 0
}

func (x *QueryVerifyMembershipRequest) GetMerklePath() *v2.MerklePath {
	if x != nil {
		return x.MerklePath
	}
	return nil
}

// QueryVerifyMembershipResponse is the response type for the Query/VerifyMembership RPC method
type QueryVerifyMembershipResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// boolean indicating success or failure of proof verification.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryVerifyMembershipResponse) Reset() {
	*x = QueryVerifyMembershipResponse{}
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryVerifyMembershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryVerifyMembershipResponse) ProtoMessage() {}

func (x *QueryVerifyMembershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ibc_core_client_v1_query_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryVerifyMembershipResponse.ProtoReflect.Descriptor instead.
func (*QueryVerifyMembershipResponse) Descriptor() ([]byte, []int) {
	return file_ibc_core_client_v1_query_proto_rawDescGZIP(), []int{21}
}

func (x *QueryVerifyMembershipResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_ibc_core_client_v1_query_proto protoreflect.FileDescriptor

const file_ibc_core_client_v1_query_proto_rawDesc = "" +
	"\n" +
	"\x1eibc/core/client/v1/query.proto\x12\x12ibc.core.client.v1\x1a*cosmos/base/query/v1beta1/pagination.proto\x1a\x1bcosmos/query/v1/query.proto\x1a\x1fibc/core/client/v1/client.proto\x1a'ibc/core/commitment/v2/commitment.proto\x1a\x19google/protobuf/any.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x14gogoproto/gogo.proto\"6\n" +
	"\x17QueryClientStateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xae\x01\n" +
	"\x18QueryClientStateResponse\x127\n" +
	"\fclient_state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\vclientState\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"b\n" +
	"\x18QueryClientStatesRequest\x12F\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xd4\x01\n" +
	"\x19QueryClientStatesResponse\x12n\n" +
	"\rclient_states\x18\x01 \x03(\v2).ibc.core.client.v1.IdentifiedClientStateB\x1e\xc8\xde\x1f\x00\xaa\xdf\x1f\x16IdentifiedClientStatesR\fclientStates\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\xb0\x01\n" +
	"\x1aQueryConsensusStateRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12'\n" +
	"\x0frevision_number\x18\x02 \x01(\x04R\x0erevisionNumber\x12'\n" +
	"\x0frevision_height\x18\x03 \x01(\x04R\x0erevisionHeight\x12#\n" +
	"\rlatest_height\x18\x04 \x01(\bR\flatestHeight\"\xb7\x01\n" +
	"\x1bQueryConsensusStateResponse\x12=\n" +
	"\x0fconsensus_state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x0econsensusState\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\"\x82\x01\n" +
	"\x1bQueryConsensusStatesRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xc6\x01\n" +
	"\x1cQueryConsensusStatesResponse\x12]\n" +
	"\x10consensus_states\x18\x01 \x03(\v2,.ibc.core.client.v1.ConsensusStateWithHeightB\x04\xc8\xde\x1f\x00R\x0fconsensusStates\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"\x88\x01\n" +
	"!QueryConsensusStateHeightsRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12F\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2&.cosmos.base.query.v1beta1.PageRequestR\n" +
	"pagination\"\xc7\x01\n" +
	"\"QueryConsensusStateHeightsResponse\x12X\n" +
	"\x17consensus_state_heights\x18\x01 \x03(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\x15consensusStateHeights\x12G\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2'.cosmos.base.query.v1beta1.PageResponseR\n" +
	"pagination\"7\n" +
	"\x18QueryClientStatusRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"3\n" +
	"\x19QueryClientStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x1a\n" +
	"\x18QueryClientParamsRequest\"O\n" +
	"\x19QueryClientParamsResponse\x122\n" +
	"\x06params\x18\x01 \x01(\v2\x1a.ibc.core.client.v1.ParamsR\x06params\"8\n" +
	"\x19QueryClientCreatorRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"6\n" +
	"\x1aQueryClientCreatorResponse\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\"!\n" +
	"\x1fQueryUpgradedClientStateRequest\"l\n" +
	" QueryUpgradedClientStateResponse\x12H\n" +
	"\x15upgraded_client_state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x13upgradedClientState\"$\n" +
	"\"QueryUpgradedConsensusStateRequest\"u\n" +
	"#QueryUpgradedConsensusStateResponse\x12N\n" +
	"\x18upgraded_consensus_state\x18\x01 \x01(\v2\x14.google.protobuf.AnyR\x16upgradedConsensusState\"\xbd\x02\n" +
	"\x1cQueryVerifyMembershipRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12C\n" +
	"\fproof_height\x18\x03 \x01(\v2\x1a.ibc.core.client.v1.HeightB\x04\xc8\xde\x1f\x00R\vproofHeight\x12\x14\n" +
	"\x05value\x18\x05 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"time_delay\x18\x06 \x01(\x04R\ttimeDelay\x12\x1f\n" +
	"\vblock_delay\x18\a \x01(\x04R\n" +
	"blockDelay\x12I\n" +
	"\vmerkle_path\x18\b \x01(\v2\".ibc.core.commitment.v2.MerklePathB\x04\xc8\xde\x1f\x00R\n" +
	"merklePathJ\x04\b\x04\x10\x05\"9\n" +
	"\x1dQueryVerifyMembershipResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xab\x0f\n" +
	"\x05Query\x12\x9f\x01\n" +
	"\vClientState\x12+.ibc.core.client.v1.QueryClientStateRequest\x1a,.ibc.core.client.v1.QueryClientStateResponse\"5\x82\xd3\xe4\x93\x02/\x12-/ibc/core/client/v1/client_states/{client_id}\x12\x96\x01\n" +
	"\fClientStates\x12,.ibc.core.client.v1.QueryClientStatesRequest\x1a-.ibc.core.client.v1.QueryClientStatesResponse\")\x82\xd3\xe4\x93\x02#\x12!/ibc/core/client/v1/client_states\x12\xdf\x01\n" +
	"\x0eConsensusState\x12..ibc.core.client.v1.QueryConsensusStateRequest\x1a/.ibc.core.client.v1.QueryConsensusStateResponse\"l\x82\xd3\xe4\x93\x02f\x12d/ibc/core/client/v1/consensus_states/{client_id}/revision/{revision_number}/height/{revision_height}\x12\xae\x01\n" +
	"\x0fConsensusStates\x12/.ibc.core.client.v1.QueryConsensusStatesRequest\x1a0.ibc.core.client.v1.QueryConsensusStatesResponse\"8\x82\xd3\xe4\x93\x022\x120/ibc/core/client/v1/consensus_states/{client_id}\x12\xc8\x01\n" +
	"\x15ConsensusStateHeights\x125.ibc.core.client.v1.QueryConsensusStateHeightsRequest\x1a6.ibc.core.client.v1.QueryConsensusStateHeightsResponse\"@\x82\xd3\xe4\x93\x02:\x128/ibc/core/client/v1/consensus_states/{client_id}/heights\x12\xa2\x01\n" +
	"\fClientStatus\x12,.ibc.core.client.v1.QueryClientStatusRequest\x1a-.ibc.core.client.v1.QueryClientStatusResponse\"5\x82\xd3\xe4\x93\x02/\x12-/ibc/core/client/v1/client_status/{client_id}\x12\x8f\x01\n" +
	"\fClientParams\x12,.ibc.core.client.v1.QueryClientParamsRequest\x1a-.ibc.core.client.v1.QueryClientParamsResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/ibc/core/client/v1/params\x12\xa6\x01\n" +
	"\rClientCreator\x12-.ibc.core.client.v1.QueryClientCreatorRequest\x1a..ibc.core.client.v1.QueryClientCreatorResponse\"6\x82\xd3\xe4\x93\x020\x12./ibc/core/client/v1/client_creator/{client_id}\x12\xb4\x01\n" +
	"\x13UpgradedClientState\x123.ibc.core.client.v1.QueryUpgradedClientStateRequest\x1a4.ibc.core.client.v1.QueryUpgradedClientStateResponse\"2\x82\xd3\xe4\x93\x02,\x12*/ibc/core/client/v1/upgraded_client_states\x12\xc0\x01\n" +
	"\x16UpgradedConsensusState\x126.ibc.core.client.v1.QueryUpgradedConsensusStateRequest\x1a7.ibc.core.client.v1.QueryUpgradedConsensusStateResponse\"5\x82\xd3\xe4\x93\x02/\x12-/ibc/core/client/v1/upgraded_consensus_states\x12\xae\x01\n" +
	"\x10VerifyMembership\x120.ibc.core.client.v1.QueryVerifyMembershipRequest\x1a1.ibc.core.client.v1.QueryVerifyMembershipResponse\"5\x88\xe7\xb0*\x01\x82\xd3\xe4\x93\x02*:\x01*\"%/ibc/core/client/v1/verify_membershipB\xca\x01\n" +
	"\x16com.ibc.core.client.v1B\n" +
	"QueryProtoP\x01Z9github.com/drpcorg/public/pkg/ibc/core/client/v1;clientv1\xa2\x02\x03ICC\xaa\x02\x12Ibc.Core.Client.V1\xca\x02\x12Ibc\\Core\\Client\\V1\xe2\x02\x1eIbc\\Core\\Client\\V1\\GPBMetadata\xea\x02\x15Ibc::Core::Client::V1b\x06proto3"

var (
	file_ibc_core_client_v1_query_proto_rawDescOnce sync.Once
	file_ibc_core_client_v1_query_proto_rawDescData []byte
)

func file_ibc_core_client_v1_query_proto_rawDescGZIP() []byte {
	file_ibc_core_client_v1_query_proto_rawDescOnce.Do(func() {
		file_ibc_core_client_v1_query_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ibc_core_client_v1_query_proto_rawDesc), len(file_ibc_core_client_v1_query_proto_rawDesc)))
	})
	return file_ibc_core_client_v1_query_proto_rawDescData
}

var file_ibc_core_client_v1_query_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_ibc_core_client_v1_query_proto_goTypes = []any{
	(*QueryClientStateRequest)(nil),             // 0: ibc.core.client.v1.QueryClientStateRequest
	(*QueryClientStateResponse)(nil),            // 1: ibc.core.client.v1.QueryClientStateResponse
	(*QueryClientStatesRequest)(nil),            // 2: ibc.core.client.v1.QueryClientStatesRequest
	(*QueryClientStatesResponse)(nil),           // 3: ibc.core.client.v1.QueryClientStatesResponse
	(*QueryConsensusStateRequest)(nil),          // 4: ibc.core.client.v1.QueryConsensusStateRequest
	(*QueryConsensusStateResponse)(nil),         // 5: ibc.core.client.v1.QueryConsensusStateResponse
	(*QueryConsensusStatesRequest)(nil),         // 6: ibc.core.client.v1.QueryConsensusStatesRequest
	(*QueryConsensusStatesResponse)(nil),        // 7: ibc.core.client.v1.QueryConsensusStatesResponse
	(*QueryConsensusStateHeightsRequest)(nil),   // 8: ibc.core.client.v1.QueryConsensusStateHeightsRequest
	(*QueryConsensusStateHeightsResponse)(nil),  // 9: ibc.core.client.v1.QueryConsensusStateHeightsResponse
	(*QueryClientStatusRequest)(nil),            // 10: ibc.core.client.v1.QueryClientStatusRequest
	(*QueryClientStatusResponse)(nil),           // 11: ibc.core.client.v1.QueryClientStatusResponse
	(*QueryClientParamsRequest)(nil),            // 12: ibc.core.client.v1.QueryClientParamsRequest
	(*QueryClientParamsResponse)(nil),           // 13: ibc.core.client.v1.QueryClientParamsResponse
	(*QueryClientCreatorRequest)(nil),           // 14: ibc.core.client.v1.QueryClientCreatorRequest
	(*QueryClientCreatorResponse)(nil),          // 15: ibc.core.client.v1.QueryClientCreatorResponse
	(*QueryUpgradedClientStateRequest)(nil),     // 16: ibc.core.client.v1.QueryUpgradedClientStateRequest
	(*QueryUpgradedClientStateResponse)(nil),    // 17: ibc.core.client.v1.QueryUpgradedClientStateResponse
	(*QueryUpgradedConsensusStateRequest)(nil),  // 18: ibc.core.client.v1.QueryUpgradedConsensusStateRequest
	(*QueryUpgradedConsensusStateResponse)(nil), // 19: ibc.core.client.v1.QueryUpgradedConsensusStateResponse
	(*QueryVerifyMembershipRequest)(nil),        // 20: ibc.core.client.v1.QueryVerifyMembershipRequest
	(*QueryVerifyMembershipResponse)(nil),       // 21: ibc.core.client.v1.QueryVerifyMembershipResponse
	(*anypb.Any)(nil),                           // 22: google.protobuf.Any
	(*Height)(nil),                              // 23: ibc.core.client.v1.Height
	(*v1beta1.PageRequest)(nil),                 // 24: cosmos.base.query.v1beta1.PageRequest
	(*IdentifiedClientState)(nil),               // 25: ibc.core.client.v1.IdentifiedClientState
	(*v1beta1.PageResponse)(nil),                // 26: cosmos.base.query.v1beta1.PageResponse
	(*ConsensusStateWithHeight)(nil),            // 27: ibc.core.client.v1.ConsensusStateWithHeight
	(*Params)(nil),                              // 28: ibc.core.client.v1.Params
	(*v2.MerklePath)(nil),                       // 29: ibc.core.commitment.v2.MerklePath
}
var file_ibc_core_client_v1_query_proto_depIdxs = []int32{
	22, // 0: ibc.core.client.v1.QueryClientStateResponse.client_state:type_name -> google.protobuf.Any
	23, // 1: ibc.core.client.v1.QueryClientStateResponse.proof_height:type_name -> ibc.core.client.v1.Height
	24, // 2: ibc.core.client.v1.QueryClientStatesRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	25, // 3: ibc.core.client.v1.QueryClientStatesResponse.client_states:type_name -> ibc.core.client.v1.IdentifiedClientState
	26, // 4: ibc.core.client.v1.QueryClientStatesResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	22, // 5: ibc.core.client.v1.QueryConsensusStateResponse.consensus_state:type_name -> google.protobuf.Any
	23, // 6: ibc.core.client.v1.QueryConsensusStateResponse.proof_height:type_name -> ibc.core.client.v1.Height
	24, // 7: ibc.core.client.v1.QueryConsensusStatesRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	27, // 8: ibc.core.client.v1.QueryConsensusStatesResponse.consensus_states:type_name -> ibc.core.client.v1.ConsensusStateWithHeight
	26, // 9: ibc.core.client.v1.QueryConsensusStatesResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	24, // 10: ibc.core.client.v1.QueryConsensusStateHeightsRequest.pagination:type_name -> cosmos.base.query.v1beta1.PageRequest
	23, // 11: ibc.core.client.v1.QueryConsensusStateHeightsResponse.consensus_state_heights:type_name -> ibc.core.client.v1.Height
	26, // 12: ibc.core.client.v1.QueryConsensusStateHeightsResponse.pagination:type_name -> cosmos.base.query.v1beta1.PageResponse
	28, // 13: ibc.core.client.v1.QueryClientParamsResponse.params:type_name -> ibc.core.client.v1.Params
	22, // 14: ibc.core.client.v1.QueryUpgradedClientStateResponse.upgraded_client_state:type_name -> google.protobuf.Any
	22, // 15: ibc.core.client.v1.QueryUpgradedConsensusStateResponse.upgraded_consensus_state:type_name -> google.protobuf.Any
	23, // 16: ibc.core.client.v1.QueryVerifyMembershipRequest.proof_height:type_name -> ibc.core.client.v1.Height
	29, // 17: ibc.core.client.v1.QueryVerifyMembershipRequest.merkle_path:type_name -> ibc.core.commitment.v2.MerklePath
	0,  // 18: ibc.core.client.v1.Query.ClientState:input_type -> ibc.core.client.v1.QueryClientStateRequest
	2,  // 19: ibc.core.client.v1.Query.ClientStates:input_type -> ibc.core.client.v1.QueryClientStatesRequest
	4,  // 20: ibc.core.client.v1.Query.ConsensusState:input_type -> ibc.core.client.v1.QueryConsensusStateRequest
	6,  // 21: ibc.core.client.v1.Query.ConsensusStates:input_type -> ibc.core.client.v1.QueryConsensusStatesRequest
	8,  // 22: ibc.core.client.v1.Query.ConsensusStateHeights:input_type -> ibc.core.client.v1.QueryConsensusStateHeightsRequest
	10, // 23: ibc.core.client.v1.Query.ClientStatus:input_type -> ibc.core.client.v1.QueryClientStatusRequest
	12, // 24: ibc.core.client.v1.Query.ClientParams:input_type -> ibc.core.client.v1.QueryClientParamsRequest
	14, // 25: ibc.core.client.v1.Query.ClientCreator:input_type -> ibc.core.client.v1.QueryClientCreatorRequest
	16, // 26: ibc.core.client.v1.Query.UpgradedClientState:input_type -> ibc.core.client.v1.QueryUpgradedClientStateRequest
	18, // 27: ibc.core.client.v1.Query.UpgradedConsensusState:input_type -> ibc.core.client.v1.QueryUpgradedConsensusStateRequest
	20, // 28: ibc.core.client.v1.Query.VerifyMembership:input_type -> ibc.core.client.v1.QueryVerifyMembershipRequest
	1,  // 29: ibc.core.client.v1.Query.ClientState:output_type -> ibc.core.client.v1.QueryClientStateResponse
	3,  // 30: ibc.core.client.v1.Query.ClientStates:output_type -> ibc.core.client.v1.QueryClientStatesResponse
	5,  // 31: ibc.core.client.v1.Query.ConsensusState:output_type -> ibc.core.client.v1.QueryConsensusStateResponse
	7,  // 32: ibc.core.client.v1.Query.ConsensusStates:output_type -> ibc.core.client.v1.QueryConsensusStatesResponse
	9,  // 33: ibc.core.client.v1.Query.ConsensusStateHeights:output_type -> ibc.core.client.v1.QueryConsensusStateHeightsResponse
	11, // 34: ibc.core.client.v1.Query.ClientStatus:output_type -> ibc.core.client.v1.QueryClientStatusResponse
	13, // 35: ibc.core.client.v1.Query.ClientParams:output_type -> ibc.core.client.v1.QueryClientParamsResponse
	15, // 36: ibc.core.client.v1.Query.ClientCreator:output_type -> ibc.core.client.v1.QueryClientCreatorResponse
	17, // 37: ibc.core.client.v1.Query.UpgradedClientState:output_type -> ibc.core.client.v1.QueryUpgradedClientStateResponse
	19, // 38: ibc.core.client.v1.Query.UpgradedConsensusState:output_type -> ibc.core.client.v1.QueryUpgradedConsensusStateResponse
	21, // 39: ibc.core.client.v1.Query.VerifyMembership:output_type -> ibc.core.client.v1.QueryVerifyMembershipResponse
	29, // [29:40] is the sub-list for method output_type
	18, // [18:29] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_ibc_core_client_v1_query_proto_init() }
func file_ibc_core_client_v1_query_proto_init() {
	if File_ibc_core_client_v1_query_proto != nil {
		return
	}
	file_ibc_core_client_v1_client_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ibc_core_client_v1_query_proto_rawDesc), len(file_ibc_core_client_v1_query_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ibc_core_client_v1_query_proto_goTypes,
		DependencyIndexes: file_ibc_core_client_v1_query_proto_depIdxs,
		MessageInfos:      file_ibc_core_client_v1_query_proto_msgTypes,
	}.Build()
	File_ibc_core_client_v1_query_proto = out.File
	file_ibc_core_client_v1_query_proto_goTypes = nil
	file_ibc_core_client_v1_query_proto_depIdxs = nil
}
