// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: celestia/zkism/v1/tx.proto

package zkismv1

import (
	_ "cosmossdk.io/api/cosmos/msg/v1"
	_ "github.com/drpcorg/public/pkg/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MsgCreateInterchainSecurityModule is the request type for CreateInterchainSecurityModule.
type MsgCreateInterchainSecurityModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// creator is the message sender.
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	// initial trusted state
	State []byte `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// merkle tree address in byte32 format
	MerkleTreeAddress []byte `protobuf:"bytes,3,opt,name=merkle_tree_address,json=merkleTreeAddress,proto3" json:"merkle_tree_address,omitempty"`
	// the sp1 groth16 verifier key
	Groth16Vkey []byte `protobuf:"bytes,4,opt,name=groth16_vkey,json=groth16Vkey,proto3" json:"groth16_vkey,omitempty"`
	// hash-based commitment to the verifier key used for state transition
	StateTransitionVkey []byte `protobuf:"bytes,5,opt,name=state_transition_vkey,json=stateTransitionVkey,proto3" json:"state_transition_vkey,omitempty"`
	// hash-based commitment to the verifier key used for state membership
	StateMembershipVkey []byte `protobuf:"bytes,6,opt,name=state_membership_vkey,json=stateMembershipVkey,proto3" json:"state_membership_vkey,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MsgCreateInterchainSecurityModule) Reset() {
	*x = MsgCreateInterchainSecurityModule{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateInterchainSecurityModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateInterchainSecurityModule) ProtoMessage() {}

func (x *MsgCreateInterchainSecurityModule) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateInterchainSecurityModule.ProtoReflect.Descriptor instead.
func (*MsgCreateInterchainSecurityModule) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{0}
}

func (x *MsgCreateInterchainSecurityModule) GetCreator() string {
	if x != nil {
		return x.Creator
	}
	return ""
}

func (x *MsgCreateInterchainSecurityModule) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *MsgCreateInterchainSecurityModule) GetMerkleTreeAddress() []byte {
	if x != nil {
		return x.MerkleTreeAddress
	}
	return nil
}

func (x *MsgCreateInterchainSecurityModule) GetGroth16Vkey() []byte {
	if x != nil {
		return x.Groth16Vkey
	}
	return nil
}

func (x *MsgCreateInterchainSecurityModule) GetStateTransitionVkey() []byte {
	if x != nil {
		return x.StateTransitionVkey
	}
	return nil
}

func (x *MsgCreateInterchainSecurityModule) GetStateMembershipVkey() []byte {
	if x != nil {
		return x.StateMembershipVkey
	}
	return nil
}

// MsgCreateInterchainSecurityModuleResponse is the response type for CreateInterchainSecurityModule.
type MsgCreateInterchainSecurityModuleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgCreateInterchainSecurityModuleResponse) Reset() {
	*x = MsgCreateInterchainSecurityModuleResponse{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgCreateInterchainSecurityModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgCreateInterchainSecurityModuleResponse) ProtoMessage() {}

func (x *MsgCreateInterchainSecurityModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgCreateInterchainSecurityModuleResponse.ProtoReflect.Descriptor instead.
func (*MsgCreateInterchainSecurityModuleResponse) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{1}
}

func (x *MsgCreateInterchainSecurityModuleResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// MsgUpdateInterchainSecurityModule is the request type for UpdateInterchainSecurityModule.
type MsgUpdateInterchainSecurityModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ism identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// proof is the ZK proof bytes (groth16).
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// the public values used for proof verification.
	PublicValues []byte `protobuf:"bytes,3,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	// the tx signer address
	Signer        string `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateInterchainSecurityModule) Reset() {
	*x = MsgUpdateInterchainSecurityModule{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateInterchainSecurityModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateInterchainSecurityModule) ProtoMessage() {}

func (x *MsgUpdateInterchainSecurityModule) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateInterchainSecurityModule.ProtoReflect.Descriptor instead.
func (*MsgUpdateInterchainSecurityModule) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{2}
}

func (x *MsgUpdateInterchainSecurityModule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgUpdateInterchainSecurityModule) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgUpdateInterchainSecurityModule) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *MsgUpdateInterchainSecurityModule) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

// MsgUpdateInterchainSecurityModuleResponse is the response type for UpdateInterchainSecurityModule.
type MsgUpdateInterchainSecurityModuleResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// new ism state
	State         []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgUpdateInterchainSecurityModuleResponse) Reset() {
	*x = MsgUpdateInterchainSecurityModuleResponse{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgUpdateInterchainSecurityModuleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgUpdateInterchainSecurityModuleResponse) ProtoMessage() {}

func (x *MsgUpdateInterchainSecurityModuleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgUpdateInterchainSecurityModuleResponse.ProtoReflect.Descriptor instead.
func (*MsgUpdateInterchainSecurityModuleResponse) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{3}
}

func (x *MsgUpdateInterchainSecurityModuleResponse) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

// MsgSubmitMessages is the request type for SubmitMessages.
type MsgSubmitMessages struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ism identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// proof is the ZK proof bytes (groth16).
	Proof []byte `protobuf:"bytes,2,opt,name=proof,proto3" json:"proof,omitempty"`
	// the public values used for proof verification.
	PublicValues []byte `protobuf:"bytes,3,opt,name=public_values,json=publicValues,proto3" json:"public_values,omitempty"`
	// the tx signer address
	Signer        string `protobuf:"bytes,4,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitMessages) Reset() {
	*x = MsgSubmitMessages{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitMessages) ProtoMessage() {}

func (x *MsgSubmitMessages) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitMessages.ProtoReflect.Descriptor instead.
func (*MsgSubmitMessages) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{4}
}

func (x *MsgSubmitMessages) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MsgSubmitMessages) GetProof() []byte {
	if x != nil {
		return x.Proof
	}
	return nil
}

func (x *MsgSubmitMessages) GetPublicValues() []byte {
	if x != nil {
		return x.PublicValues
	}
	return nil
}

func (x *MsgSubmitMessages) GetSigner() string {
	if x != nil {
		return x.Signer
	}
	return ""
}

// MsgSubmitMessagesResponse is the response type for SubmitMessages.
type MsgSubmitMessagesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// state commitment root used to verify messages (hex-encoded)
	StateRoot string `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	// list of authorized messages ids
	Messages      []string `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgSubmitMessagesResponse) Reset() {
	*x = MsgSubmitMessagesResponse{}
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgSubmitMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgSubmitMessagesResponse) ProtoMessage() {}

func (x *MsgSubmitMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_tx_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgSubmitMessagesResponse.ProtoReflect.Descriptor instead.
func (*MsgSubmitMessagesResponse) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_tx_proto_rawDescGZIP(), []int{5}
}

func (x *MsgSubmitMessagesResponse) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *MsgSubmitMessagesResponse) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

var File_celestia_zkism_v1_tx_proto protoreflect.FileDescriptor

const file_celestia_zkism_v1_tx_proto_rawDesc = "" +
	"\n" +
	"\x1acelestia/zkism/v1/tx.proto\x12\x11celestia.zkism.v1\x1a\x17cosmos/msg/v1/msg.proto\x1a\x14gogoproto/gogo.proto\"\x9c\x02\n" +
	"!MsgCreateInterchainSecurityModule\x12\x18\n" +
	"\acreator\x18\x01 \x01(\tR\acreator\x12\x14\n" +
	"\x05state\x18\x02 \x01(\fR\x05state\x12.\n" +
	"\x13merkle_tree_address\x18\x03 \x01(\fR\x11merkleTreeAddress\x12!\n" +
	"\fgroth16_vkey\x18\x04 \x01(\fR\vgroth16Vkey\x122\n" +
	"\x15state_transition_vkey\x18\x05 \x01(\fR\x13stateTransitionVkey\x122\n" +
	"\x15state_membership_vkey\x18\x06 \x01(\fR\x13stateMembershipVkey:\f\x82\xe7\xb0*\acreator\"\x80\x01\n" +
	")MsgCreateInterchainSecurityModuleResponse\x12S\n" +
	"\x02id\x18\x01 \x01(\tBC\xc8\xde\x1f\x00\xda\xde\x1f;github.com/bcp-innovations/hyperlane-cosmos/util.HexAddressR\x02id\"\xd8\x01\n" +
	"!MsgUpdateInterchainSecurityModule\x12S\n" +
	"\x02id\x18\x01 \x01(\tBC\xc8\xde\x1f\x00\xda\xde\x1f;github.com/bcp-innovations/hyperlane-cosmos/util.HexAddressR\x02id\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12#\n" +
	"\rpublic_values\x18\x03 \x01(\fR\fpublicValues\x12\x16\n" +
	"\x06signer\x18\x04 \x01(\tR\x06signer:\v\x82\xe7\xb0*\x06signer\"A\n" +
	")MsgUpdateInterchainSecurityModuleResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\fR\x05state\"\xc8\x01\n" +
	"\x11MsgSubmitMessages\x12S\n" +
	"\x02id\x18\x01 \x01(\tBC\xc8\xde\x1f\x00\xda\xde\x1f;github.com/bcp-innovations/hyperlane-cosmos/util.HexAddressR\x02id\x12\x14\n" +
	"\x05proof\x18\x02 \x01(\fR\x05proof\x12#\n" +
	"\rpublic_values\x18\x03 \x01(\fR\fpublicValues\x12\x16\n" +
	"\x06signer\x18\x04 \x01(\tR\x06signer:\v\x82\xe7\xb0*\x06signer\"V\n" +
	"\x19MsgSubmitMessagesResponse\x12\x1d\n" +
	"\n" +
	"state_root\x18\x01 \x01(\tR\tstateRoot\x12\x1a\n" +
	"\bmessages\x18\x02 \x03(\tR\bmessages2\xa0\x03\n" +
	"\x03Msg\x12\x94\x01\n" +
	"\x1eCreateInterchainSecurityModule\x124.celestia.zkism.v1.MsgCreateInterchainSecurityModule\x1a<.celestia.zkism.v1.MsgCreateInterchainSecurityModuleResponse\x12\x94\x01\n" +
	"\x1eUpdateInterchainSecurityModule\x124.celestia.zkism.v1.MsgUpdateInterchainSecurityModule\x1a<.celestia.zkism.v1.MsgUpdateInterchainSecurityModuleResponse\x12d\n" +
	"\x0eSubmitMessages\x12$.celestia.zkism.v1.MsgSubmitMessages\x1a,.celestia.zkism.v1.MsgSubmitMessagesResponse\x1a\x05\x80\xe7\xb0*\x01B\xbf\x01\n" +
	"\x15com.celestia.zkism.v1B\aTxProtoP\x01Z7github.com/drpcorg/public/pkg/celestia/zkism/v1;zkismv1\xa2\x02\x03CZX\xaa\x02\x11Celestia.Zkism.V1\xca\x02\x11Celestia\\Zkism\\V1\xe2\x02\x1dCelestia\\Zkism\\V1\\GPBMetadata\xea\x02\x13Celestia::Zkism::V1b\x06proto3"

var (
	file_celestia_zkism_v1_tx_proto_rawDescOnce sync.Once
	file_celestia_zkism_v1_tx_proto_rawDescData []byte
)

func file_celestia_zkism_v1_tx_proto_rawDescGZIP() []byte {
	file_celestia_zkism_v1_tx_proto_rawDescOnce.Do(func() {
		file_celestia_zkism_v1_tx_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_celestia_zkism_v1_tx_proto_rawDesc), len(file_celestia_zkism_v1_tx_proto_rawDesc)))
	})
	return file_celestia_zkism_v1_tx_proto_rawDescData
}

var file_celestia_zkism_v1_tx_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_celestia_zkism_v1_tx_proto_goTypes = []any{
	(*MsgCreateInterchainSecurityModule)(nil),         // 0: celestia.zkism.v1.MsgCreateInterchainSecurityModule
	(*MsgCreateInterchainSecurityModuleResponse)(nil), // 1: celestia.zkism.v1.MsgCreateInterchainSecurityModuleResponse
	(*MsgUpdateInterchainSecurityModule)(nil),         // 2: celestia.zkism.v1.MsgUpdateInterchainSecurityModule
	(*MsgUpdateInterchainSecurityModuleResponse)(nil), // 3: celestia.zkism.v1.MsgUpdateInterchainSecurityModuleResponse
	(*MsgSubmitMessages)(nil),                         // 4: celestia.zkism.v1.MsgSubmitMessages
	(*MsgSubmitMessagesResponse)(nil),                 // 5: celestia.zkism.v1.MsgSubmitMessagesResponse
}
var file_celestia_zkism_v1_tx_proto_depIdxs = []int32{
	0, // 0: celestia.zkism.v1.Msg.CreateInterchainSecurityModule:input_type -> celestia.zkism.v1.MsgCreateInterchainSecurityModule
	2, // 1: celestia.zkism.v1.Msg.UpdateInterchainSecurityModule:input_type -> celestia.zkism.v1.MsgUpdateInterchainSecurityModule
	4, // 2: celestia.zkism.v1.Msg.SubmitMessages:input_type -> celestia.zkism.v1.MsgSubmitMessages
	1, // 3: celestia.zkism.v1.Msg.CreateInterchainSecurityModule:output_type -> celestia.zkism.v1.MsgCreateInterchainSecurityModuleResponse
	3, // 4: celestia.zkism.v1.Msg.UpdateInterchainSecurityModule:output_type -> celestia.zkism.v1.MsgUpdateInterchainSecurityModuleResponse
	5, // 5: celestia.zkism.v1.Msg.SubmitMessages:output_type -> celestia.zkism.v1.MsgSubmitMessagesResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_celestia_zkism_v1_tx_proto_init() }
func file_celestia_zkism_v1_tx_proto_init() {
	if File_celestia_zkism_v1_tx_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_celestia_zkism_v1_tx_proto_rawDesc), len(file_celestia_zkism_v1_tx_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_celestia_zkism_v1_tx_proto_goTypes,
		DependencyIndexes: file_celestia_zkism_v1_tx_proto_depIdxs,
		MessageInfos:      file_celestia_zkism_v1_tx_proto_msgTypes,
	}.Build()
	File_celestia_zkism_v1_tx_proto = out.File
	file_celestia_zkism_v1_tx_proto_goTypes = nil
	file_celestia_zkism_v1_tx_proto_depIdxs = nil
}
