// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: celestia/zkism/v1/types.proto

package zkismv1

import (
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/drpcorg/public/pkg/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InterchainSecurityModule defines the Hyperlane interchain security module (ISM).
type InterchainSecurityModule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// unique hyperlane identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// the owner or creator of the ism
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// current state
	State []byte `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// merkle tree address in bytes32 format
	MerkleTreeAddress []byte `protobuf:"bytes,4,opt,name=merkle_tree_address,json=merkleTreeAddress,proto3" json:"merkle_tree_address,omitempty"`
	// the sp1 groth16 verifier key
	Groth16Vkey []byte `protobuf:"bytes,5,opt,name=groth16_vkey,json=groth16Vkey,proto3" json:"groth16_vkey,omitempty"`
	// hash-based commitment to the verifier key used for state transition
	StateTransitionVkey []byte `protobuf:"bytes,6,opt,name=state_transition_vkey,json=stateTransitionVkey,proto3" json:"state_transition_vkey,omitempty"`
	// hash-based commitment to the verifier key used for state membership
	StateMembershipVkey []byte `protobuf:"bytes,7,opt,name=state_membership_vkey,json=stateMembershipVkey,proto3" json:"state_membership_vkey,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *InterchainSecurityModule) Reset() {
	*x = InterchainSecurityModule{}
	mi := &file_celestia_zkism_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterchainSecurityModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterchainSecurityModule) ProtoMessage() {}

func (x *InterchainSecurityModule) ProtoReflect() protoreflect.Message {
	mi := &file_celestia_zkism_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterchainSecurityModule.ProtoReflect.Descriptor instead.
func (*InterchainSecurityModule) Descriptor() ([]byte, []int) {
	return file_celestia_zkism_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *InterchainSecurityModule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InterchainSecurityModule) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *InterchainSecurityModule) GetState() []byte {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *InterchainSecurityModule) GetMerkleTreeAddress() []byte {
	if x != nil {
		return x.MerkleTreeAddress
	}
	return nil
}

func (x *InterchainSecurityModule) GetGroth16Vkey() []byte {
	if x != nil {
		return x.Groth16Vkey
	}
	return nil
}

func (x *InterchainSecurityModule) GetStateTransitionVkey() []byte {
	if x != nil {
		return x.StateTransitionVkey
	}
	return nil
}

func (x *InterchainSecurityModule) GetStateMembershipVkey() []byte {
	if x != nil {
		return x.StateMembershipVkey
	}
	return nil
}

var File_celestia_zkism_v1_types_proto protoreflect.FileDescriptor

const file_celestia_zkism_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x1dcelestia/zkism/v1/types.proto\x12\x11celestia.zkism.v1\x1a\x19cosmos_proto/cosmos.proto\x1a\x14gogoproto/gogo.proto\"\xf6\x02\n" +
	"\x18InterchainSecurityModule\x12S\n" +
	"\x02id\x18\x01 \x01(\tBC\xc8\xde\x1f\x00\xda\xde\x1f;github.com/bcp-innovations/hyperlane-cosmos/util.HexAddressR\x02id\x12.\n" +
	"\x05owner\x18\x02 \x01(\tB\x18Ҵ-\x14cosmos.AddressStringR\x05owner\x12\x14\n" +
	"\x05state\x18\x03 \x01(\fR\x05state\x12.\n" +
	"\x13merkle_tree_address\x18\x04 \x01(\fR\x11merkleTreeAddress\x12!\n" +
	"\fgroth16_vkey\x18\x05 \x01(\fR\vgroth16Vkey\x122\n" +
	"\x15state_transition_vkey\x18\x06 \x01(\fR\x13stateTransitionVkey\x122\n" +
	"\x15state_membership_vkey\x18\a \x01(\fR\x13stateMembershipVkey:\x04\x88\xa0\x1f\x00B\xc2\x01\n" +
	"\x15com.celestia.zkism.v1B\n" +
	"TypesProtoP\x01Z7github.com/drpcorg/public/pkg/celestia/zkism/v1;zkismv1\xa2\x02\x03CZX\xaa\x02\x11Celestia.Zkism.V1\xca\x02\x11Celestia\\Zkism\\V1\xe2\x02\x1dCelestia\\Zkism\\V1\\GPBMetadata\xea\x02\x13Celestia::Zkism::V1b\x06proto3"

var (
	file_celestia_zkism_v1_types_proto_rawDescOnce sync.Once
	file_celestia_zkism_v1_types_proto_rawDescData []byte
)

func file_celestia_zkism_v1_types_proto_rawDescGZIP() []byte {
	file_celestia_zkism_v1_types_proto_rawDescOnce.Do(func() {
		file_celestia_zkism_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_celestia_zkism_v1_types_proto_rawDesc), len(file_celestia_zkism_v1_types_proto_rawDesc)))
	})
	return file_celestia_zkism_v1_types_proto_rawDescData
}

var file_celestia_zkism_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_celestia_zkism_v1_types_proto_goTypes = []any{
	(*InterchainSecurityModule)(nil), // 0: celestia.zkism.v1.InterchainSecurityModule
}
var file_celestia_zkism_v1_types_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_celestia_zkism_v1_types_proto_init() }
func file_celestia_zkism_v1_types_proto_init() {
	if File_celestia_zkism_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_celestia_zkism_v1_types_proto_rawDesc), len(file_celestia_zkism_v1_types_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_celestia_zkism_v1_types_proto_goTypes,
		DependencyIndexes: file_celestia_zkism_v1_types_proto_depIdxs,
		MessageInfos:      file_celestia_zkism_v1_types_proto_msgTypes,
	}.Build()
	File_celestia_zkism_v1_types_proto = out.File
	file_celestia_zkism_v1_types_proto_goTypes = nil
	file_celestia_zkism_v1_types_proto_depIdxs = nil
}
