// Copyright (c) Mysten Labs, Inc.
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: sui/rpc/v2/filter.proto

package sui

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DNF filter for transactions: any term may match, and each term is an AND
// of signed literals.
// An absent filter matches everything. A present filter must have at least one
// term.
type TransactionFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terms are ORed together.
	Terms         []*TransactionTerm `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionFilter) Reset() {
	*x = TransactionFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFilter) ProtoMessage() {}

func (x *TransactionFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFilter.ProtoReflect.Descriptor instead.
func (*TransactionFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionFilter) GetTerms() []*TransactionTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

// One conjunction in a transaction DNF filter.
type TransactionTerm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Literals are ANDed together.
	Literals      []*TransactionLiteral `protobuf:"bytes,1,rep,name=literals,proto3" json:"literals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionTerm) Reset() {
	*x = TransactionTerm{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionTerm) ProtoMessage() {}

func (x *TransactionTerm) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionTerm.ProtoReflect.Descriptor instead.
func (*TransactionTerm) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionTerm) GetLiterals() []*TransactionLiteral {
	if x != nil {
		return x.Literals
	}
	return nil
}

// One signed transaction predicate literal: a predicate, optionally negated.
type TransactionLiteral struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, the literal matches transactions that the predicate does *not*
	// match.
	Negated bool `protobuf:"varint,1,opt,name=negated,proto3" json:"negated,omitempty"`
	// The transaction-index predicate to match.
	//
	// Types that are valid to be assigned to Predicate:
	//
	//	*TransactionLiteral_Sender
	//	*TransactionLiteral_AffectedAddress
	//	*TransactionLiteral_AffectedObject
	//	*TransactionLiteral_MoveCall
	//	*TransactionLiteral_EmitModule
	//	*TransactionLiteral_EventType
	//	*TransactionLiteral_EventStreamHead
	//	*TransactionLiteral_PackageWrite
	Predicate     isTransactionLiteral_Predicate `protobuf_oneof:"predicate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionLiteral) Reset() {
	*x = TransactionLiteral{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionLiteral) ProtoMessage() {}

func (x *TransactionLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionLiteral.ProtoReflect.Descriptor instead.
func (*TransactionLiteral) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{2}
}

func (x *TransactionLiteral) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

func (x *TransactionLiteral) GetPredicate() isTransactionLiteral_Predicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *TransactionLiteral) GetSender() *SenderFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_Sender); ok {
			return x.Sender
		}
	}
	return nil
}

func (x *TransactionLiteral) GetAffectedAddress() *AffectedAddressFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_AffectedAddress); ok {
			return x.AffectedAddress
		}
	}
	return nil
}

func (x *TransactionLiteral) GetAffectedObject() *AffectedObjectFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_AffectedObject); ok {
			return x.AffectedObject
		}
	}
	return nil
}

func (x *TransactionLiteral) GetMoveCall() *MoveCallFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_MoveCall); ok {
			return x.MoveCall
		}
	}
	return nil
}

func (x *TransactionLiteral) GetEmitModule() *EmitModuleFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_EmitModule); ok {
			return x.EmitModule
		}
	}
	return nil
}

func (x *TransactionLiteral) GetEventType() *EventTypeFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_EventType); ok {
			return x.EventType
		}
	}
	return nil
}

func (x *TransactionLiteral) GetEventStreamHead() *EventStreamHeadFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_EventStreamHead); ok {
			return x.EventStreamHead
		}
	}
	return nil
}

func (x *TransactionLiteral) GetPackageWrite() *PackageWriteFilter {
	if x != nil {
		if x, ok := x.Predicate.(*TransactionLiteral_PackageWrite); ok {
			return x.PackageWrite
		}
	}
	return nil
}

type isTransactionLiteral_Predicate interface {
	isTransactionLiteral_Predicate()
}

type TransactionLiteral_Sender struct {
	// Match transactions sent by the specified address.
	Sender *SenderFilter `protobuf:"bytes,2,opt,name=sender,proto3,oneof"`
}

type TransactionLiteral_AffectedAddress struct {
	// Match transactions where the specified address's state moved as a side
	// effect: it owns an object after the txn, owned an object before the
	// txn that was mutated/transferred away/deleted/wrapped, or its
	// address-balance changed via an accumulator event.
	AffectedAddress *AffectedAddressFilter `protobuf:"bytes,3,opt,name=affected_address,json=affectedAddress,proto3,oneof"`
}

type TransactionLiteral_AffectedObject struct {
	// Match transactions whose effects include a change for the specified
	// object.
	AffectedObject *AffectedObjectFilter `protobuf:"bytes,4,opt,name=affected_object,json=affectedObject,proto3,oneof"`
}

type TransactionLiteral_MoveCall struct {
	// Match transactions that made a Move call matching the specified filter.
	MoveCall *MoveCallFilter `protobuf:"bytes,5,opt,name=move_call,json=moveCall,proto3,oneof"`
}

type TransactionLiteral_EmitModule struct {
	// Match transactions that emitted an event whose package/module fields
	// match the specified filter.
	EmitModule *EmitModuleFilter `protobuf:"bytes,6,opt,name=emit_module,json=emitModule,proto3,oneof"`
}

type TransactionLiteral_EventType struct {
	// Match transactions that emitted an event with a type matching the
	// specified filter.
	EventType *EventTypeFilter `protobuf:"bytes,7,opt,name=event_type,json=eventType,proto3,oneof"`
}

type TransactionLiteral_EventStreamHead struct {
	// Match transactions that wrote to the specified authenticated event
	// stream head.
	EventStreamHead *EventStreamHeadFilter `protobuf:"bytes,8,opt,name=event_stream_head,json=eventStreamHead,proto3,oneof"`
}

type TransactionLiteral_PackageWrite struct {
	// Match transactions that wrote a Move package — a first publish or an
	// upgrade, of any package.
	PackageWrite *PackageWriteFilter `protobuf:"bytes,9,opt,name=package_write,json=packageWrite,proto3,oneof"`
}

func (*TransactionLiteral_Sender) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_AffectedAddress) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_AffectedObject) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_MoveCall) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EmitModule) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EventType) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_EventStreamHead) isTransactionLiteral_Predicate() {}

func (*TransactionLiteral_PackageWrite) isTransactionLiteral_Predicate() {}

// DNF filter for events: any term may match, and each term is an AND of
// signed literals. Sender predicates match all events from matching
// transactions; emit-module, event-type, and event-stream-head predicates match
// individual event-space dimensions. An absent filter matches everything. A
// present filter must have at least one term.
type EventFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Terms are ORed together.
	Terms         []*EventTerm `protobuf:"bytes,1,rep,name=terms,proto3" json:"terms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventFilter) Reset() {
	*x = EventFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventFilter) ProtoMessage() {}

func (x *EventFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventFilter.ProtoReflect.Descriptor instead.
func (*EventFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{3}
}

func (x *EventFilter) GetTerms() []*EventTerm {
	if x != nil {
		return x.Terms
	}
	return nil
}

// One conjunction in an event DNF filter.
type EventTerm struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Literals are ANDed together.
	Literals      []*EventLiteral `protobuf:"bytes,1,rep,name=literals,proto3" json:"literals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTerm) Reset() {
	*x = EventTerm{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTerm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTerm) ProtoMessage() {}

func (x *EventTerm) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTerm.ProtoReflect.Descriptor instead.
func (*EventTerm) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{4}
}

func (x *EventTerm) GetLiterals() []*EventLiteral {
	if x != nil {
		return x.Literals
	}
	return nil
}

// One signed event predicate literal: a predicate, optionally negated.
type EventLiteral struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// When true, the literal matches events that the predicate does *not* match.
	Negated bool `protobuf:"varint,1,opt,name=negated,proto3" json:"negated,omitempty"`
	// The event-index predicate to match.
	//
	// Types that are valid to be assigned to Predicate:
	//
	//	*EventLiteral_Sender
	//	*EventLiteral_EmitModule
	//	*EventLiteral_EventType
	//	*EventLiteral_EventStreamHead
	Predicate     isEventLiteral_Predicate `protobuf_oneof:"predicate"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventLiteral) Reset() {
	*x = EventLiteral{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventLiteral) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventLiteral) ProtoMessage() {}

func (x *EventLiteral) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventLiteral.ProtoReflect.Descriptor instead.
func (*EventLiteral) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{5}
}

func (x *EventLiteral) GetNegated() bool {
	if x != nil {
		return x.Negated
	}
	return false
}

func (x *EventLiteral) GetPredicate() isEventLiteral_Predicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

func (x *EventLiteral) GetSender() *SenderFilter {
	if x != nil {
		if x, ok := x.Predicate.(*EventLiteral_Sender); ok {
			return x.Sender
		}
	}
	return nil
}

func (x *EventLiteral) GetEmitModule() *EmitModuleFilter {
	if x != nil {
		if x, ok := x.Predicate.(*EventLiteral_EmitModule); ok {
			return x.EmitModule
		}
	}
	return nil
}

func (x *EventLiteral) GetEventType() *EventTypeFilter {
	if x != nil {
		if x, ok := x.Predicate.(*EventLiteral_EventType); ok {
			return x.EventType
		}
	}
	return nil
}

func (x *EventLiteral) GetEventStreamHead() *EventStreamHeadFilter {
	if x != nil {
		if x, ok := x.Predicate.(*EventLiteral_EventStreamHead); ok {
			return x.EventStreamHead
		}
	}
	return nil
}

type isEventLiteral_Predicate interface {
	isEventLiteral_Predicate()
}

type EventLiteral_Sender struct {
	// Match events from transactions sent by the specified address.
	Sender *SenderFilter `protobuf:"bytes,2,opt,name=sender,proto3,oneof"`
}

type EventLiteral_EmitModule struct {
	// Match events whose package/module fields match the specified filter.
	EmitModule *EmitModuleFilter `protobuf:"bytes,3,opt,name=emit_module,json=emitModule,proto3,oneof"`
}

type EventLiteral_EventType struct {
	// Match events whose type matches the specified filter.
	EventType *EventTypeFilter `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3,oneof"`
}

type EventLiteral_EventStreamHead struct {
	// Match events committed to the specified authenticated event stream head.
	EventStreamHead *EventStreamHeadFilter `protobuf:"bytes,5,opt,name=event_stream_head,json=eventStreamHead,proto3,oneof"`
}

func (*EventLiteral_Sender) isEventLiteral_Predicate() {}

func (*EventLiteral_EmitModule) isEventLiteral_Predicate() {}

func (*EventLiteral_EventType) isEventLiteral_Predicate() {}

func (*EventLiteral_EventStreamHead) isEventLiteral_Predicate() {}

// Match by transaction sender address.
type SenderFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sender address (hex-encoded).
	Address       *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SenderFilter) Reset() {
	*x = SenderFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SenderFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SenderFilter) ProtoMessage() {}

func (x *SenderFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SenderFilter.ProtoReflect.Descriptor instead.
func (*SenderFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{6}
}

func (x *SenderFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

// Match by any address whose state moved as a side effect of the
// transaction: object ownership changes (in either direction), prior
// owners of removed/wrapped objects, and address-balance changes via
// accumulator events.
type AffectedAddressFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The affected address (hex-encoded).
	Address       *string `protobuf:"bytes,1,opt,name=address,proto3,oneof" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedAddressFilter) Reset() {
	*x = AffectedAddressFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedAddressFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedAddressFilter) ProtoMessage() {}

func (x *AffectedAddressFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedAddressFilter.ProtoReflect.Descriptor instead.
func (*AffectedAddressFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{7}
}

func (x *AffectedAddressFilter) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

// Match by changed object ID.
type AffectedObjectFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The changed object ID (hex-encoded).
	ObjectId      *string `protobuf:"bytes,1,opt,name=object_id,json=objectId,proto3,oneof" json:"object_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AffectedObjectFilter) Reset() {
	*x = AffectedObjectFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AffectedObjectFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AffectedObjectFilter) ProtoMessage() {}

func (x *AffectedObjectFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AffectedObjectFilter.ProtoReflect.Descriptor instead.
func (*AffectedObjectFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{8}
}

func (x *AffectedObjectFilter) GetObjectId() string {
	if x != nil && x.ObjectId != nil {
		return *x.ObjectId
	}
	return ""
}

// Match by Move function call, specified as a `::`-delimited Move path.
//
// Specificity levels:
//
//	"0xpkg"                        -> matches any call in the package
//	"0xpkg::module"                -> matches any call in the module
//	"0xpkg::module::function"      -> matches calls to the exact function
type MoveCallFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Move path of the form `package[::module[::function]]`.
	Function      *string `protobuf:"bytes,1,opt,name=function,proto3,oneof" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MoveCallFilter) Reset() {
	*x = MoveCallFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MoveCallFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoveCallFilter) ProtoMessage() {}

func (x *MoveCallFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoveCallFilter.ProtoReflect.Descriptor instead.
func (*MoveCallFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{9}
}

func (x *MoveCallFilter) GetFunction() string {
	if x != nil && x.Function != nil {
		return *x.Function
	}
	return ""
}

// Match by an event's package/module fields, specified as a `::`-delimited
// Move path. These identify the top-level Move call that triggered the event.
//
// Specificity levels:
//
//	"0xpkg"               -> matches events with this package_id
//	"0xpkg::module"       -> matches events with this package_id and module
type EmitModuleFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Move path of the form `package[::module]`.
	Module        *string `protobuf:"bytes,1,opt,name=module,proto3,oneof" json:"module,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmitModuleFilter) Reset() {
	*x = EmitModuleFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmitModuleFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitModuleFilter) ProtoMessage() {}

func (x *EmitModuleFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitModuleFilter.ProtoReflect.Descriptor instead.
func (*EmitModuleFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{10}
}

func (x *EmitModuleFilter) GetModule() string {
	if x != nil && x.Module != nil {
		return *x.Module
	}
	return ""
}

// Match by event struct type, specified as a Move type string.
//
// Specificity levels:
//
//	"0xaddr"                              -> matches events whose type is defined at this address
//	"0xaddr::module"                      -> matches events whose type is in this module
//	"0xaddr::module::Name"                -> matches events with this type name (any instantiation)
//	"0xaddr::module::Name<T1, T2>"        -> matches events with this exact generic instantiation
type EventTypeFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Move type string of the form
	// `address[::module[::Name[<type_params>]]]`.
	EventType     *string `protobuf:"bytes,1,opt,name=event_type,json=eventType,proto3,oneof" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventTypeFilter) Reset() {
	*x = EventTypeFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventTypeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventTypeFilter) ProtoMessage() {}

func (x *EventTypeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventTypeFilter.ProtoReflect.Descriptor instead.
func (*EventTypeFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{11}
}

func (x *EventTypeFilter) GetEventType() string {
	if x != nil && x.EventType != nil {
		return *x.EventType
	}
	return ""
}

// Match by authenticated event stream head.
type EventStreamHeadFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The stream id address (hex-encoded).
	StreamId      *string `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3,oneof" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventStreamHeadFilter) Reset() {
	*x = EventStreamHeadFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventStreamHeadFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventStreamHeadFilter) ProtoMessage() {}

func (x *EventStreamHeadFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventStreamHeadFilter.ProtoReflect.Descriptor instead.
func (*EventStreamHeadFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{12}
}

func (x *EventStreamHeadFilter) GetStreamId() string {
	if x != nil && x.StreamId != nil {
		return *x.StreamId
	}
	return ""
}

// Match transactions that wrote a Move package.
type PackageWriteFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageWriteFilter) Reset() {
	*x = PackageWriteFilter{}
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageWriteFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageWriteFilter) ProtoMessage() {}

func (x *PackageWriteFilter) ProtoReflect() protoreflect.Message {
	mi := &file_sui_rpc_v2_filter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageWriteFilter.ProtoReflect.Descriptor instead.
func (*PackageWriteFilter) Descriptor() ([]byte, []int) {
	return file_sui_rpc_v2_filter_proto_rawDescGZIP(), []int{13}
}

var File_sui_rpc_v2_filter_proto protoreflect.FileDescriptor

const file_sui_rpc_v2_filter_proto_rawDesc = "" +
	"\n" +
	"\x17sui/rpc/v2/filter.proto\x12\n" +
	"sui.rpc.v2\"F\n" +
	"\x11TransactionFilter\x121\n" +
	"\x05terms\x18\x01 \x03(\v2\x1b.sui.rpc.v2.TransactionTermR\x05terms\"M\n" +
	"\x0fTransactionTerm\x12:\n" +
	"\bliterals\x18\x01 \x03(\v2\x1e.sui.rpc.v2.TransactionLiteralR\bliterals\"\xde\x04\n" +
	"\x12TransactionLiteral\x12\x18\n" +
	"\anegated\x18\x01 \x01(\bR\anegated\x122\n" +
	"\x06sender\x18\x02 \x01(\v2\x18.sui.rpc.v2.SenderFilterH\x00R\x06sender\x12N\n" +
	"\x10affected_address\x18\x03 \x01(\v2!.sui.rpc.v2.AffectedAddressFilterH\x00R\x0faffectedAddress\x12K\n" +
	"\x0faffected_object\x18\x04 \x01(\v2 .sui.rpc.v2.AffectedObjectFilterH\x00R\x0eaffectedObject\x129\n" +
	"\tmove_call\x18\x05 \x01(\v2\x1a.sui.rpc.v2.MoveCallFilterH\x00R\bmoveCall\x12?\n" +
	"\vemit_module\x18\x06 \x01(\v2\x1c.sui.rpc.v2.EmitModuleFilterH\x00R\n" +
	"emitModule\x12<\n" +
	"\n" +
	"event_type\x18\a \x01(\v2\x1b.sui.rpc.v2.EventTypeFilterH\x00R\teventType\x12O\n" +
	"\x11event_stream_head\x18\b \x01(\v2!.sui.rpc.v2.EventStreamHeadFilterH\x00R\x0feventStreamHead\x12E\n" +
	"\rpackage_write\x18\t \x01(\v2\x1e.sui.rpc.v2.PackageWriteFilterH\x00R\fpackageWriteB\v\n" +
	"\tpredicate\":\n" +
	"\vEventFilter\x12+\n" +
	"\x05terms\x18\x01 \x03(\v2\x15.sui.rpc.v2.EventTermR\x05terms\"A\n" +
	"\tEventTerm\x124\n" +
	"\bliterals\x18\x01 \x03(\v2\x18.sui.rpc.v2.EventLiteralR\bliterals\"\xb9\x02\n" +
	"\fEventLiteral\x12\x18\n" +
	"\anegated\x18\x01 \x01(\bR\anegated\x122\n" +
	"\x06sender\x18\x02 \x01(\v2\x18.sui.rpc.v2.SenderFilterH\x00R\x06sender\x12?\n" +
	"\vemit_module\x18\x03 \x01(\v2\x1c.sui.rpc.v2.EmitModuleFilterH\x00R\n" +
	"emitModule\x12<\n" +
	"\n" +
	"event_type\x18\x04 \x01(\v2\x1b.sui.rpc.v2.EventTypeFilterH\x00R\teventType\x12O\n" +
	"\x11event_stream_head\x18\x05 \x01(\v2!.sui.rpc.v2.EventStreamHeadFilterH\x00R\x0feventStreamHeadB\v\n" +
	"\tpredicate\"9\n" +
	"\fSenderFilter\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address\"B\n" +
	"\x15AffectedAddressFilter\x12\x1d\n" +
	"\aaddress\x18\x01 \x01(\tH\x00R\aaddress\x88\x01\x01B\n" +
	"\n" +
	"\b_address\"F\n" +
	"\x14AffectedObjectFilter\x12 \n" +
	"\tobject_id\x18\x01 \x01(\tH\x00R\bobjectId\x88\x01\x01B\f\n" +
	"\n" +
	"_object_id\">\n" +
	"\x0eMoveCallFilter\x12\x1f\n" +
	"\bfunction\x18\x01 \x01(\tH\x00R\bfunction\x88\x01\x01B\v\n" +
	"\t_function\":\n" +
	"\x10EmitModuleFilter\x12\x1b\n" +
	"\x06module\x18\x01 \x01(\tH\x00R\x06module\x88\x01\x01B\t\n" +
	"\a_module\"D\n" +
	"\x0fEventTypeFilter\x12\"\n" +
	"\n" +
	"event_type\x18\x01 \x01(\tH\x00R\teventType\x88\x01\x01B\r\n" +
	"\v_event_type\"G\n" +
	"\x15EventStreamHeadFilter\x12 \n" +
	"\tstream_id\x18\x01 \x01(\tH\x00R\bstreamId\x88\x01\x01B\f\n" +
	"\n" +
	"_stream_id\"\x14\n" +
	"\x12PackageWriteFilterB\x8a\x01\n" +
	"\x0ecom.sui.rpc.v2B\vFilterProtoP\x01Z!github.com/drpcorg/public/pkg/sui\xa2\x02\x03SRX\xaa\x02\n" +
	"Sui.Rpc.V2\xca\x02\n" +
	"Sui\\Rpc\\V2\xe2\x02\x16Sui\\Rpc\\V2\\GPBMetadata\xea\x02\fSui::Rpc::V2b\x06proto3"

var (
	file_sui_rpc_v2_filter_proto_rawDescOnce sync.Once
	file_sui_rpc_v2_filter_proto_rawDescData []byte
)

func file_sui_rpc_v2_filter_proto_rawDescGZIP() []byte {
	file_sui_rpc_v2_filter_proto_rawDescOnce.Do(func() {
		file_sui_rpc_v2_filter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_filter_proto_rawDesc), len(file_sui_rpc_v2_filter_proto_rawDesc)))
	})
	return file_sui_rpc_v2_filter_proto_rawDescData
}

var file_sui_rpc_v2_filter_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_sui_rpc_v2_filter_proto_goTypes = []any{
	(*TransactionFilter)(nil),     // 0: sui.rpc.v2.TransactionFilter
	(*TransactionTerm)(nil),       // 1: sui.rpc.v2.TransactionTerm
	(*TransactionLiteral)(nil),    // 2: sui.rpc.v2.TransactionLiteral
	(*EventFilter)(nil),           // 3: sui.rpc.v2.EventFilter
	(*EventTerm)(nil),             // 4: sui.rpc.v2.EventTerm
	(*EventLiteral)(nil),          // 5: sui.rpc.v2.EventLiteral
	(*SenderFilter)(nil),          // 6: sui.rpc.v2.SenderFilter
	(*AffectedAddressFilter)(nil), // 7: sui.rpc.v2.AffectedAddressFilter
	(*AffectedObjectFilter)(nil),  // 8: sui.rpc.v2.AffectedObjectFilter
	(*MoveCallFilter)(nil),        // 9: sui.rpc.v2.MoveCallFilter
	(*EmitModuleFilter)(nil),      // 10: sui.rpc.v2.EmitModuleFilter
	(*EventTypeFilter)(nil),       // 11: sui.rpc.v2.EventTypeFilter
	(*EventStreamHeadFilter)(nil), // 12: sui.rpc.v2.EventStreamHeadFilter
	(*PackageWriteFilter)(nil),    // 13: sui.rpc.v2.PackageWriteFilter
}
var file_sui_rpc_v2_filter_proto_depIdxs = []int32{
	1,  // 0: sui.rpc.v2.TransactionFilter.terms:type_name -> sui.rpc.v2.TransactionTerm
	2,  // 1: sui.rpc.v2.TransactionTerm.literals:type_name -> sui.rpc.v2.TransactionLiteral
	6,  // 2: sui.rpc.v2.TransactionLiteral.sender:type_name -> sui.rpc.v2.SenderFilter
	7,  // 3: sui.rpc.v2.TransactionLiteral.affected_address:type_name -> sui.rpc.v2.AffectedAddressFilter
	8,  // 4: sui.rpc.v2.TransactionLiteral.affected_object:type_name -> sui.rpc.v2.AffectedObjectFilter
	9,  // 5: sui.rpc.v2.TransactionLiteral.move_call:type_name -> sui.rpc.v2.MoveCallFilter
	10, // 6: sui.rpc.v2.TransactionLiteral.emit_module:type_name -> sui.rpc.v2.EmitModuleFilter
	11, // 7: sui.rpc.v2.TransactionLiteral.event_type:type_name -> sui.rpc.v2.EventTypeFilter
	12, // 8: sui.rpc.v2.TransactionLiteral.event_stream_head:type_name -> sui.rpc.v2.EventStreamHeadFilter
	13, // 9: sui.rpc.v2.TransactionLiteral.package_write:type_name -> sui.rpc.v2.PackageWriteFilter
	4,  // 10: sui.rpc.v2.EventFilter.terms:type_name -> sui.rpc.v2.EventTerm
	5,  // 11: sui.rpc.v2.EventTerm.literals:type_name -> sui.rpc.v2.EventLiteral
	6,  // 12: sui.rpc.v2.EventLiteral.sender:type_name -> sui.rpc.v2.SenderFilter
	10, // 13: sui.rpc.v2.EventLiteral.emit_module:type_name -> sui.rpc.v2.EmitModuleFilter
	11, // 14: sui.rpc.v2.EventLiteral.event_type:type_name -> sui.rpc.v2.EventTypeFilter
	12, // 15: sui.rpc.v2.EventLiteral.event_stream_head:type_name -> sui.rpc.v2.EventStreamHeadFilter
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_sui_rpc_v2_filter_proto_init() }
func file_sui_rpc_v2_filter_proto_init() {
	if File_sui_rpc_v2_filter_proto != nil {
		return
	}
	file_sui_rpc_v2_filter_proto_msgTypes[2].OneofWrappers = []any{
		(*TransactionLiteral_Sender)(nil),
		(*TransactionLiteral_AffectedAddress)(nil),
		(*TransactionLiteral_AffectedObject)(nil),
		(*TransactionLiteral_MoveCall)(nil),
		(*TransactionLiteral_EmitModule)(nil),
		(*TransactionLiteral_EventType)(nil),
		(*TransactionLiteral_EventStreamHead)(nil),
		(*TransactionLiteral_PackageWrite)(nil),
	}
	file_sui_rpc_v2_filter_proto_msgTypes[5].OneofWrappers = []any{
		(*EventLiteral_Sender)(nil),
		(*EventLiteral_EmitModule)(nil),
		(*EventLiteral_EventType)(nil),
		(*EventLiteral_EventStreamHead)(nil),
	}
	file_sui_rpc_v2_filter_proto_msgTypes[6].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[7].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[8].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[9].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[10].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[11].OneofWrappers = []any{}
	file_sui_rpc_v2_filter_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sui_rpc_v2_filter_proto_rawDesc), len(file_sui_rpc_v2_filter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sui_rpc_v2_filter_proto_goTypes,
		DependencyIndexes: file_sui_rpc_v2_filter_proto_depIdxs,
		MessageInfos:      file_sui_rpc_v2_filter_proto_msgTypes,
	}.Build()
	File_sui_rpc_v2_filter_proto = out.File
	file_sui_rpc_v2_filter_proto_goTypes = nil
	file_sui_rpc_v2_filter_proto_depIdxs = nil
}
